//! Windows sparse presets and semantic transfer share this field contract (#3879/#3880).
use crate::adjustment::f;
use raw_core::types::{
    transfer_mode, AdjustmentGroup, AdjustmentModel, FieldKind, WbScaleVersion, ADJUSTMENT_SCHEMA,
    NON_COPYABLE_FIELDS,
};

pub(crate) fn emit_cs() -> String {
    let mut out = String::from("// Generated by tools/codegen.sh from raw-core's adjustment schema and transfer table. DO NOT EDIT.\n\nnamespace Maple.WinUI.Generated;\n\npublic sealed record AdjustmentFieldSpec(string Name, string Member, string Kind, double Minimum, double Maximum, double DefaultNumber, bool Copyable, string TransferMode);\npublic sealed record AdjustmentGroupSpec(string Id, string Label, string[] Fields);\n\npublic static class AdjustmentFields\n{\n    public static readonly AdjustmentFieldSpec[] All =\n    {\n");
    for field in ADJUSTMENT_SCHEMA {
        let member = field
            .name
            .split('_')
            .map(|part| format!("{}{}", part[..1].to_uppercase(), &part[1..]))
            .collect::<String>();
        let kind = match field.kind {
            FieldKind::F32 => "Number",
            FieldKind::Enum => "Enum",
            FieldKind::String => "String",
            FieldKind::ToneCurve => "Curve",
        };
        out.push_str(&format!(
            "        new(\"{}\", \"{member}\", \"{kind}\", {}, {}, {}, {}, \"{}\"),\n",
            field.name,
            f(field.range.0),
            f(field.range.1),
            f(field.default_f32),
            !NON_COPYABLE_FIELDS.contains(&field.name),
            transfer_mode(field.name).expect("transfer decision").name()
        ));
    }
    out.push_str("    };\n\n    public static readonly AdjustmentGroupSpec[] Groups =\n    {\n");
    for group in AdjustmentGroup::ALL {
        let fields = group
            .fields()
            .iter()
            .map(|name| format!("\"{name}\""))
            .collect::<Vec<_>>()
            .join(", ");
        out.push_str(&format!(
            "        new(\"{}\", \"{}\", new[] {{ {fields} }}),\n",
            group.id(),
            group.label()
        ));
    }
    out.push_str("    };\n\n    public static readonly System.Collections.Generic.IReadOnlyDictionary<string, string> TransferModes = new System.Collections.Generic.Dictionary<string, string>\n    {\n");
    let fields = AdjustmentGroup::ALL
        .iter()
        .flat_map(|g| g.fields().iter().copied())
        .chain(NON_COPYABLE_FIELDS.iter().copied())
        .collect::<std::collections::BTreeSet<_>>();
    for field in fields {
        out.push_str(&format!(
            "        [\"{field}\"] = \"{}\",\n",
            transfer_mode(field).expect("transfer decision").name()
        ));
    }
    let scale = match AdjustmentModel::default().wb_scale_version {
        WbScaleVersion::V1 => 1,
        WbScaleVersion::V2 => 2,
        WbScaleVersion::V3 => 3,
        WbScaleVersion::V4 => 4,
        WbScaleVersion::V5 => 5,
    };
    out.push_str(&format!(
        "    }};\n\n    public const int CurrentWhiteBalanceScaleVersion = {scale};\n}}\n"
    ));
    out
}

#[cfg(test)]
mod tests {
    use super::*;
    #[test]
    fn every_shared_field_and_group_has_a_windows_contract() {
        let out = emit_cs();
        for field in ADJUSTMENT_SCHEMA {
            assert!(out.contains(&format!("new(\"{}\",", field.name)));
            assert!(out.contains(transfer_mode(field.name).unwrap().name()));
        }
        for group in AdjustmentGroup::ALL {
            assert!(out.contains(&format!("new(\"{}\", \"{}\",", group.id(), group.label())));
        }
        assert!(out.contains("\"lens_profile\", \"LensProfile\", \"String\", 0.0, 0.0, 0.0, false"));
        assert!(out.contains("\"temperature\", \"Temperature\", \"Number\", 2000.0, 12000.0, 6500.0, true, \"Relative\""));
        assert_eq!(out, emit_cs());
    }
}
