//! Adjustment-schema emitters — Swift + TypeScript output for
//! `raw_core::types::ADJUSTMENT_SCHEMA` (#118).
//!
//! Split out of `main.rs` in #366, when the point-curve emit arms pushed
//! that file past CONTRIBUTING.md's 600-line hard budget. `main.rs` keeps
//! the CLI wiring and the shared `camel_case` helper (`ui_tokens.rs` uses
//! it too); everything that knows the adjustment schema lives here.

use raw_core::types::{FieldKind, FieldSpec};
use raw_core::PIPELINE_OUTPUT_VERSION;

use crate::camel_case;

const BANNER_SWIFT: &str = "// THIS FILE IS GENERATED BY tools/codegen.sh. DO NOT EDIT.\n\
     // Source: src/raw-pipeline/raw-core/src/types/adjustment.rs (ADJUSTMENT_SCHEMA)\n\
     // and src/raw-pipeline/raw-core/src/version.rs (PIPELINE_OUTPUT_VERSION).\n";

const BANNER_TS: &str = "// THIS FILE IS GENERATED BY tools/codegen.sh. DO NOT EDIT.\n\
     // Source: src/raw-pipeline/raw-core/src/types/adjustment.rs (ADJUSTMENT_SCHEMA)\n\
     // and src/raw-pipeline/raw-core/src/version.rs (PIPELINE_OUTPUT_VERSION).\n";

/// Render an `f32` schema constant in a stable, deterministic form.
///
/// Used uniformly for `range.0`, `range.1`, and `default_f32`. `{:?}` picks
/// the shortest round-tripping decimal, which is stable across Rust versions
/// for the literals in `ADJUSTMENT_SCHEMA` (they're all small exact decimals
/// like `2000.0`, `-100.0`, `0.5`, `25.0`).
fn f(v: f32) -> String {
    let s = format!("{:?}", v);
    // `{:?}` on f32 always includes a decimal point. Belt-and-braces guard
    // in case that ever changes: append `.0` if no fractional indicator.
    if s.contains('.') || s.contains('e') || s.contains('E') {
        s
    } else {
        format!("{}.0", s)
    }
}

/// Rewrite backtick-wrapped Rust-style snake_case identifiers in a doc string
/// to their target-language camelCase form. Only tokens that exactly match a
/// schema `name` are rewritten — generic snake_case text (e.g. an XMP key
/// fragment like `crs:Sharpness`) is left alone.
///
/// Motivation (PR #463 review): the canonical `ADJUSTMENT_SCHEMA` doc strings
/// reference sibling fields by their Rust snake_case names (e.g. "use
/// `capture_sharpening_sigma`"). Emitting that verbatim into Swift/TS sends
/// platform callers chasing an identifier that does not exist in their
/// language — Swift sees `captureSharpeningSigma`, TS sees
/// `captureSharpeningSigma`. Both targets use camelCase, so a single
/// rewriter covers both.
fn rewrite_doc_identifiers(doc: &str, schema: &[FieldSpec]) -> String {
    let mut out = String::with_capacity(doc.len());
    let bytes = doc.as_bytes();
    let mut i = 0;
    while i < bytes.len() {
        if bytes[i] == b'`' {
            // Find the closing backtick.
            if let Some(rel_end) = bytes[i + 1..].iter().position(|&b| b == b'`') {
                let end = i + 1 + rel_end;
                let token = &doc[i + 1..end];
                // Only rewrite if the token exactly matches a schema field
                // name (snake_case). Leaves things like `papp:Foo` and
                // `crs:Bar` untouched because they do not appear as schema
                // names.
                if schema.iter().any(|s| s.name == token) {
                    out.push('`');
                    out.push_str(&camel_case(token));
                    out.push('`');
                } else {
                    out.push_str(&doc[i..=end]);
                }
                i = end + 1;
                continue;
            }
        }
        out.push(doc[i..].chars().next().unwrap());
        i += doc[i..].chars().next().unwrap().len_utf8();
    }
    out
}

// -------------------------------------------------------------------------
// Swift
// -------------------------------------------------------------------------

pub(crate) fn emit_swift(schema: &[FieldSpec]) -> String {
    let mut s = String::new();
    s.push_str(BANNER_SWIFT);
    s.push_str("//\n");
    s.push_str("// Emits range constants and a canonical field-name enum for\n");
    s.push_str("// `AdjustmentModel`. The struct itself + defaults + init stay\n");
    s.push_str("// hand-written in `AdjustmentModel.swift`; Apple's defaults\n");
    s.push_str("// match raw-core's canonical values (per #326, sharpen converges\n");
    s.push_str("// to the reference renderer's import baseline: 40 / 1.0 / 25 / 0).\n");
    s.push_str("// Point-curve fields (#366) contribute a `FieldName` case and no\n");
    s.push_str("// range; the `ToneCurve` value type is hand-written in\n");
    s.push_str("// `ToneCurve.swift`.\n\n");
    s.push_str("import Foundation\n\n");

    // FieldName enum — canonical snake_case names from the schema.
    s.push_str("extension AdjustmentModel {\n");
    s.push_str("    /// Canonical field identifiers, snake_case as recorded in\n");
    s.push_str("    /// `raw_core::types::ADJUSTMENT_SCHEMA`. Use these when you need\n");
    s.push_str("    /// a stable string key independent of Swift's camelCase property names.\n");
    s.push_str("    public enum FieldName: String, CaseIterable, Sendable, Hashable {\n");
    for spec in schema {
        // case <camel> = "<snake>"
        let case_ident = camel_case(spec.name);
        s.push_str(&format!(
            "        case {} = \"{}\"\n",
            case_ident, spec.name
        ));
    }
    s.push_str("    }\n\n");

    // Range constants for F32 fields. `Enum` and `ToneCurve` fields have no
    // numeric range — the match is exhaustive (no wildcard arm) so a future
    // FieldKind variant is a compile error here rather than a silent skip.
    s.push_str("    // MARK: - Range constants (canonical, generated)\n\n");
    for spec in schema {
        match spec.kind {
            FieldKind::F32 => {
                let camel = camel_case(spec.name);
                let doc = rewrite_doc_identifiers(spec.doc, schema);
                s.push_str(&format!("    /// {}\n", doc));
                s.push_str(&format!(
                    "    public static let {}Range: ClosedRange<Double> = {}...{}\n",
                    camel,
                    f(spec.range.0),
                    f(spec.range.1),
                ));
            }
            FieldKind::Enum | FieldKind::ToneCurve => {}
        }
    }

    // Pipeline-output version (#1926). Monotonic cache-invalidation salt for
    // the develop pipeline's rendered output; single-sourced from
    // `raw_core::version::PIPELINE_OUTPUT_VERSION`. Rendered-output caches key
    // on it so one bump in raw-core invalidates every stale entry.
    s.push_str("\n    // MARK: - Pipeline-output version (canonical, generated)\n\n");
    s.push_str(
        "    /// Monotonic version of the develop pipeline's rendered output\n\
         \x20   /// (#1926). Bump in `raw_core::version::PIPELINE_OUTPUT_VERSION`\n\
         \x20   /// whenever a change alters the pixels produced for the same\n\
         \x20   /// (RAW, sidecar) input, or silently reinterprets a stored\n\
         \x20   /// AdjustmentModel value without a load-time converter. Fold it\n\
         \x20   /// into every rendered-output cache key so a single bump\n\
         \x20   /// invalidates stale entries across all platforms.\n",
    );
    s.push_str(&format!(
        "    public static let pipelineOutputVersion: UInt32 = {}\n",
        PIPELINE_OUTPUT_VERSION,
    ));

    s.push_str("}\n\n");

    // Copy/paste/sync groups (#944). Top-level type, not nested on
    // `AdjustmentModel`: the selective-paste UI on both platforms needs it
    // independently of any one model instance.
    s.push_str(&crate::adjustment_groups::emit_swift());
    s
}

// -------------------------------------------------------------------------
// TypeScript
// -------------------------------------------------------------------------

pub(crate) fn emit_ts(schema: &[FieldSpec]) -> String {
    let mut s = String::new();
    s.push_str(BANNER_TS);
    s.push_str("//\n");
    s.push_str("// Emits the AdjustmentModel field interface, range constants, and a\n");
    s.push_str("// default factory. Hand-written extensions (e.g. `WhiteBalancePreset`)\n");
    s.push_str("// live alongside in `adjustment-model.ts` and augment this shape.\n\n");

    // Point-curve fields (#366) reference the hand-written `ToneCurve`
    // interface from `models/adjustment-model.ts`. The import is type-only,
    // so the module cycle (models imports the generated defaults factory)
    // is erased at compile time and never exists at runtime.
    s.push_str("import type { ToneCurve } from '../models/adjustment-model';\n\n");

    // HighlightRecoveryMode union. `Blend` and `Luminance` are legacy
    // back-compat variants kept so old XMP sidecars continue to parse;
    // both upgrade to `ChromaticAdaptation` at apply time (see
    // raw-core::stages::highlight_recovery). Emitted in the multi-line
    // form prettier produces past its print-width threshold so the
    // codegen-drift + format-check gates agree without a post-step
    // through `prettier --write`.
    s.push_str(
        "export type HighlightRecoveryMode =\n  \
         | 'Off'\n  \
         | 'Blend'\n  \
         | 'Luminance'\n  \
         | 'ChromaticAdaptation'\n  \
         | 'OklabChromaReduction';\n\n",
    );

    // DisplayLookCurve (ticket #371; retired in #443 — Wave-3 closing step
    // of #416). Both variants are now identical no-ops at the pipeline
    // level; the enum is kept on `AdjustmentModel` and emitted to Swift /
    // TS so `papp:Look` in pre-#443 sidecars round-trips. See
    // `raw-core::types::adjustment::Look`.
    s.push_str("export type Look = 'Neutral' | 'Default';\n\n");

    // Render-shaping profile (Auto Profile Phase 1, ticket #536; AcrMatch
    // #1722). `Auto` (default) fits a per-image curve from the embedded JPEG
    // preview at render time; `Neutral` runs the AgX scene-referred view
    // transform; `AcrMatch` runs the fitted ACR-match model (selectable, not
    // yet default). Pre-#536 sidecars carrying `papp:Look` migrate
    // transparently in the parser (Default → Auto, Neutral → Neutral). See
    // raw-core::types::adjustment::Profile.
    s.push_str("export type Profile = 'Auto' | 'Neutral' | 'AcrMatch';\n\n");

    // Tone-curve application mode (ticket #436). `PerChannel` applies the
    // three R/G/B curves independently (hue shifts); `RatioPreserving`
    // folds them through Rec.2020 luma to preserve hue. Default is
    // `PerChannel` for backward compatibility (see
    // raw-core::stages::tone_curves).
    s.push_str("export type ToneCurveMode = 'PerChannel' | 'RatioPreserving';\n\n");

    // User white-balance method (ticket #431). `Cat16` performs proper
    // chromatic adaptation in CAT16 LMS cone space (default since #431);
    // `DiagonalRec2020` is the legacy von-Kries diagonal-gain path
    // retained for parity A/B (see raw-core::stages::white_balance).
    s.push_str("export type WbMethod = 'Cat16' | 'DiagonalRec2020';\n\n");

    // Per-image auto-exposure mode (ticket #429). `On` (default) anchors
    // scene mid-gray to 0.18 before AgX so every camera lands at the
    // same point on the sigmoid by default; `Off` skips anchoring for
    // strict scene-referred output. The user `exposure` slider stacks
    // additively in EV on top (see raw-core::stages::auto_exposure).
    s.push_str("export type AutoExposureMode = 'Off' | 'On';\n\n");

    // Hot/dead-pixel suppression (#1106). `Off` (default) skips the
    // pre-demosaic defect-replacement stage bit-identically; `On` replaces
    // same-color-neighbor outliers with the neighborhood median inside the
    // decode product (see raw-core::stages::hot_pixel).
    s.push_str("export type HotPixelSuppressionMode = 'Off' | 'On';\n\n");

    // Generated interface.
    s.push_str("export interface GeneratedAdjustmentModel {\n");
    for spec in schema {
        let camel = camel_case(spec.name);
        let doc = rewrite_doc_identifiers(spec.doc, schema);
        match spec.kind {
            FieldKind::F32 => {
                s.push_str(&format!(
                    "  /** {} Range: [{}, {}]. */\n  {}: number;\n",
                    doc,
                    f(spec.range.0),
                    f(spec.range.1),
                    camel,
                ));
            }
            FieldKind::Enum => {
                // Only HighlightRecoveryMode exists today; emit its TS type name.
                let ts_ty = spec.enum_name;
                s.push_str(&format!("  /** {} */\n  {}: {};\n", doc, camel, ts_ty,));
            }
            FieldKind::ToneCurve => {
                // Point curve (#366). One curve type for every curve field;
                // the interface is hand-written in `models/adjustment-model.ts`.
                s.push_str(&format!("  /** {} */\n  {}: ToneCurve;\n", doc, camel));
            }
        }
    }
    s.push_str("}\n\n");

    // Range constants.
    s.push_str(
        "/** Canonical `[min, max]` range for each scalar field, generated from raw-core. */\n",
    );
    s.push_str("export const ADJUSTMENT_RANGES = {\n");
    for spec in schema {
        // Exhaustive on purpose (see `emit_swift`): only scalars have a range.
        match spec.kind {
            FieldKind::F32 => {
                let camel = camel_case(spec.name);
                s.push_str(&format!(
                    "  {}: [{}, {}] as const,\n",
                    camel,
                    f(spec.range.0),
                    f(spec.range.1),
                ));
            }
            FieldKind::Enum | FieldKind::ToneCurve => {}
        }
    }
    s.push_str("} as const;\n\n");

    // Default factory.
    s.push_str("/** Canonical raw-core defaults, generated from `ADJUSTMENT_SCHEMA`. */\n");
    s.push_str("export function defaultGeneratedAdjustmentModel(): GeneratedAdjustmentModel {\n");
    s.push_str("  return {\n");
    for spec in schema {
        let camel = camel_case(spec.name);
        match spec.kind {
            FieldKind::F32 => {
                s.push_str(&format!("    {}: {},\n", camel, f(spec.default_f32)));
            }
            FieldKind::Enum => {
                // No enum-default slot on `FieldSpec` (the existing schema
                // only carries `default_f32` for scalars). Hard-coded per
                // enum_name; mirrors raw-core's `Default for <Enum>` impls.
                let default_variant = match spec.enum_name {
                    "HighlightRecoveryMode" => "ChromaticAdaptation",
                    // DisplayLookCurve (#371). New users get the empirical
                    // Look, not Neutral.
                    "Look" => "Default",
                    // Tone-curve mode (#436). Default preserves pre-#436
                    // behavior (absent attribute = current pipeline output).
                    "ToneCurveMode" => "PerChannel",
                    // User WB method (#431). New users get proper chromatic
                    // adaptation in CAT16 cone space.
                    "WbMethod" => "Cat16",
                    // Per-image auto-exposure (#429). `On` is the new default —
                    // anchor scene mid-gray to 0.18 before AgX.
                    "AutoExposureMode" => "On",
                    // Auto Profile (#536). Default fits a per-image curve
                    // from the embedded preview; `Neutral` runs AgX.
                    "Profile" => "Auto",
                    // Hot/dead-pixel suppression (#1106). Off until a
                    // harness sweep shows enabling is free on clean fixtures.
                    "HotPixelSuppressionMode" => "Off",
                    other => panic!(
                        "codegen: no default mapping for enum `{}` — add one \
                         alongside the matching Rust `Default` impl",
                        other
                    ),
                };
                s.push_str(&format!("    {}: '{}',\n", camel, default_variant));
            }
            FieldKind::ToneCurve => {
                // Identity curve (#366) — the empty control-point list, the
                // same canonical default `ToneCurve::default()` carries in
                // raw-core and `ToneCurve.identity` carries on Apple. A fresh
                // object per call so callers can mutate the model in place
                // without aliasing another model's curve.
                s.push_str(&format!("    {}: {{ points: [] }},\n", camel));
            }
        }
    }
    s.push_str("  };\n");
    s.push_str("}\n");

    // Pipeline-output version (#1926). Monotonic cache-invalidation salt for
    // the develop pipeline's rendered output; single-sourced from
    // `raw_core::version::PIPELINE_OUTPUT_VERSION`. Rendered-output caches key
    // on it so one bump in raw-core invalidates every stale entry.
    s.push_str(
        "\n/**\n * Monotonic version of the develop pipeline's rendered output (#1926).\n \
         * Bump in `raw_core::version::PIPELINE_OUTPUT_VERSION` whenever a change alters\n \
         * the pixels produced for the same (RAW, sidecar) input, or silently\n \
         * reinterprets a stored AdjustmentModel value without a load-time converter.\n \
         * Fold it into every rendered-output cache key so a single bump invalidates\n \
         * stale entries across all platforms.\n */\n",
    );
    s.push_str(&format!(
        "export const PIPELINE_OUTPUT_VERSION = {};\n\n",
        PIPELINE_OUTPUT_VERSION,
    ));

    // Copy/paste/sync groups (#944) — same table Swift gets above.
    s.push_str(&crate::adjustment_groups::emit_ts());
    s
}

#[cfg(test)]
mod tests {
    use super::*;
    use raw_core::types::ADJUSTMENT_SCHEMA;

    #[test]
    fn camel_case_basic() {
        assert_eq!(camel_case("temperature"), "temperature");
        assert_eq!(camel_case("sharpen_amount"), "sharpenAmount");
        assert_eq!(camel_case("nr_color"), "nrColor");
        assert_eq!(camel_case("highlight_recovery"), "highlightRecovery");
    }

    #[test]
    fn f_renders_with_decimal() {
        assert!(f(2000.0).contains('.'));
        assert!(f(-100.0).contains('.'));
        assert!(f(0.5).contains('.'));
        assert!(f(25.0).contains('.'));
    }

    #[test]
    fn swift_emits_field_name_enum_and_ranges() {
        let out = emit_swift(ADJUSTMENT_SCHEMA);
        assert!(out.contains("public enum FieldName"));
        assert!(out.contains("case temperature = \"temperature\""));
        assert!(out.contains("case sharpenAmount = \"sharpen_amount\""));
        assert!(out.contains("public static let temperatureRange: ClosedRange<Double>"));
        // No defaults emitted.
        assert!(!out.contains("public static let `default`"));
        assert!(!out.contains("defaultAdjustmentModel"));
        // Pipeline-output version (#1926): single-sourced from raw-core and
        // emitted as a static on AdjustmentModel for the rendered-output caches.
        assert!(out.contains(&format!(
            "public static let pipelineOutputVersion: UInt32 = {}",
            PIPELINE_OUTPUT_VERSION
        )));
    }

    #[test]
    fn ts_emits_interface_ranges_and_defaults() {
        let out = emit_ts(ADJUSTMENT_SCHEMA);
        assert!(out.contains("export interface GeneratedAdjustmentModel"));
        assert!(out.contains("temperature: number;"));
        assert!(out.contains("highlightRecovery: HighlightRecoveryMode;"));
        assert!(out.contains("ADJUSTMENT_RANGES"));
        assert!(out.contains("defaultGeneratedAdjustmentModel"));
        assert!(out.contains("temperature: 6500"));
        // Auto Profile (#536) + AcrMatch (#1722): Profile enum is in
        // ADJUSTMENT_SCHEMA, so the codegen must emit the type (with all
        // variants), the interface field, and a default.
        assert!(out.contains("export type Profile = 'Auto' | 'Neutral' | 'AcrMatch';"));
        assert!(out.contains("profile: Profile;"));
        assert!(out.contains("profile: 'Auto'"));
        // Pipeline-output version (#1926): single-sourced from raw-core and
        // emitted as a top-level const for the Web rendered-output caches.
        assert!(out.contains(&format!(
            "export const PIPELINE_OUTPUT_VERSION = {};",
            PIPELINE_OUTPUT_VERSION
        )));
    }

    /// Point curves (#366): Swift gets the canonical `FieldName` cases and
    /// nothing else — no range constant exists for a curve, and the
    /// `ToneCurve` value type is hand-written in `ToneCurve.swift`.
    #[test]
    fn swift_emits_tone_curve_field_names_without_ranges() {
        let out = emit_swift(ADJUSTMENT_SCHEMA);
        for (case_name, snake) in [
            ("toneCurveLuma", "tone_curve_luma"),
            ("toneCurveRed", "tone_curve_red"),
            ("toneCurveGreen", "tone_curve_green"),
            ("toneCurveBlue", "tone_curve_blue"),
        ] {
            assert!(
                out.contains(&format!("case {} = \"{}\"", case_name, snake)),
                "missing FieldName case for {}",
                snake
            );
            assert!(
                !out.contains(&format!("{}Range", case_name)),
                "curve fields have no numeric range, got one for {}",
                snake
            );
        }
        // The type is hand-written, not generated.
        assert!(!out.contains("struct ToneCurve"));
    }

    /// Point curves (#366): the TS interface members reference the
    /// hand-written `ToneCurve` interface (type-only import), the default
    /// factory hands back the identity curve, and no range is emitted.
    #[test]
    fn ts_emits_tone_curve_fields_and_identity_defaults() {
        let out = emit_ts(ADJUSTMENT_SCHEMA);
        assert!(out.contains("import type { ToneCurve } from '../models/adjustment-model';"));
        for camel in [
            "toneCurveLuma",
            "toneCurveRed",
            "toneCurveGreen",
            "toneCurveBlue",
        ] {
            assert!(
                out.contains(&format!("{}: ToneCurve;", camel)),
                "missing interface member for {}",
                camel
            );
            assert!(
                out.contains(&format!("{}: {{ points: [] }},", camel)),
                "missing identity default for {}",
                camel
            );
            assert!(
                !out.contains(&format!("  {}: [", camel)),
                "curve fields must not appear in ADJUSTMENT_RANGES ({})",
                camel
            );
        }
        // The interface is hand-written in `models/adjustment-model.ts`.
        assert!(!out.contains("export interface ToneCurve"));
    }

    #[test]
    fn rewrite_doc_identifiers_rewrites_schema_names_only() {
        // Backtick-wrapped tokens that match a schema field name are
        // rewritten to camelCase; anything else (XMP keys, prose) is left
        // alone. Per PR #463 review.
        let doc = "Deprecated: use `capture_sharpening_sigma`. See the XMP \
                   `papp:CaptureSharpeningRadius` read-path; not the \
                   `temperature` field.";
        let rewritten = rewrite_doc_identifiers(doc, ADJUSTMENT_SCHEMA);
        assert!(
            rewritten.contains("`captureSharpeningSigma`"),
            "schema field name should be camelCased, got: {}",
            rewritten
        );
        assert!(
            rewritten.contains("`temperature`"),
            "single-word schema names should pass through unchanged"
        );
        assert!(
            rewritten.contains("`papp:CaptureSharpeningRadius`"),
            "XMP keys are not schema names — must be left alone, got: {}",
            rewritten
        );
        assert!(
            !rewritten.contains("`capture_sharpening_sigma`"),
            "snake_case schema reference should have been rewritten, got: {}",
            rewritten
        );
    }

    #[test]
    fn determinism_double_emit_is_identical() {
        // Running the emitters twice in-process produces identical strings;
        // the on-disk determinism check happens in tools/codegen.sh.
        let a = emit_swift(ADJUSTMENT_SCHEMA);
        let b = emit_swift(ADJUSTMENT_SCHEMA);
        assert_eq!(a, b);
        let a = emit_ts(ADJUSTMENT_SCHEMA);
        let b = emit_ts(ADJUSTMENT_SCHEMA);
        assert_eq!(a, b);
    }
}
