//! API preset validation uses canonical snake_case scalar field names (#3663).
use raw_core::types::{FieldKind, FieldSpec};

use crate::adjustment::f;

pub(crate) fn emit_ts(schema: &[FieldSpec]) -> String {
    let mut out = String::from(
        "// THIS FILE IS GENERATED BY tools/codegen.sh. DO NOT EDIT.\n\
         // Source: raw_core::types::ADJUSTMENT_SCHEMA\n\n\
         export const NUMERIC_FIELD_RANGES: Readonly<Record<string, readonly [number, number]>> = {\n",
    );
    let mut strings = Vec::new();
    let mut free_form = Vec::new();
    for field in schema {
        match field.kind {
            FieldKind::F32 => out.push_str(&format!(
                "  {}: [{}, {}],\n",
                field.name,
                f(field.range.0),
                f(field.range.1)
            )),
            FieldKind::Enum => strings.push(field.name),
            FieldKind::String => {
                strings.push(field.name);
                free_form.push(field.name);
            }
            // Preset fields are scalar; point curves remain deliberately excluded.
            FieldKind::ToneCurve => {}
        }
    }
    out.push_str("};\n\n");
    out.push_str("export const STRING_FIELDS: ReadonlySet<string> = new Set([\n");
    for value in strings {
        out.push_str(&format!("  '{value}',\n"));
    }
    out.push_str("]);\n\n");
    out.push_str(&format!(
        "export const FREE_FORM_STRING_FIELDS: ReadonlySet<string> = new Set([{}]);\n",
        free_form
            .iter()
            .map(|name| format!("'{name}'"))
            .collect::<Vec<_>>()
            .join(", ")
    ));
    out
}
