//! Field transfer decisions from the same Rust table used by coverage tests (#3311).
use raw_core::types::{
    transfer_mode, AdjustmentGroup, NON_COPYABLE_FIELDS, TRANSFER_XMP_ATTRIBUTES,
    TRANSFER_XMP_ELEMENTS,
};

fn fields() -> impl Iterator<Item = &'static str> {
    AdjustmentGroup::ALL
        .iter()
        .flat_map(|g| g.fields().iter().copied())
        .chain(NON_COPYABLE_FIELDS.iter().copied())
}

pub fn emit_ts() -> String {
    let mut out = String::from(
        "// Generated by tools/codegen.sh from schema/groups/transfer.rs. DO NOT EDIT.\n\n\
export type AdjustmentTransferMode = 'Absolute' | 'Relative' | 'AssetRelative' | 'Unsupported';\n\n\
/** Relative WB is not assigned until #2434 supplies its baseline contract. */\n\
export const ADJUSTMENT_TRANSFER_MODES: Readonly<Record<string, AdjustmentTransferMode>> = {\n",
    );
    for field in fields() {
        out.push_str(&format!(
            "  {field}: '{}',\n",
            transfer_mode(field).expect("transfer decision").name()
        ));
    }
    out.push_str("};\n");
    out.push_str(
        "\nexport const TRANSFER_XMP_ATTRIBUTES: Readonly<Record<string, readonly string[]>> = {\n",
    );
    for (field, attributes) in TRANSFER_XMP_ATTRIBUTES {
        let values = attributes
            .iter()
            .map(|key| format!("'{key}'"))
            .collect::<Vec<_>>();
        let row = format!("  {field}: [{}],\n", values.join(", "));
        if row.len() <= 101 {
            out.push_str(&row);
        } else {
            out.push_str(&format!(
                "  {field}: [\n{}  ],\n",
                values
                    .iter()
                    .map(|value| format!("    {value},\n"))
                    .collect::<String>()
            ));
        }
    }
    out.push_str(
        "};\n\nexport const TRANSFER_XMP_ELEMENTS: Readonly<Record<string, string>> = {\n",
    );
    for (field, key) in TRANSFER_XMP_ELEMENTS {
        out.push_str(&format!("  {field}: '{key}',\n"));
    }
    out.push_str("};\n");
    out
}

pub fn emit_swift() -> String {
    let mut out = String::from(
        "// Generated by tools/codegen.sh from schema/groups/transfer.rs. DO NOT EDIT.\n\n\
public enum AdjustmentTransferMode: String, Sendable {\n\
\x20   case absolute = \"Absolute\"\n\
\x20   case relative = \"Relative\"\n\
\x20   case assetRelative = \"AssetRelative\"\n\
\x20   case unsupported = \"Unsupported\"\n\
}\n\n\
/// Relative WB is not assigned until #2434 supplies its baseline contract.\n\
public let adjustmentTransferModes: [String: AdjustmentTransferMode] = [\n",
    );
    for field in fields() {
        let name = transfer_mode(field).expect("transfer decision").name();
        let lower = format!("{}{}", name[..1].to_lowercase(), &name[1..]);
        out.push_str(&format!("    \"{field}\": .{lower},\n"));
    }
    out.push_str("]\n");
    out
}

#[cfg(test)]
mod tests {
    use super::*;
    #[test]
    fn decisions_are_generated_for_both_consumers() {
        for field in fields() {
            let mode = transfer_mode(field).unwrap().name();
            assert!(emit_ts().contains(&format!("{field}: '{mode}'")));
            assert!(emit_swift().contains(&format!("\"{field}\": .")));
        }
        assert!(emit_ts().contains("crop: 'AssetRelative'"));
        assert!(emit_ts().contains("inpaint_removals: 'Unsupported'"));
        assert_eq!(emit_ts(), emit_ts());
        assert_eq!(emit_swift(), emit_swift());
    }
}
