//! TypeScript field-lookup tables for `AdjustmentModel` — `ADJUSTMENT_RANGES`
//! plus the copy/paste/sync group tables (#944).
//!
//! Split out of `adjustment.rs` in #2683: as `ADJUSTMENT_SCHEMA` grows, the
//! combined `adjustment-model.generated.ts` file kept crossing the file-size
//! budget (CONTRIBUTING.md "File-size budget"), and moving `emit_ts_tables`
//! in-place pushed `adjustment.rs` itself past the same budget in the same
//! PR. This module emits a sibling TypeScript file
//! (`adjustment-tables.generated.ts`) carrying the field-range and
//! copy/paste-group tables, so neither generated file — nor either emitter
//! source file — needs to grow toward the 600-line hard budget as the
//! schema gains fields. There is no Swift counterpart: Swift's single
//! generated file (`AdjustmentModel+Generated.swift`) has real headroom
//! (~460/600 lines) and doesn't need the split.

use raw_core::types::{FieldKind, FieldSpec};

use crate::adjustment::f;
use crate::camel_case;

const BANNER_TS_TABLES: &str = "// THIS FILE IS GENERATED BY tools/codegen.sh. DO NOT EDIT.\n\
     // Source: src/raw-pipeline/raw-core/src/types/adjustment.rs (ADJUSTMENT_SCHEMA)\n\
     // and src/raw-pipeline/raw-core/src/types/adjustment/schema/groups.rs (AdjustmentGroup).\n\
     //\n\
     // Field-lookup tables for AdjustmentModel: the canonical [min, max]\n\
     // range per scalar field, plus the copy/paste/sync group membership\n\
     // tables (#944). Split out of adjustment-model.generated.ts (#2683) —\n\
     // as ADJUSTMENT_SCHEMA grows, the combined file kept crossing the\n\
     // file-size budget (CONTRIBUTING.md \"File-size budget\"); this sibling\n\
     // file gives both generated files real headroom.\n\n";

/// TypeScript: `ADJUSTMENT_RANGES` plus the copy/paste/sync group tables
/// (#944). Emitted to a sibling file from `adjustment-model.generated.ts`
/// (#2683 — see `BANNER_TS_TABLES`) so neither generated file grows toward
/// the 600-line hard budget as `ADJUSTMENT_SCHEMA` gains fields. Neither
/// block references `GeneratedAdjustmentModel` or `ToneCurve`, so this file
/// needs no import from its sibling.
pub(crate) fn emit_ts_tables(schema: &[FieldSpec]) -> String {
    let mut s = String::from(BANNER_TS_TABLES);
    s.push_str(
        "/** Canonical `[min, max]` range for each scalar field, generated from raw-core. */\n",
    );
    s.push_str("export const ADJUSTMENT_RANGES = {\n");
    for spec in schema {
        // Exhaustive on purpose (see `adjustment::emit_swift`): only scalars
        // have a range.
        match spec.kind {
            FieldKind::F32 => {
                let camel = camel_case(spec.name);
                s.push_str(&format!(
                    "  {}: [{}, {}] as const,\n",
                    camel,
                    f(spec.range.0),
                    f(spec.range.1),
                ));
            }
            FieldKind::Enum | FieldKind::ToneCurve | FieldKind::String => {}
        }
    }
    s.push_str("} as const;\n\n");

    // Copy/paste/sync groups (#944) — same table Swift gets appended to its
    // single generated file; Swift's file has real headroom (~460/600) so it
    // does not need the split.
    s.push_str(&crate::adjustment_groups::emit_ts());
    s
}

#[cfg(test)]
mod tests {
    use super::*;
    use raw_core::types::ADJUSTMENT_SCHEMA;

    /// Field-lookup tables (#2683): `ADJUSTMENT_RANGES` and the copy/paste
    /// group tables emit to their own file, disjoint from `emit_ts`'s
    /// interface + defaults output — neither generated file duplicates the
    /// other's content.
    #[test]
    fn ts_tables_emits_ranges_and_groups_disjoint_from_model_file() {
        let out = emit_ts_tables(ADJUSTMENT_SCHEMA);
        assert!(out.contains("export const ADJUSTMENT_RANGES = {"));
        assert!(out.contains("temperature: [2000.0, 12000.0] as const,"));
        // String-kind fields (film_look, #2683) carry no range — only F32
        // fields do; a String field must not appear as a range entry.
        assert!(!out.contains("filmLook: ["));
        assert!(out.contains("filmStrength: [0.0, 100.0] as const,"));
        // Copy/paste/sync groups (#944) — the table this file inherited
        // from the end of `emit_ts`.
        assert!(out.contains("export const ADJUSTMENT_GROUPS: readonly AdjustmentGroupSpec[]"));
        assert!(out.contains("export const ADJUSTMENT_NON_COPYABLE_FIELDS"));
        // Disjoint from the model file: no interface, no default factory, no
        // pipeline version — those stay in `emit_ts`'s output.
        assert!(!out.contains("export interface GeneratedAdjustmentModel"));
        assert!(!out.contains("defaultGeneratedAdjustmentModel"));
        assert!(!out.contains("PIPELINE_OUTPUT_VERSION"));
    }

    #[test]
    fn determinism_double_emit_is_identical() {
        // Running the emitter twice in-process produces identical strings;
        // the on-disk determinism check happens in tools/codegen.sh.
        let a = emit_ts_tables(ADJUSTMENT_SCHEMA);
        let b = emit_ts_tables(ADJUSTMENT_SCHEMA);
        assert_eq!(a, b);
    }
}
