//! Field transfer decisions from the same Rust table used by coverage tests (#3311).
use raw_core::types::{
    transfer_mode, AdjustmentGroup, AdjustmentModel, TransferMode, WbScaleVersion,
    ADJUSTMENT_SCHEMA, NON_COPYABLE_FIELDS, TRANSFER_XMP_ATTRIBUTES, TRANSFER_XMP_ELEMENTS,
};

fn fields() -> impl Iterator<Item = &'static str> {
    AdjustmentGroup::ALL
        .iter()
        .flat_map(|g| g.fields().iter().copied())
        .chain(NON_COPYABLE_FIELDS.iter().copied())
}

pub fn emit_ts() -> String {
    let mut out = String::from(
        "// Generated by tools/codegen.sh from schema/groups/transfer.rs. DO NOT EDIT.\n\n\
export type AdjustmentTransferMode = 'Absolute' | 'Relative' | 'AssetRelative' | 'Unsupported';\n\n\
/** Relative fields also support an explicit camera As Shot correction. */\n\
export const ADJUSTMENT_TRANSFER_MODES: Readonly<Record<string, AdjustmentTransferMode>> = {\n",
    );
    for field in fields() {
        out.push_str(&format!(
            "  {field}: '{}',\n",
            transfer_mode(field).expect("transfer decision").name()
        ));
    }
    out.push_str("};\n");
    let scale = match AdjustmentModel::default().wb_scale_version {
        WbScaleVersion::V1 => 1,
        WbScaleVersion::V2 => 2,
        WbScaleVersion::V3 => 3,
        WbScaleVersion::V4 => 4,
        WbScaleVersion::V5 => 5,
    };
    out.push_str(&format!(
        "\nexport const CURRENT_WHITE_BALANCE_SCALE_VERSION = {scale};\n"
    ));
    out.push_str("\nexport const RELATIVE_TRANSFER_RANGES: Readonly<Record<string, readonly [number, number]>> = {\n");
    for field in ADJUSTMENT_SCHEMA
        .iter()
        .filter(|field| transfer_mode(field.name) == Some(TransferMode::Relative))
    {
        out.push_str(&format!(
            "  {}: [{}, {}],\n",
            field.name, field.range.0, field.range.1
        ));
    }
    out.push_str("};\n");
    out.push_str(
        "\nexport const TRANSFER_XMP_ATTRIBUTES: Readonly<Record<string, readonly string[]>> = {\n",
    );
    for (field, attributes) in TRANSFER_XMP_ATTRIBUTES {
        let values = attributes
            .iter()
            .map(|key| format!("'{key}'"))
            .collect::<Vec<_>>();
        let row = format!("  {field}: [{}],\n", values.join(", "));
        if row.len() <= 101 {
            out.push_str(&row);
        } else {
            out.push_str(&format!(
                "  {field}: [\n{}  ],\n",
                values
                    .iter()
                    .map(|value| format!("    {value},\n"))
                    .collect::<String>()
            ));
        }
    }
    out.push_str(
        "};\n\nexport const TRANSFER_XMP_ELEMENTS: Readonly<Record<string, string>> = {\n",
    );
    for (field, key) in TRANSFER_XMP_ELEMENTS {
        out.push_str(&format!("  {field}: '{key}',\n"));
    }
    out.push_str("};\n");
    out
}

pub fn emit_swift() -> String {
    let mut out = String::from(
        "// Generated by tools/codegen.sh from schema/groups/transfer.rs. DO NOT EDIT.\n\n\
public enum AdjustmentTransferMode: String, Sendable {\n\
\x20 case absolute = \"Absolute\"\n\
\x20 case relative = \"Relative\"\n\
\x20 case assetRelative = \"AssetRelative\"\n\
\x20 case unsupported = \"Unsupported\"\n\
}\n\n\
/// Relative fields also support an explicit camera As Shot correction.\n\
public let adjustmentTransferModes: [String: AdjustmentTransferMode] = [\n",
    );
    for field in fields() {
        let name = transfer_mode(field).expect("transfer decision").name();
        let lower = format!("{}{}", name[..1].to_lowercase(), &name[1..]);
        out.push_str(&format!("  \"{field}\": .{lower},\n"));
    }
    out.push_str("]\n");
    out
}

#[cfg(test)]
mod tests {
    use super::*;
    #[test]
    fn decisions_are_generated_for_both_consumers() {
        for field in fields() {
            let mode = transfer_mode(field).unwrap().name();
            assert!(emit_ts().contains(&format!("{field}: '{mode}'")));
            assert!(emit_swift().contains(&format!("\"{field}\": .")));
        }
        assert!(emit_ts().contains("crop: 'AssetRelative'"));
        assert!(emit_ts().contains("inpaint_removals: 'Unsupported'"));
        assert_eq!(emit_ts(), emit_ts());
        assert_eq!(emit_swift(), emit_swift());
    }
}
