//! Emit the concrete #3311 batch DTO, shared by Swift, Angular, and Bun.
use raw_core::batch_transfer::{
    BATCH_ASSET_STATUSES, BATCH_TRANSFER_DTOS, BATCH_TRANSFER_STATUSES,
};

pub fn emit(swift: bool) -> String {
    emit_contract(swift, false)
}

/// API jobs already have their own progress and per-target status vocabulary.
/// Emit only the shared result shapes that the existing job runner consumes.
pub fn emit_api() -> String {
    emit_contract(false, true)
}

fn emit_contract(swift: bool, api: bool) -> String {
    let mut out = String::from("// THIS FILE IS GENERATED BY tools/codegen.sh. DO NOT EDIT.\n// Source: raw-core/src/batch_transfer.rs (#3311).\n\n");
    for (name, values) in [
        ("BatchTransferStatus", BATCH_TRANSFER_STATUSES),
        ("BatchAssetStatus", BATCH_ASSET_STATUSES),
    ] {
        if api && name == "BatchTransferStatus" {
            continue;
        }
        if swift {
            out.push_str(&format!(
                "public enum {name}: String, Codable, Sendable {{\n  case {}\n}}\n\n",
                values.join(", ")
            ));
        } else {
            out.push_str(&format!(
                "export type {name} = {};\n\n",
                values
                    .iter()
                    .map(|v| format!("'{v}'"))
                    .collect::<Vec<_>>()
                    .join(" | ")
            ));
        }
    }
    for (name, fields) in BATCH_TRANSFER_DTOS {
        if api && *name == "BatchTransferProgress" {
            continue;
        }
        out.push_str(&if swift {
            format!("public struct {name}: Codable, Sendable, Equatable {{\n")
        } else {
            format!("export interface {name} {{\n")
        });
        for (field, kind) in *fields {
            if swift {
                out.push_str(&format!("  public var {field}: {}\n", swift_type(kind)));
            } else {
                out.push_str(&format!("  {field}: {kind};\n"));
            }
        }
        if swift {
            let parameters = fields
                .iter()
                .map(|(f, k)| format!("{f}: {}", swift_type(k)))
                .collect::<Vec<_>>();
            let signature = format!("  public init({}) {{\n", parameters.join(", "));
            if signature.len() > 100 {
                out.push_str(&format!(
                    "  public init(\n    {}\n  ) {{\n",
                    parameters.join(",\n    ")
                ));
            } else {
                out.push_str(&signature);
            }
            for (field, _) in *fields {
                out.push_str(&format!("    self.{field} = {field}\n"));
            }
            out.push_str("  }\n");
        }
        out.push_str("}\n\n");
    }
    out.trim_end().to_owned() + "\n"
}
fn swift_type(kind: &str) -> String {
    match kind {
        "string" => "String".into(),
        "number" => "Int".into(),
        "boolean" => "Bool".into(),
        s if s.ends_with("[]") => format!("[{}]", swift_type(&s[..s.len() - 2])),
        s => s.into(),
    }
}
