//! Capability-registry emitters — Swift, TypeScript, and C# consumers of
//! `raw_core::capability_registry::CAPABILITY_REGISTRY` with the release
//! state computed from the evidence records on disk (ticket #2430).
//!
//! Every consumer carries the same facts: the closed enums (surfaces,
//! adapters, asset classes, render paths, evidence sources, release
//! states), one record per capability, and the build identity the states
//! were computed against. The human/machine release summaries live in
//! `capability_summary.rs`.

use raw_core::capability_registry::{
    classify, AssetClass, Capability, Evidence, EvidenceSource, ExportPath, PreviewPath,
    ReleaseState, StorageAdapter, Surface,
};

use crate::camel_case;

const BANNER: &str = "THIS FILE IS GENERATED BY tools/codegen.sh. DO NOT EDIT.\n\
     Source: src/raw-pipeline/raw-core/src/capability_registry/ (CAPABILITY_REGISTRY)\n\
     and the evidence records under test-fixtures/qualification/ (#2430).\n\
     \n\
     Release state is COMPUTED from harness evidence, never asserted: a\n\
     capability reads `released` only when every declared evidence source\n\
     has a record on the current pipeline + schema version, over the\n\
     current corpus, on an accepted backend, with executed == expected\n\
     cases, zero failures, and zero skips. See docs/capability-registry.md.";

fn banner(prefix: &str) -> String {
    BANNER
        .lines()
        .map(|l| {
            if l.is_empty() {
                format!("{prefix}\n")
            } else {
                format!("{prefix} {l}\n")
            }
        })
        .collect()
}

/// `(enum name, every (id) case)` for each closed enum, in one place so the
/// three targets cannot disagree on membership or order.
fn closed_enums() -> Vec<(&'static str, Vec<&'static str>)> {
    vec![
        ("Surface", Surface::ALL.iter().map(|s| s.id()).collect()),
        (
            "StorageAdapter",
            StorageAdapter::ALL.iter().map(|s| s.id()).collect(),
        ),
        (
            "AssetClass",
            AssetClass::ALL.iter().map(|s| s.id()).collect(),
        ),
        (
            "PreviewPath",
            PreviewPath::ALL.iter().map(|s| s.id()).collect(),
        ),
        (
            "ExportPath",
            ExportPath::ALL.iter().map(|s| s.id()).collect(),
        ),
        (
            "EvidenceSource",
            EvidenceSource::ALL.iter().map(|s| s.id()).collect(),
        ),
        ("ReleaseState", vec!["core", "integrated", "released"]),
    ]
}

/// The per-capability facts every target emits, already stringified.
struct Row {
    id: &'static str,
    title: &'static str,
    owner: &'static str,
    surfaces: Vec<&'static str>,
    storage_adapters: Vec<&'static str>,
    asset_classes: Vec<&'static str>,
    preview_paths: Vec<&'static str>,
    export_paths: Vec<&'static str>,
    fields: Vec<&'static str>,
    integration: Vec<&'static str>,
    qualification: Vec<&'static str>,
    state: ReleaseState,
}

fn rows(registry: &[Capability], evidence: &Evidence) -> Vec<Row> {
    registry
        .iter()
        .map(|c| Row {
            id: c.id,
            title: c.title,
            owner: c.owner,
            surfaces: c.surfaces.iter().map(|s| s.id()).collect(),
            storage_adapters: c.storage_adapters.iter().map(|s| s.id()).collect(),
            asset_classes: c.asset_classes.iter().map(|s| s.id()).collect(),
            preview_paths: c.preview_paths.iter().map(|s| s.id()).collect(),
            export_paths: c.export_paths.iter().map(|s| s.id()).collect(),
            fields: c.owned_fields(),
            integration: c.integration.iter().map(|s| s.id()).collect(),
            qualification: c.qualification.iter().map(|s| s.id()).collect(),
            state: classify(c, evidence).state,
        })
        .collect()
}

fn pascal_case(snake: &str) -> String {
    let camel = camel_case(snake);
    let mut chars = camel.chars();
    match chars.next() {
        Some(first) => first.to_uppercase().chain(chars).collect(),
        None => String::new(),
    }
}

// -------------------------------------------------------------------------
// Swift
// -------------------------------------------------------------------------

pub(crate) fn emit_swift(registry: &[Capability], evidence: &Evidence) -> String {
    let build = evidence.build.expect("evidence carries a build identity");
    let mut s = banner("//");
    s.push_str("\nimport Foundation\n\n");
    for (name, cases) in closed_enums() {
        s.push_str(&format!(
            "public enum Capability{name}: String, CaseIterable, Sendable {{\n"
        ));
        for id in cases {
            s.push_str(&format!("    case {} = \"{}\"\n", camel_case(id), id));
        }
        s.push_str("}\n\n");
    }
    s.push_str("/// One editor capability and its computed release state.\n");
    s.push_str("public struct CapabilityRecord: Sendable {\n");
    s.push_str("    public let id: String\n");
    s.push_str("    public let title: String\n");
    s.push_str("    public let owner: String\n");
    s.push_str("    public let surfaces: [CapabilitySurface]\n");
    s.push_str("    public let storageAdapters: [CapabilityStorageAdapter]\n");
    s.push_str("    public let assetClasses: [CapabilityAssetClass]\n");
    s.push_str("    public let previewPaths: [CapabilityPreviewPath]\n");
    s.push_str("    public let exportPaths: [CapabilityExportPath]\n");
    s.push_str("    public let fields: [String]\n");
    s.push_str("    public let integration: [CapabilityEvidenceSource]\n");
    s.push_str("    public let qualification: [CapabilityEvidenceSource]\n");
    s.push_str("    public let releaseState: CapabilityReleaseState\n");
    s.push_str("}\n\n");
    s.push_str("/// The registry plus the build the states were computed for.\n");
    s.push_str("public enum CapabilityRegistry {\n");
    s.push_str(&format!(
        "    public static let pipelineOutputVersion: UInt32 = {}\n",
        build.pipeline_version
    ));
    s.push_str(&format!(
        "    public static let schemaVersion: UInt32 = {}\n\n",
        build.schema_version
    ));
    s.push_str("    public static let all: [CapabilityRecord] = [\n");
    for row in rows(registry, evidence) {
        s.push_str("        CapabilityRecord(\n");
        s.push_str(&format!("            id: \"{}\",\n", row.id));
        s.push_str(&format!("            title: \"{}\",\n", row.title));
        s.push_str(&format!("            owner: \"{}\",\n", row.owner));
        s.push_str(&swift_cases("surfaces", &row.surfaces));
        s.push_str(&swift_cases("storageAdapters", &row.storage_adapters));
        s.push_str(&swift_cases("assetClasses", &row.asset_classes));
        s.push_str(&swift_cases("previewPaths", &row.preview_paths));
        s.push_str(&swift_cases("exportPaths", &row.export_paths));
        s.push_str(&swift_strings("fields", &row.fields));
        s.push_str(&swift_cases("integration", &row.integration));
        s.push_str(&swift_cases("qualification", &row.qualification));
        s.push_str(&format!(
            "            releaseState: .{}\n",
            camel_case(row.state.id())
        ));
        s.push_str("        ),\n");
    }
    s.push_str("    ]\n");
    s.push_str("}\n");
    s
}

fn swift_cases(key: &str, ids: &[&str]) -> String {
    let members: Vec<String> = ids
        .iter()
        .map(|id| format!(".{}", camel_case(id)))
        .collect();
    swift_array(key, &members)
}

fn swift_strings(key: &str, values: &[&str]) -> String {
    let members: Vec<String> = values.iter().map(|v| format!("\"{v}\"")).collect();
    swift_array(key, &members)
}

/// An array argument at 12-space indent, shaped the way `swift-format`
/// lints it: a literal that fits in 100 columns stays on one line with no
/// trailing comma; a longer one breaks one element per line, each with a
/// trailing comma.
fn swift_array(key: &str, members: &[String]) -> String {
    let compact = format!("            {key}: [{}],", members.join(", "));
    if compact.len() <= 100 {
        return format!("{compact}\n");
    }
    let mut s = format!("            {key}: [\n");
    for m in members {
        s.push_str(&format!("                {m},\n"));
    }
    s.push_str("            ],\n");
    s
}

// -------------------------------------------------------------------------
// TypeScript
// -------------------------------------------------------------------------

pub(crate) fn emit_ts(registry: &[Capability], evidence: &Evidence) -> String {
    let build = evidence.build.expect("evidence carries a build identity");
    let mut s = banner("//");
    s.push('\n');
    for (name, cases) in closed_enums() {
        s.push_str(&ts_union(name, &cases));
        s.push('\n');
    }
    s.push_str("/** One editor capability and its computed release state. */\n");
    s.push_str("export interface CapabilityRecord {\n");
    s.push_str("  readonly id: string;\n");
    s.push_str("  readonly title: string;\n");
    s.push_str("  readonly owner: string;\n");
    s.push_str("  readonly surfaces: readonly CapabilitySurface[];\n");
    s.push_str("  readonly storageAdapters: readonly CapabilityStorageAdapter[];\n");
    s.push_str("  readonly assetClasses: readonly CapabilityAssetClass[];\n");
    s.push_str("  readonly previewPaths: readonly CapabilityPreviewPath[];\n");
    s.push_str("  readonly exportPaths: readonly CapabilityExportPath[];\n");
    s.push_str("  readonly fields: readonly string[];\n");
    s.push_str("  readonly integration: readonly CapabilityEvidenceSource[];\n");
    s.push_str("  readonly qualification: readonly CapabilityEvidenceSource[];\n");
    s.push_str("  readonly releaseState: CapabilityReleaseState;\n");
    s.push_str("}\n\n");
    s.push_str("/** The build the release states were computed for. */\n");
    s.push_str("export const CAPABILITY_REGISTRY_BUILD = {\n");
    s.push_str(&format!(
        "  pipelineOutputVersion: {},\n",
        build.pipeline_version
    ));
    s.push_str(&format!("  schemaVersion: {},\n", build.schema_version));
    s.push_str("} as const;\n\n");
    s.push_str("export const CAPABILITY_REGISTRY: readonly CapabilityRecord[] = [\n");
    for row in rows(registry, evidence) {
        s.push_str("  {\n");
        s.push_str(&format!("    id: '{}',\n", row.id));
        s.push_str(&format!(
            "    title: '{}',\n",
            row.title.replace('\'', "\\'")
        ));
        s.push_str(&format!("    owner: '{}',\n", row.owner));
        s.push_str(&ts_array("surfaces", &row.surfaces));
        s.push_str(&ts_array("storageAdapters", &row.storage_adapters));
        s.push_str(&ts_array("assetClasses", &row.asset_classes));
        s.push_str(&ts_array("previewPaths", &row.preview_paths));
        s.push_str(&ts_array("exportPaths", &row.export_paths));
        s.push_str(&ts_array("fields", &row.fields));
        s.push_str(&ts_array("integration", &row.integration));
        s.push_str(&ts_array("qualification", &row.qualification));
        s.push_str(&format!("    releaseState: '{}',\n", row.state.id()));
        s.push_str("  },\n");
    }
    s.push_str("];\n");
    s
}

/// A string-literal union, formatted the way `prettier --print-width 100`
/// prints it: one line when it fits, otherwise one member per line.
fn ts_union(name: &str, cases: &[&str]) -> String {
    let members: Vec<String> = cases.iter().map(|c| format!("'{c}'")).collect();
    let compact = format!("export type Capability{name} = {};", members.join(" | "));
    if compact.len() <= 100 {
        return format!("{compact}\n");
    }
    let mut s = format!("export type Capability{name} =\n");
    for (i, m) in members.iter().enumerate() {
        let sep = if i == members.len() - 1 { ";" } else { "" };
        s.push_str(&format!("  | {m}{sep}\n"));
    }
    s
}

/// A string array property at 4-space indent, formatted the way `prettier
/// --print-width 100` prints it: one line when it fits, otherwise one
/// element per line (prettier never fills string arrays). Hand-replicated
/// so the emitter stays a pure function — the drift gate confirms the two
/// agree.
fn ts_array(key: &str, values: &[&str]) -> String {
    let quoted: Vec<String> = values.iter().map(|v| format!("'{v}'")).collect();
    let compact = format!("    {key}: [{}],", quoted.join(", "));
    if compact.len() <= 100 {
        return format!("{compact}\n");
    }
    let mut s = format!("    {key}: [\n");
    for q in quoted {
        s.push_str(&format!("      {q},\n"));
    }
    s.push_str("    ],\n");
    s
}

// -------------------------------------------------------------------------
// C#
// -------------------------------------------------------------------------

pub(crate) fn emit_cs(registry: &[Capability], evidence: &Evidence) -> String {
    let build = evidence.build.expect("evidence carries a build identity");
    let mut s = banner("//");
    s.push_str("\nusing System.Collections.Generic;\n\n");
    s.push_str("namespace Maple.WinUI.Generated\n{\n");
    for (name, cases) in closed_enums() {
        let members: Vec<String> = cases.iter().map(|id| pascal_case(id)).collect();
        s.push_str(&format!(
            "    public enum Capability{name} {{ {} }}\n",
            members.join(", ")
        ));
    }
    s.push_str(
        "\n    /// <summary>One editor capability and its computed release state.</summary>\n",
    );
    s.push_str("    public sealed record CapabilityRecord(\n");
    s.push_str("        string Id,\n");
    s.push_str("        string Title,\n");
    s.push_str("        string Owner,\n");
    s.push_str("        IReadOnlyList<CapabilitySurface> Surfaces,\n");
    s.push_str("        IReadOnlyList<CapabilityStorageAdapter> StorageAdapters,\n");
    s.push_str("        IReadOnlyList<CapabilityAssetClass> AssetClasses,\n");
    s.push_str("        IReadOnlyList<CapabilityPreviewPath> PreviewPaths,\n");
    s.push_str("        IReadOnlyList<CapabilityExportPath> ExportPaths,\n");
    s.push_str("        IReadOnlyList<string> Fields,\n");
    s.push_str("        IReadOnlyList<CapabilityEvidenceSource> Integration,\n");
    s.push_str("        IReadOnlyList<CapabilityEvidenceSource> Qualification,\n");
    s.push_str("        CapabilityReleaseState ReleaseState);\n\n");
    s.push_str(
        "    /// <summary>The registry plus the build the states were computed for.</summary>\n",
    );
    s.push_str("    public static class CapabilityRegistry\n    {\n");
    s.push_str(&format!(
        "        public const uint PipelineOutputVersion = {};\n",
        build.pipeline_version
    ));
    s.push_str(&format!(
        "        public const uint SchemaVersion = {};\n\n",
        build.schema_version
    ));
    s.push_str("        public static readonly IReadOnlyList<CapabilityRecord> All = new CapabilityRecord[]\n        {\n");
    for row in rows(registry, evidence) {
        s.push_str("            new(\n");
        s.push_str(&format!("                \"{}\",\n", row.id));
        s.push_str(&format!(
            "                \"{}\",\n",
            row.title.replace('"', "\\\"")
        ));
        s.push_str(&format!("                \"{}\",\n", row.owner));
        s.push_str(&cs_enum_array("CapabilitySurface", &row.surfaces));
        s.push_str(&cs_enum_array(
            "CapabilityStorageAdapter",
            &row.storage_adapters,
        ));
        s.push_str(&cs_enum_array("CapabilityAssetClass", &row.asset_classes));
        s.push_str(&cs_enum_array("CapabilityPreviewPath", &row.preview_paths));
        s.push_str(&cs_enum_array("CapabilityExportPath", &row.export_paths));
        s.push_str(&cs_string_array(&row.fields));
        s.push_str(&cs_enum_array("CapabilityEvidenceSource", &row.integration));
        s.push_str(&cs_enum_array(
            "CapabilityEvidenceSource",
            &row.qualification,
        ));
        s.push_str(&format!(
            "                CapabilityReleaseState.{}),\n",
            pascal_case(row.state.id())
        ));
    }
    s.push_str("        };\n    }\n}\n");
    s
}

fn cs_enum_array(ty: &str, ids: &[&str]) -> String {
    let members: Vec<String> = ids
        .iter()
        .map(|id| format!("{ty}.{}", pascal_case(id)))
        .collect();
    format!("                new {ty}[] {{ {} }},\n", members.join(", "))
}

fn cs_string_array(values: &[&str]) -> String {
    let quoted: Vec<String> = values.iter().map(|v| format!("\"{v}\"")).collect();
    format!(
        "                new string[] {{ {} }},\n",
        quoted.join(", ")
    )
}

#[cfg(test)]
mod tests {
    use super::*;
    use raw_core::capability_registry::{BuildIdentity, CAPABILITY_REGISTRY};

    fn no_evidence() -> Evidence {
        Evidence {
            records: Default::default(),
            build: Some(BuildIdentity {
                pipeline_version: 2,
                schema_version: 5,
            }),
            corpus_hashes: Default::default(),
        }
    }

    #[test]
    fn swift_emits_every_capability_with_a_state() {
        let out = emit_swift(CAPABILITY_REGISTRY, &no_evidence());
        assert_eq!(
            out.matches("CapabilityRecord(\n").count(),
            CAPABILITY_REGISTRY.len()
        );
        assert!(out.contains("public enum CapabilitySurface: String, CaseIterable, Sendable {"));
        assert!(out.contains("    case apiFilesystem = \"api_filesystem\"\n"));
        assert!(out.contains("            surfaces: [.apple, .web, .windows],\n"));
        assert!(out.contains("            fields: [],\n"));
        assert!(out.contains("public static let pipelineOutputVersion: UInt32 = 2\n"));
        // No evidence: nothing can leave Core.
        assert_eq!(
            out.matches("releaseState: .core\n").count(),
            CAPABILITY_REGISTRY.len()
        );
    }

    #[test]
    fn ts_emits_unions_interface_and_registry() {
        let out = emit_ts(CAPABILITY_REGISTRY, &no_evidence());
        assert!(out.contains(
            "export type CapabilityReleaseState = 'core' | 'integrated' | 'released';\n"
        ));
        assert!(out.contains("export type CapabilityStorageAdapter =\n  | 'filesystem'\n"));
        assert!(out.contains("export interface CapabilityRecord {"));
        assert!(out.contains("export const CAPABILITY_REGISTRY_BUILD = {\n  pipelineOutputVersion: 2,\n  schemaVersion: 5,\n} as const;"));
        assert_eq!(out.matches("    id: '").count(), CAPABILITY_REGISTRY.len());
        assert!(out.contains("    surfaces: ['apple', 'web', 'windows'],\n"));
        // Every emitted line respects prettier's 100-column print width.
        assert!(
            out.lines().all(|l| l.len() <= 100),
            "a line exceeds 100 columns"
        );
    }

    #[test]
    fn cs_emits_enums_record_and_registry() {
        let out = emit_cs(CAPABILITY_REGISTRY, &no_evidence());
        assert!(out.contains("namespace Maple.WinUI.Generated"));
        assert!(out.contains("public enum CapabilitySurface { Apple, Web, Windows }"));
        assert!(out.contains("public sealed record CapabilityRecord("));
        assert!(out.contains("public const uint PipelineOutputVersion = 2;"));
        assert_eq!(
            out.matches("            new(\n").count(),
            CAPABILITY_REGISTRY.len()
        );
        assert!(
            out.contains("new CapabilityStorageAdapter[] { CapabilityStorageAdapter.ApiFilesystem")
        );
    }

    #[test]
    fn determinism_double_emit_is_identical() {
        let e = no_evidence();
        assert_eq!(
            emit_swift(CAPABILITY_REGISTRY, &e),
            emit_swift(CAPABILITY_REGISTRY, &e)
        );
        assert_eq!(
            emit_ts(CAPABILITY_REGISTRY, &e),
            emit_ts(CAPABILITY_REGISTRY, &e)
        );
        assert_eq!(
            emit_cs(CAPABILITY_REGISTRY, &e),
            emit_cs(CAPABILITY_REGISTRY, &e)
        );
    }
}
