//! Release summaries for the capability registry (#2430): the
//! human-readable `docs/capability-registry.md` and the machine-readable
//! `docs/capability-registry.json`. Both are derived from the same
//! `classify` pass the Swift / TS / C# consumers use, so the four never
//! disagree about a capability's state or why it holds it.
//!
//! Markdown is emitted as headings + lists only (no tables) and JSON is
//! printed by a small prettier-shaped printer, so both files are stable
//! under the repo's `prettier --check` gate without a formatting pass.

use raw_core::capability_registry::{
    classify, Capability, Evidence, EvidenceSource, Finding, ReleaseState,
};

// -------------------------------------------------------------------------
// Markdown
// -------------------------------------------------------------------------

pub(crate) fn emit_md(registry: &[Capability], evidence: &Evidence) -> String {
    let build = evidence.build.expect("evidence carries a build identity");
    let classified: Vec<_> = registry
        .iter()
        .map(|c| (c, classify(c, evidence)))
        .collect();
    let count = |state: ReleaseState| classified.iter().filter(|(_, c)| c.state == state).count();

    let mut s = String::new();
    s.push_str("# Capability registry\n\n");
    s.push_str("<!-- THIS FILE IS GENERATED BY tools/codegen.sh. DO NOT EDIT. -->\n\n");
    s.push_str(
        "Generated from `src/raw-pipeline/raw-core/src/capability_registry/` (the registry, reviewed Rust) and the harness evidence records under `test-fixtures/qualification/` by `codegen --schema capability-registry --target md` (ticket #2430). The `codegen-drift` CI job regenerates this file on every push; a hand edit fails that gate. Release state is computed, never asserted — see `docs/testing.md` § \"Capability registry and qualification evidence\" for the rule and the operator workflow.\n\n",
    );
    s.push_str("## Build\n\n");
    s.push_str(&format!(
        "- Pipeline output version: {}\n",
        build.pipeline_version
    ));
    s.push_str(&format!(
        "- Sidecar schema version: {}\n",
        build.schema_version
    ));
    s.push_str(&format!(
        "- Capabilities: {} ({} released, {} integrated, {} core)\n\n",
        classified.len(),
        count(ReleaseState::Released),
        count(ReleaseState::Integrated),
        count(ReleaseState::Core)
    ));

    s.push_str("## Capabilities\n\n");
    for (cap, c) in &classified {
        s.push_str(&format!("### `{}` — {}\n\n", cap.id, cap.title));
        s.push_str(&format!("- State: **{}**\n", c.state.id()));
        s.push_str(&format!("- Owner: `{}`\n", cap.owner));
        s.push_str(&md_list("Surfaces", cap.surfaces.iter().map(|s| s.id())));
        s.push_str(&md_list(
            "Storage adapters",
            cap.storage_adapters.iter().map(|s| s.id()),
        ));
        s.push_str(&md_list(
            "Asset classes",
            cap.asset_classes.iter().map(|s| s.id()),
        ));
        s.push_str(&md_list(
            "Preview paths",
            cap.preview_paths.iter().map(|s| s.id()),
        ));
        s.push_str(&md_list(
            "Export paths",
            cap.export_paths.iter().map(|s| s.id()),
        ));
        s.push_str(&md_list("Fields", cap.owned_fields().into_iter()));
        s.push_str(&md_findings("Integration evidence", &c.integration));
        s.push_str(&md_findings("Qualification evidence", &c.qualification));
        s.push('\n');
    }

    s.push_str("## Evidence sources\n\n");
    for source in EvidenceSource::ALL {
        s.push_str(&format!("### `{}`\n\n", source.id()));
        s.push_str(&format!("- {}\n", source.description()));
        s.push_str(&md_list("Covers", source.covers().iter().map(|s| s.id())));
        s.push_str(&md_list(
            "Accepted backends",
            source.accepted_backends().iter().copied(),
        ));
        s.push_str(&format!("- Expected cases: {}\n", source.expected_cases()));
        s.push_str(&md_list("Corpus", source.corpus().iter().copied()));
        let status = raw_core::capability_registry::judge(*source, evidence);
        match evidence.records.get(source) {
            Some(r) => s.push_str(&format!(
                "- Record: {} — {} of {} executed, {} failed, {} skipped, on `{}`, pipeline v{}, schema v{}, commit `{}`, recorded {}\n",
                status.describe(),
                r.executed_cases,
                r.expected_cases,
                r.failed_cases,
                r.skipped_cases,
                r.backend,
                r.pipeline_version,
                r.schema_version,
                if r.git_sha.is_empty() { "unknown" } else { &r.git_sha },
                if r.recorded_at.is_empty() { "at an unknown time" } else { &r.recorded_at },
            )),
            None => s.push_str(&format!("- Record: {}\n", status.describe())),
        }
        s.push('\n');
    }
    s.trim_end().to_owned() + "\n"
}

fn md_list<'a>(label: &str, items: impl Iterator<Item = &'a str>) -> String {
    let quoted: Vec<String> = items.map(|i| format!("`{i}`")).collect();
    if quoted.is_empty() {
        format!("- {label}: none\n")
    } else {
        format!("- {label}: {}\n", quoted.join(", "))
    }
}

fn md_findings(label: &str, findings: &[Finding]) -> String {
    if findings.is_empty() {
        return format!("- {label}: none declared\n");
    }
    let mut s = format!("- {label}:\n");
    for f in findings {
        s.push_str(&format!(
            "  - `{}` — {}\n",
            f.source.id(),
            f.status.describe()
        ));
    }
    s
}

// -------------------------------------------------------------------------
// JSON
// -------------------------------------------------------------------------

/// A tiny ordered JSON tree — `serde_json::Value` sorts object keys, and
/// the summary wants declaration order.
enum J {
    Str(String),
    Num(u64),
    Null,
    Arr(Vec<J>),
    Obj(Vec<(&'static str, J)>),
}

fn strs<'a>(items: impl Iterator<Item = &'a str>) -> J {
    J::Arr(items.map(|s| J::Str(s.to_owned())).collect())
}

fn finding_json(f: &Finding) -> J {
    J::Obj(vec![
        ("source", J::Str(f.source.id().to_owned())),
        ("status", J::Str(f.status.id().to_owned())),
        ("detail", J::Str(f.status.describe())),
    ])
}

pub(crate) fn emit_json(registry: &[Capability], evidence: &Evidence) -> String {
    let build = evidence.build.expect("evidence carries a build identity");
    let capabilities = registry
        .iter()
        .map(|cap| {
            let c = classify(cap, evidence);
            J::Obj(vec![
                ("id", J::Str(cap.id.to_owned())),
                ("title", J::Str(cap.title.to_owned())),
                ("owner", J::Str(cap.owner.to_owned())),
                ("state", J::Str(c.state.id().to_owned())),
                ("surfaces", strs(cap.surfaces.iter().map(|s| s.id()))),
                (
                    "storage_adapters",
                    strs(cap.storage_adapters.iter().map(|s| s.id())),
                ),
                (
                    "asset_classes",
                    strs(cap.asset_classes.iter().map(|s| s.id())),
                ),
                (
                    "preview_paths",
                    strs(cap.preview_paths.iter().map(|s| s.id())),
                ),
                (
                    "export_paths",
                    strs(cap.export_paths.iter().map(|s| s.id())),
                ),
                ("fields", strs(cap.owned_fields().into_iter())),
                (
                    "integration",
                    J::Arr(c.integration.iter().map(finding_json).collect()),
                ),
                (
                    "qualification",
                    J::Arr(c.qualification.iter().map(finding_json).collect()),
                ),
            ])
        })
        .collect();
    let sources = EvidenceSource::ALL
        .iter()
        .map(|source| {
            let record = match evidence.records.get(source) {
                Some(r) => J::Obj(vec![
                    ("backend", J::Str(r.backend.clone())),
                    ("pipeline_version", J::Num(r.pipeline_version.into())),
                    ("schema_version", J::Num(r.schema_version.into())),
                    ("corpus_hash", J::Str(r.corpus_hash.clone())),
                    ("expected_cases", J::Num(r.expected_cases.into())),
                    ("executed_cases", J::Num(r.executed_cases.into())),
                    ("failed_cases", J::Num(r.failed_cases.into())),
                    ("skipped_cases", J::Num(r.skipped_cases.into())),
                    ("git_sha", J::Str(r.git_sha.clone())),
                    ("recorded_at", J::Str(r.recorded_at.clone())),
                    ("command", J::Str(r.command.clone())),
                ]),
                None => J::Null,
            };
            let status = raw_core::capability_registry::judge(*source, evidence);
            J::Obj(vec![
                ("source", J::Str(source.id().to_owned())),
                ("description", J::Str(source.description().to_owned())),
                ("covers", strs(source.covers().iter().map(|s| s.id()))),
                (
                    "accepted_backends",
                    strs(source.accepted_backends().iter().copied()),
                ),
                ("expected_cases", J::Num(source.expected_cases().into())),
                ("corpus", strs(source.corpus().iter().copied())),
                (
                    "corpus_hash",
                    evidence
                        .corpus_hashes
                        .get(source)
                        .map_or(J::Null, |h| J::Str(h.clone())),
                ),
                ("status", J::Str(status.id().to_owned())),
                ("record", record),
            ])
        })
        .collect();
    let root = J::Obj(vec![
        (
            "generator",
            J::Str("tools/codegen.sh (codegen --schema capability-registry --target json)".into()),
        ),
        (
            "build",
            J::Obj(vec![
                (
                    "pipeline_output_version",
                    J::Num(build.pipeline_version.into()),
                ),
                ("schema_version", J::Num(build.schema_version.into())),
            ]),
        ),
        ("capabilities", J::Arr(capabilities)),
        ("evidence_sources", J::Arr(sources)),
    ]);
    let mut out = String::new();
    print_json(&root, 0, 0, &mut out);
    out.push('\n');
    out
}

fn json_string(s: &str) -> String {
    serde_json::to_string(s).expect("string serializes")
}

/// Prettier-shaped JSON: objects always expanded, arrays on one line when
/// the whole line — `used` columns already on it (indent + key) plus the
/// array and a trailing comma — fits in 100 columns, otherwise one element
/// per line.
fn print_json(v: &J, indent: usize, used: usize, out: &mut String) {
    let pad = " ".repeat(indent);
    let inner = " ".repeat(indent + 2);
    match v {
        J::Str(s) => out.push_str(&json_string(s)),
        J::Num(n) => out.push_str(&n.to_string()),
        J::Null => out.push_str("null"),
        J::Arr(items) if items.is_empty() => out.push_str("[]"),
        J::Arr(items) => {
            let flat: Option<Vec<String>> = items
                .iter()
                .map(|i| match i {
                    J::Str(s) => Some(json_string(s)),
                    J::Num(n) => Some(n.to_string()),
                    J::Null => Some("null".into()),
                    _ => None,
                })
                .collect();
            if let Some(flat) = flat {
                let line = format!("[{}]", flat.join(", "));
                if used + line.len() + 1 <= 100 {
                    out.push_str(&line);
                    return;
                }
            }
            out.push_str("[\n");
            for (i, item) in items.iter().enumerate() {
                out.push_str(&inner);
                print_json(item, indent + 2, indent + 2, out);
                out.push_str(if i + 1 == items.len() { "\n" } else { ",\n" });
            }
            out.push_str(&pad);
            out.push(']');
        }
        J::Obj(entries) if entries.is_empty() => out.push_str("{}"),
        J::Obj(entries) => {
            out.push_str("{\n");
            for (i, (k, val)) in entries.iter().enumerate() {
                let key = json_string(k);
                out.push_str(&inner);
                out.push_str(&key);
                out.push_str(": ");
                print_json(val, indent + 2, indent + 2 + key.len() + 2, out);
                out.push_str(if i + 1 == entries.len() { "\n" } else { ",\n" });
            }
            out.push_str(&pad);
            out.push('}');
        }
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    use raw_core::capability_registry::{BuildIdentity, CAPABILITY_REGISTRY};

    fn no_evidence() -> Evidence {
        Evidence {
            records: Default::default(),
            build: Some(BuildIdentity {
                pipeline_version: 2,
                schema_version: 5,
            }),
            corpus_hashes: Default::default(),
        }
    }

    #[test]
    fn md_lists_every_capability_and_source() {
        let out = emit_md(CAPABILITY_REGISTRY, &no_evidence());
        assert!(out.starts_with("# Capability registry\n\n<!-- THIS FILE IS GENERATED"));
        for cap in CAPABILITY_REGISTRY {
            assert!(out.contains(&format!("### `{}` — {}\n", cap.id, cap.title)));
        }
        for source in EvidenceSource::ALL {
            assert!(out.contains(&format!("### `{}`\n", source.id())));
        }
        assert!(out.contains("- State: **core**\n"));
        assert!(out.contains("- Record: no record\n"));
        assert!(
            !out.contains('|'),
            "tables are not prettier-stable; lists only"
        );
    }

    #[test]
    fn json_is_valid_and_carries_build_and_states() {
        let out = emit_json(CAPABILITY_REGISTRY, &no_evidence());
        let v: serde_json::Value = serde_json::from_str(&out).expect("valid JSON");
        assert_eq!(v["build"]["pipeline_output_version"], 2);
        assert_eq!(
            v["capabilities"].as_array().unwrap().len(),
            CAPABILITY_REGISTRY.len()
        );
        assert_eq!(v["capabilities"][0]["state"], "core");
        assert_eq!(v["evidence_sources"][0]["status"], "missing");
        assert!(v["evidence_sources"][0]["record"].is_null());
        // Prettier collapses a scalar array onto one line only when it fits
        // in the print width, and never breaks a string — so every line is
        // either within 100 columns or a single (unbreakable) string value.
        assert!(
            out.lines().all(|l| l.len() <= 100
                || l.trim_start().starts_with('"') && l.matches('"').count() <= 4),
            "a breakable line exceeds 100 columns"
        );
        assert!(out.contains("\"surfaces\": [\"apple\", \"web\", \"windows\"],\n"));
    }

    #[test]
    fn determinism_double_emit_is_identical() {
        let e = no_evidence();
        assert_eq!(
            emit_md(CAPABILITY_REGISTRY, &e),
            emit_md(CAPABILITY_REGISTRY, &e)
        );
        assert_eq!(
            emit_json(CAPABILITY_REGISTRY, &e),
            emit_json(CAPABILITY_REGISTRY, &e)
        );
    }
}
