//! Emit the culling vocabulary without moving platform presentation or parsing policy.
use raw_core::color_labels::COLOR_LABELS;

const HEADER: &str = "// Generated by codegen --schema color-labels. Do not edit.\n\n";

pub fn emit_swift() -> String {
    let mut out = String::from(HEADER);
    out.push_str("public enum ColorLabel: String, Codable, Sendable, Hashable, CaseIterable {\n");
    for label in COLOR_LABELS {
        out.push_str(&format!("  case {label}\n"));
    }
    out.push_str("}\n");
    out
}

pub fn emit_ts() -> String {
    let values = COLOR_LABELS.map(|label| format!("'{label}'")).join(", ");
    format!("{HEADER}export const COLOR_LABEL_VALUES = [{values}] as const;\n")
}

pub fn emit_cs() -> String {
    let values = COLOR_LABELS.map(|label| format!("\"{label}\"")).join(", ");
    format!(
        "{HEADER}namespace Maple.WinUI.Generated;\n\npublic static class ColorLabelVocabulary\n{{\n    public static readonly System.Collections.Generic.IReadOnlyList<string> Values =\n        new[] {{ {values} }};\n}}\n"
    )
}
