//! WGSL color-matrix emitter (epic #925 P2 / #990).
//!
//! Single-sources the color matrices the GPU scene-linear kernels bake in,
//! emitting them as WGSL `const` declarations from the *same* `raw-core`
//! constants the CPU pipeline uses. The first consumer is the Oklab vibrance
//! kernel (`raw-gpu/src/vibrance.wgsl`), which needs the forward Rec.2020→Oklab
//! matrices and their inverses to round-trip a pixel through Oklab on the GPU.
//!
//! ## Why this exists
//!
//! The Oklab matrices live as `const` in `raw-core` (`color::oklab`,
//! `color::matrices`). A hand-typed WGSL copy would silently drift the moment
//! anyone retunes a matrix. This emitter formats the *live* Rust constants, and
//! the generated file rides the existing `codegen-drift` CI gate
//! (`tools/codegen.sh` + `git diff --exit-code`) so a drift fails the build.
//!
//! ## Matrix convention (load-bearing — every GPU matrix stage copies it)
//!
//! `raw-core::math::Matrix3` is **row-major**; `Matrix3::mul_vec` computes
//! `out[i] = dot(row_i, v)`. WGSL's `mat3x3<f32>` is **column-major**, so a
//! `mat3x3` built from these rows and multiplied `M * v` would silently
//! transpose the matrix and break parity. To mirror `mul_vec` exactly we emit
//! each matrix as **three `const` row `vec3<f32>`s** named `<NAME>_R0/_R1/_R2`,
//! and the kernels apply them with explicit dot products:
//!
//! ```wgsl
//! fn mul_<name>(v: vec3<f32>) -> vec3<f32> {
//!     return vec3<f32>(dot(NAME_R0, v), dot(NAME_R1, v), dot(NAME_R2, v));
//! }
//! ```
//!
//! ## Inverses
//!
//! The reverse Oklab direction needs `M⁻¹`. We compute the inverse here via the
//! same `Matrix3::inverse()` the runtime `OnceLock` cache in `color::oklab`
//! uses — `oklab.rs`'s `cached_inverses_match_matrix3_inverse_bit_exact` test
//! pins that cache to `Matrix3::inverse()`, so emitting `inverse()` of the
//! `pub const` source is bit-identical to what the CPU pipeline runs. The chain
//! is therefore single-source end to end: one Rust constant → CPU pipeline,
//! WGSL forward const, and WGSL inverse const.

use raw_core::color::matrices::{M_REC2020_TO_P3, M_REC2020_TO_SRGB, M_SRGB_TO_P3};
use raw_core::color::oklab::{M1_SRGB_TO_LMS, M2_LMS_TO_LAB};
use raw_core::math::Matrix3;

const BANNER: &str = "\
// THIS FILE IS GENERATED BY tools/codegen.sh. DO NOT EDIT.\n\
// Source: src/raw-pipeline/raw-core/src/color/{matrices,oklab}.rs\n\
//   (M_REC2020_TO_SRGB, M_REC2020_TO_P3, M_SRGB_TO_P3, M1_SRGB_TO_LMS, M2_LMS_TO_LAB + Matrix3::inverse()).\n\
// Emitter: src/raw-pipeline/codegen/src/color_matrices.rs (epic #925 P2 / #990 / #1337).\n";

/// Format an `f32` as a WGSL float literal that round-trips and always carries
/// an `f` suffix (WGSL infers `f32` from the suffix; a bare `0.5` is an
/// abstract-float that still concretises to f32 here, but the explicit suffix
/// documents intent and matches how naga prints constants). `{:?}` picks the
/// shortest round-tripping decimal — stable across Rust versions for these
/// literals, identical to the adjustment-schema emitter's `f()`.
fn wgsl_f(v: f32) -> String {
    let s = format!("{v:?}");
    let with_point = if s.contains('.') || s.contains('e') || s.contains('E') {
        s
    } else {
        format!("{s}.0")
    };
    format!("{with_point}f")
}

/// Emit one matrix as three `const` row `vec3<f32>`s plus a `mul_<name>` helper.
/// `name` is the UPPER_SNAKE WGSL identifier stem; `fn_name` is the snake_case
/// helper name.
fn emit_matrix(out: &mut String, name: &str, fn_name: &str, doc: &str, m: &Matrix3) {
    let r = &m.0;
    out.push_str(&format!("// {doc}\n"));
    for (i, row) in r.iter().enumerate() {
        out.push_str(&format!(
            "const {name}_R{i}: vec3<f32> = vec3<f32>({}, {}, {});\n",
            wgsl_f(row[0]),
            wgsl_f(row[1]),
            wgsl_f(row[2]),
        ));
    }
    out.push_str(&format!(
        "fn {fn_name}(v: vec3<f32>) -> vec3<f32> {{\n    \
         return vec3<f32>(dot({name}_R0, v), dot({name}_R1, v), dot({name}_R2, v));\n}}\n\n"
    ));
}

/// The full WGSL color-matrix module: forward Oklab matrices + their inverses,
/// each as row-`vec3` consts with a `mul_*` dot-product helper.
///
/// Naming mirrors the Rust functions in `color::oklab` so a stage author can
/// map one-to-one:
///   - `mul_rec2020_to_srgb` / `mul_srgb_to_rec2020`
///   - `mul_srgb_to_lms`     / `mul_lms_to_srgb`
///   - `mul_lms_to_lab`      / `mul_lab_to_lms`
pub fn emit_wgsl() -> String {
    let m_srgb_to_rec2020 = M_REC2020_TO_SRGB
        .inverse()
        .expect("M_REC2020_TO_SRGB is invertible");
    let m1_inv = M1_SRGB_TO_LMS.inverse().expect("M1 is invertible");
    let m2_inv = M2_LMS_TO_LAB.inverse().expect("M2 is invertible");

    let mut out = String::new();
    out.push_str(BANNER);
    out.push('\n');

    // Forward direction: Rec.2020 → sRGB → LMS → Lab.
    emit_matrix(
        &mut out,
        "M_REC2020_TO_SRGB",
        "mul_rec2020_to_srgb",
        "Linear Rec.2020 -> linear sRGB (ITU-R BT.2020 -> IEC 61966-2-1).",
        &M_REC2020_TO_SRGB,
    );
    // Rec.2020 → Display P3 (SMPTE RP 431-2, D65 white point) — ticket #1337.
    // The OETF is identical to sRGB (IEC 61966-2-1 / 2.4-gamma); only the
    // primaries matrix differs. The codegen emitter exports this so the WGSL
    // display_encode.wgsl kernel can be updated from the canonical source
    // (codegen-drift CI gate guards against manual drift).
    emit_matrix(
        &mut out,
        "M_REC2020_TO_P3",
        "mul_rec2020_to_p3",
        "Linear Rec.2020 -> linear Display P3 (SMPTE RP 431-2, D65 white point).",
        &M_REC2020_TO_P3,
    );
    // linear sRGB → Display P3 — used by display_encode.wgsl (ticket #1337)
    // for the corrected P3 path: compress in sRGB (where Oklab is defined),
    // then rotate primaries to P3 with this matrix. Single-sourced from
    // raw-core/src/color/matrices.rs::M_SRGB_TO_P3.
    emit_matrix(
        &mut out,
        "M_SRGB_TO_P3",
        "mul_srgb_to_p3",
        "Linear sRGB -> linear Display P3 (SMPTE RP 431-2, D65 white point).",
        &M_SRGB_TO_P3,
    );
    emit_matrix(
        &mut out,
        "M1_SRGB_TO_LMS",
        "mul_srgb_to_lms",
        "Ottosson M1: linear sRGB -> LMS.",
        &M1_SRGB_TO_LMS,
    );
    emit_matrix(
        &mut out,
        "M2_LMS_TO_LAB",
        "mul_lms_to_lab",
        "Ottosson M2: cube-rooted LMS -> Oklab.",
        &M2_LMS_TO_LAB,
    );

    // Inverse direction: Lab -> LMS -> sRGB -> Rec.2020. Computed via
    // Matrix3::inverse() — bit-identical to the runtime OnceLock cache (pinned
    // by oklab.rs::cached_inverses_match_matrix3_inverse_bit_exact).
    emit_matrix(
        &mut out,
        "M2_LAB_TO_LMS",
        "mul_lab_to_lms",
        "Inverse of M2: Oklab -> cube-rooted LMS.",
        &m2_inv,
    );
    emit_matrix(
        &mut out,
        "M1_LMS_TO_SRGB",
        "mul_lms_to_srgb",
        "Inverse of M1: LMS -> linear sRGB.",
        &m1_inv,
    );
    emit_matrix(
        &mut out,
        "M_SRGB_TO_REC2020",
        "mul_srgb_to_rec2020",
        "Inverse of M_REC2020_TO_SRGB: linear sRGB -> linear Rec.2020.",
        &m_srgb_to_rec2020,
    );

    out
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn emits_banner_and_all_eight_matrices() {
        let s = emit_wgsl();
        assert!(s.contains("DO NOT EDIT"));
        // Three forward + three inverse + two P3 helpers (rec2020→p3, srgb→p3).
        for f in [
            "fn mul_rec2020_to_srgb",
            "fn mul_rec2020_to_p3",
            "fn mul_srgb_to_p3",
            "fn mul_srgb_to_lms",
            "fn mul_lms_to_lab",
            "fn mul_lab_to_lms",
            "fn mul_lms_to_srgb",
            "fn mul_srgb_to_rec2020",
        ] {
            assert!(s.contains(f), "missing helper {f}");
        }
        // Each matrix emits exactly three row consts → 24 total (8 matrices).
        assert_eq!(s.matches("_R0: vec3<f32>").count(), 8);
        assert_eq!(s.matches("_R1: vec3<f32>").count(), 8);
        assert_eq!(s.matches("_R2: vec3<f32>").count(), 8);
    }

    #[test]
    fn float_literals_carry_f_suffix_and_round_trip() {
        assert_eq!(wgsl_f(0.5), "0.5f");
        assert_eq!(wgsl_f(1.0), "1.0f");
        assert_eq!(wgsl_f(-0.0182), "-0.0182f");
        // A forward-matrix entry appears verbatim.
        let s = emit_wgsl();
        assert!(
            s.contains("1.6605f"),
            "M_REC2020_TO_SRGB[0][0] literal missing"
        );
    }

    #[test]
    fn determinism_double_emit_is_identical() {
        assert_eq!(emit_wgsl(), emit_wgsl());
    }

    /// The emitted row consts must equal `Matrix3::mul_vec` semantics: the
    /// first emitted row of M_REC2020_TO_SRGB is its first Rust row. This pins
    /// the row-major convention the kernels rely on — if someone "helpfully"
    /// switches to a column-major `mat3x3`, this catches the transpose.
    #[test]
    fn first_forward_row_matches_rust_row_major() {
        let s = emit_wgsl();
        let r0 = &M_REC2020_TO_SRGB.0[0];
        let expected = format!(
            "const M_REC2020_TO_SRGB_R0: vec3<f32> = vec3<f32>({}, {}, {});",
            wgsl_f(r0[0]),
            wgsl_f(r0[1]),
            wgsl_f(r0[2]),
        );
        assert!(
            s.contains(&expected),
            "row-major row 0 mismatch:\n{expected}"
        );
    }
}
