//! Export recipe bindings. Field declarations and capabilities come from raw-core.
use raw_core::export_recipe::{
    ExportRecipe, WireKind, ENCODERS, METADATA_POLICIES, OUTPUT_PROFILES, RECIPE_FIELDS,
    RENDERING_INTENTS,
};
const HEADER: &str = "// Generated by codegen --schema export-recipe. Do not edit.\n";

pub fn emit_ts() -> String {
    let mut out = format!("{HEADER}export interface ExportRecipe {{\n");
    for f in RECIPE_FIELDS {
        let ty = match f.kind {
            WireKind::Text => "string",
            WireKind::Number => "number",
            WireKind::OptionalText => "string | null",
            WireKind::OptionalNumber => "number | null",
        };
        out.push_str(&format!("  readonly {}: {};\n", f.name, ty));
    }
    out.push_str("}\n\nconst EXPORT_RECIPE_FIELDS: Record<keyof ExportRecipe, string> = {\n");
    for f in RECIPE_FIELDS {
        let ty = match f.kind {
            WireKind::Text => "string",
            WireKind::Number => "number",
            WireKind::OptionalText => "string?",
            WireKind::OptionalNumber => "number?",
        };
        out.push_str(&format!("  {}: '{}',\n", f.name, ty));
    }
    out.push_str("};\n\nexport const EXPORT_ENCODERS = [\n");
    for (format, depth, ext) in ENCODERS {
        out.push_str(&format!(
            "  {{ format: '{format}', bitDepth: {depth}, extension: '{ext}' }},\n"
        ));
    }
    out.push_str("] as const;\n");
    for (name, values) in [
        ("EXPORT_OUTPUT_PROFILES", OUTPUT_PROFILES),
        ("EXPORT_RENDERING_INTENTS", RENDERING_INTENTS),
        ("EXPORT_METADATA_POLICIES", METADATA_POLICIES),
    ] {
        let strings: Vec<_> = values.iter().map(|v| format!("'{v}'")).collect();
        out.push_str(&format!(
            "const {name}: readonly string[] = [{}];\n",
            strings.join(", ")
        ));
    }
    // The drift gate compares the raw emitter output. Preserve serde's JSON
    // escaping here instead of trying to duplicate Prettier's quote selection.
    out.push_str("\n// Preserve the generated JSON string literals.\n// prettier-ignore\nexport const DEFAULT_EXPORT_RECIPE: ExportRecipe = {\n");
    append_defaults(&mut out, &ExportRecipe::default());
    out.push_str("};\n");
    out.push_str(&include_str!("export_recipe_validation.ts").replace("\r\n", "\n"));
    out
}

fn append_defaults(out: &mut String, recipe: &ExportRecipe) {
    let defaults = serde_json::to_value(recipe).expect("recipe defaults");
    for f in RECIPE_FIELDS {
        out.push_str(&format!("  {}: {},\n", f.name, defaults[f.name]));
    }
}

pub fn emit_swift() -> String {
    let mut out = format!("{HEADER}import Foundation\n\npublic struct ExportRecipe: Codable, Equatable, Sendable {{\n");
    for f in RECIPE_FIELDS {
        let ty = match f.kind {
            WireKind::Text => "String",
            WireKind::Number => "UInt32",
            WireKind::OptionalText => "String?",
            WireKind::OptionalNumber => "UInt32?",
        };
        out.push_str(&format!("    public var {}: {}\n", f.name, ty));
    }
    // Synthesized encodeIfPresent would DROP explicit null fields, so serialize each field.
    out.push_str("\n    enum CodingKeys: String, CodingKey, CaseIterable {\n");
    for f in RECIPE_FIELDS {
        out.push_str(&format!("        case {}\n", f.name));
    }
    out.push_str("    }\n\n    private struct AnyKey: CodingKey {\n        let stringValue: String\n        var intValue: Int? { nil }\n        init?(stringValue: String) { self.stringValue = stringValue }\n        init?(intValue: Int) { return nil }\n    }\n\n    public init(from decoder: Decoder) throws {\n        let all = try decoder.container(keyedBy: AnyKey.self)\n        guard Set(all.allKeys.map(\\.stringValue)) == Set(CodingKeys.allCases.map(\\.rawValue)) else {\n            throw DecodingError.dataCorrupted(.init(codingPath: decoder.codingPath, debugDescription: \"Recipe has missing or unknown fields\"))\n        }\n        let values = try decoder.container(keyedBy: CodingKeys.self)\n");
    for f in RECIPE_FIELDS {
        let ty = match f.kind {
            WireKind::Text => "String",
            WireKind::Number => "UInt32",
            WireKind::OptionalText => "String?",
            WireKind::OptionalNumber => "UInt32?",
        };
        out.push_str(&format!(
            "        {} = try values.decode({}.self, forKey: .{})\n",
            f.name, ty, f.name
        ));
    }
    out.push_str("        guard schemaVersion == 1 else {\n            throw DecodingError.dataCorrupted(.init(codingPath: decoder.codingPath, debugDescription: \"Unsupported recipe schemaVersion\"))\n        }\n    }\n\n    public func encode(to encoder: Encoder) throws {\n        var values = encoder.container(keyedBy: CodingKeys.self)\n");
    for f in RECIPE_FIELDS {
        out.push_str(&format!(
            "        try values.encode({}, forKey: .{})\n",
            f.name, f.name
        ));
    }
    out.push_str("    }\n}\n");
    out
}

pub fn emit_cs() -> String {
    let mut out = format!("{HEADER}#nullable enable\nusing System.Text.Json.Serialization;\n\nnamespace Maple.WinUI.Generated;\n\n[JsonUnmappedMemberHandling(JsonUnmappedMemberHandling.Disallow)]\npublic sealed record ExportRecipe\n{{\n");
    for f in RECIPE_FIELDS {
        let ty = match f.kind {
            WireKind::Text => "string",
            WireKind::Number => "uint",
            WireKind::OptionalText => "string?",
            WireKind::OptionalNumber => "uint?",
        };
        let name = format!("{}{}", f.name[..1].to_uppercase(), &f.name[1..]);
        out.push_str(&format!("    [JsonPropertyName(\"{}\")]\n    [JsonIgnore(Condition = JsonIgnoreCondition.Never)]\n    public required {} {} {{ get; init; }}\n", f.name, ty, name));
    }
    out.push_str("}\n");
    out
}

#[cfg(test)]
mod tests {
    use super::*;
    #[test]
    fn defaults_preserve_json_string_escaping_in_typescript_literals() {
        let recipe = ExportRecipe {
            name: "Photographer's \"proof\"\\folder\nnext line".into(),
            ..Default::default()
        };
        let mut output = String::new();
        append_defaults(&mut output, &recipe);
        let literal = output
            .lines()
            .find_map(|line| line.strip_prefix("  name: "))
            .unwrap()
            .strip_suffix(',')
            .unwrap();
        assert_eq!(
            serde_json::from_str::<String>(literal).unwrap(),
            recipe.name
        );
    }

    #[test]
    fn every_surface_contains_all_recipe_fields() {
        for f in RECIPE_FIELDS {
            assert!(emit_ts().contains(f.name));
            assert!(emit_swift().contains(f.name));
            assert!(emit_cs().contains(f.name));
        }
        assert!(emit_swift().contains("values.encode(watermark"));
        assert!(emit_cs().contains("JsonIgnoreCondition.Never"));
    }
}
