//! Portable filesystem names share raw-core's reserved-device vocabulary.
use crate::Target;
use raw_core::filename::{
    PAIRED_SIDECAR_SUFFIX_PATTERN, RESERVED_WINDOWS_NAMES, TRASH_ORIGINAL_PATH_SUFFIX,
    TRASH_RESTORE_COLLISION_SUFFIX,
};

pub fn emit(target: Target) -> String {
    let mut out = String::from("// Generated by codegen --schema filename. Do not edit.\n\n");
    if matches!(target, Target::Swift) {
        out.push_str(&format!(
            "public enum FilenameVocabulary {{\n  public static let originalPathMarkerSuffix = {TRASH_ORIGINAL_PATH_SUFFIX:?}\n  public static let restoreCollisionSuffix = {TRASH_RESTORE_COLLISION_SUFFIX:?}\n  public static let pairedSidecarSuffixPattern =\n    {PAIRED_SIDECAR_SUFFIX_PATTERN:?}\n}}\n"
        ));
        return out;
    }
    match target {
        Target::Ts => out.push_str("export const RESERVED_WINDOWS_NAMES: readonly string[] = [\n"),
        Target::Cs => out.push_str("using System;\nusing System.Collections.Frozen;\n\nnamespace Maple.WinUI.Generated;\n\npublic static class FilenameVocabulary\n{\n    public static readonly FrozenSet<string> ReservedWindowsNames = new[]\n    {\n"),
        _ => panic!("filename supports ts / cs / swift"),
    }
    let quote = if matches!(target, Target::Ts) {
        "'"
    } else {
        "\""
    };
    for name in RESERVED_WINDOWS_NAMES {
        out.push_str(&format!(
            "{}{quote}{name}{quote},\n",
            if matches!(target, Target::Cs) {
                "        "
            } else {
                "  "
            }
        ));
    }
    if matches!(target, Target::Cs) {
        out.push_str("    }.ToFrozenSet(StringComparer.OrdinalIgnoreCase);\n");
        out.push_str(&format!(
            "    public const string OriginalPathMarkerSuffix = {TRASH_ORIGINAL_PATH_SUFFIX:?};\n    public const string RestoreCollisionSuffix = {TRASH_RESTORE_COLLISION_SUFFIX:?};\n    public const string PairedSidecarSuffixPattern = {PAIRED_SIDECAR_SUFFIX_PATTERN:?};\n}}\n"
        ));
    } else {
        out.push_str("];\n");
        let pattern = PAIRED_SIDECAR_SUFFIX_PATTERN.replace('\\', "\\\\");
        out.push_str(&format!(
            "export const TRASH_RESTORE_COLLISION_SUFFIX = '{TRASH_RESTORE_COLLISION_SUFFIX}';\nexport const PAIRED_SIDECAR_SUFFIX_PATTERN =\n  '{pattern}';\n"
        ));
    }
    out
}
