//! Portable filesystem names share raw-core's reserved-device vocabulary.
use crate::Target;
use raw_core::filename::RESERVED_WINDOWS_NAMES;

pub fn emit(target: Target) -> String {
    let mut out = String::from("// Generated by codegen --schema filename. Do not edit.\n\n");
    match target {
        Target::Ts => out.push_str("export const RESERVED_WINDOWS_NAMES: readonly string[] = [\n"),
        Target::Cs => out.push_str("using System;\nusing System.Collections.Frozen;\n\nnamespace Maple.WinUI.Generated;\n\npublic static class FilenameVocabulary\n{\n    public static readonly FrozenSet<string> ReservedWindowsNames = new[]\n    {\n"),
        _ => panic!("filename supports ts / cs"),
    }
    let quote = if matches!(target, Target::Ts) {
        "'"
    } else {
        "\""
    };
    for name in RESERVED_WINDOWS_NAMES {
        out.push_str(&format!(
            "{}{quote}{name}{quote},\n",
            if matches!(target, Target::Cs) {
                "        "
            } else {
                "  "
            }
        ));
    }
    out.push_str(if matches!(target, Target::Cs) {
        "    }.ToFrozenSet(StringComparer.OrdinalIgnoreCase);\n}\n"
    } else {
        "];\n"
    });
    out
}
