//! Film-catalog emitters — Swift + TypeScript output for
//! `raw_core::film_catalog::FILM_CATALOG` (epic #2683, Task 6).
//!
//! Mirrors `adjustment.rs`'s string-building style. `FILM_CATALOG` is
//! already sorted by category then id (see `film_catalog.rs`'s own doc
//! comment), so both emitters pass the table order through unchanged —
//! there is no re-sort here.

use raw_core::film_catalog::{FilmCategory, FilmLookEntry};

const BANNER_SWIFT: &str = "// THIS FILE IS GENERATED BY tools/codegen.sh. DO NOT EDIT.\n\
     // Source: src/raw-pipeline/raw-core/src/film_catalog.rs (FILM_CATALOG).\n";

const BANNER_TS: &str = "// THIS FILE IS GENERATED BY tools/codegen.sh. DO NOT EDIT.\n\
     // Source: src/raw-pipeline/raw-core/src/film_catalog.rs (FILM_CATALOG).\n";

/// `FilmCategory` -> the snake_case raw value (matches the top-level cube
/// pack directory names, per `film_catalog.rs`'s doc comment on the enum).
fn category_snake(category: FilmCategory) -> &'static str {
    match category {
        FilmCategory::BlackWhite => "black_white",
        FilmCategory::CinemaPrint => "cinema_print",
        FilmCategory::ColorNegative => "color_negative",
        FilmCategory::ConsumerVintage => "consumer_vintage",
        FilmCategory::Instant => "instant",
        FilmCategory::Slide => "slide",
    }
}

/// `FilmCategory` -> the Swift camelCase case identifier.
fn category_swift_case(category: FilmCategory) -> &'static str {
    match category {
        FilmCategory::BlackWhite => "blackWhite",
        FilmCategory::CinemaPrint => "cinemaPrint",
        FilmCategory::ColorNegative => "colorNegative",
        FilmCategory::ConsumerVintage => "consumerVintage",
        FilmCategory::Instant => "instant",
        FilmCategory::Slide => "slide",
    }
}

/// All six categories in a fixed, deterministic order (matches the union /
/// `CaseIterable` order both targets emit). Hand-listed rather than derived
/// from the table: the category set is a closed enum (six top-level cube
/// pack directories), not something a future catalog entry should be able
/// to reorder.
const ALL_CATEGORIES: [FilmCategory; 6] = [
    FilmCategory::BlackWhite,
    FilmCategory::CinemaPrint,
    FilmCategory::ColorNegative,
    FilmCategory::ConsumerVintage,
    FilmCategory::Instant,
    FilmCategory::Slide,
];

// -------------------------------------------------------------------------
// Swift
// -------------------------------------------------------------------------

pub(crate) fn emit_swift(catalog: &[FilmLookEntry]) -> String {
    let mut s = String::new();
    s.push_str(BANNER_SWIFT);
    s.push_str("//\n");
    s.push_str("// Emits the film-look catalog: the FilmCategory enum, the\n");
    s.push_str("// FilmLookEntry value type, and FilmCatalog.all — one entry per\n");
    s.push_str("// `.mlut` shipped under resources/film-luts/. `id` doubles as the\n");
    s.push_str("// `papp:FilmLook` XMP value and the `.mlut` filename stem.\n\n");
    s.push_str("import Foundation\n\n");

    s.push_str("/// Which broad family a film-look belongs to — matches the six\n");
    s.push_str("/// top-level category directories in the ingested cube pack.\n");
    s.push_str("public enum FilmCategory: String, CaseIterable, Sendable {\n");
    for category in ALL_CATEGORIES {
        s.push_str(&format!(
            "    case {} = \"{}\"\n",
            category_swift_case(category),
            category_snake(category),
        ));
    }
    s.push_str("}\n\n");

    s.push_str("/// One catalog entry: the `.mlut` id (also the `papp:FilmLook`\n");
    s.push_str("/// XMP value), a human display name, and its category.\n");
    s.push_str("public struct FilmLookEntry: Sendable {\n");
    s.push_str("    public let id: String\n");
    s.push_str("    public let name: String\n");
    s.push_str("    public let category: FilmCategory\n");
    s.push_str("}\n\n");

    s.push_str("/// The full film-look catalog, in canonical (category, id) order.\n");
    s.push_str("public enum FilmCatalog {\n");
    s.push_str("    public static let all: [FilmLookEntry] = [\n");
    for entry in catalog {
        s.push_str(&format!(
            "        FilmLookEntry(id: \"{}\", name: \"{}\", category: .{}),\n",
            entry.id,
            entry.name,
            category_swift_case(entry.category),
        ));
    }
    s.push_str("    ]\n");
    s.push_str("}\n");
    s
}

// -------------------------------------------------------------------------
// TypeScript
// -------------------------------------------------------------------------

pub(crate) fn emit_ts(catalog: &[FilmLookEntry]) -> String {
    let mut s = String::new();
    s.push_str(BANNER_TS);
    s.push_str("//\n");
    s.push_str("// Emits the film-look catalog: the FilmCategory union, the\n");
    s.push_str("// FilmLookEntry interface, and FILM_CATALOG — one entry per\n");
    s.push_str("// `.mlut` shipped under resources/film-luts/. `id` doubles as the\n");
    s.push_str("// `papp:FilmLook` XMP value and the `.mlut` filename stem.\n\n");

    s.push_str("export type FilmCategory =\n");
    for (i, category) in ALL_CATEGORIES.iter().enumerate() {
        let sep = if i == ALL_CATEGORIES.len() - 1 { ";" } else { "" };
        s.push_str(&format!("  | '{}'{}\n", category_snake(*category), sep));
    }
    s.push('\n');

    s.push_str("export interface FilmLookEntry {\n");
    s.push_str("  readonly id: string;\n");
    s.push_str("  readonly name: string;\n");
    s.push_str("  readonly category: FilmCategory;\n");
    s.push_str("}\n\n");

    s.push_str("export const FILM_CATALOG: readonly FilmLookEntry[] = [\n");
    for entry in catalog {
        s.push_str(&emit_ts_entry(entry));
    }
    s.push_str("];\n");
    s
}

/// One `FILM_CATALOG` array entry, formatted to match what
/// `prettier --print-width 100` would produce for the same object literal:
/// single-line if it fits within the 100-column print width (the repo's
/// `.prettierrc`), otherwise one property per line. Hand-replicated here
/// (rather than shelling out to prettier) so the emitter stays a pure
/// function — `tools/codegen.sh`'s drift gate then confirms the two agree.
fn emit_ts_entry(entry: &FilmLookEntry) -> String {
    let compact = format!(
        "  {{ id: '{}', name: '{}', category: '{}' }},\n",
        entry.id,
        entry.name,
        category_snake(entry.category),
    );
    // `.len()` is byte length, but every field here is ASCII, so it equals
    // prettier's column count.
    if compact.trim_end_matches('\n').len() <= 100 {
        compact
    } else {
        format!(
            "  {{\n    id: '{}',\n    name: '{}',\n    category: '{}',\n  }},\n",
            entry.id,
            entry.name,
            category_snake(entry.category),
        )
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    use raw_core::film_catalog::FILM_CATALOG;

    #[test]
    fn swift_emits_hundred_entries() {
        let out = emit_swift(FILM_CATALOG);
        assert_eq!(out.matches("FilmLookEntry(id:").count(), 100);
        assert!(out.contains("public enum FilmCategory: String, CaseIterable, Sendable {"));
        assert!(out.contains("case blackWhite = \"black_white\""));
        assert!(out.contains("case slide = \"slide\""));
        assert!(out.contains("public struct FilmLookEntry: Sendable {"));
        assert!(out.contains("public enum FilmCatalog {"));
        assert!(out.contains("public static let all: [FilmLookEntry] = ["));
        assert!(out.contains(
            "FilmLookEntry(id: \"black_white_agfa_apx_100\", name: \"Agfa APX 100\", category: .blackWhite),"
        ));
    }

    #[test]
    fn ts_emits_hundred_entries() {
        let out = emit_ts(FILM_CATALOG);
        // "id: '" appears once per entry regardless of whether
        // `emit_ts_entry` chose the compact or the multi-line form.
        assert_eq!(out.matches("id: '").count(), 100);
        assert!(out.contains(
            "export type FilmCategory =\n  | 'black_white'\n  | 'cinema_print'\n  | 'color_negative'\n  | 'consumer_vintage'\n  | 'instant'\n  | 'slide';\n"
        ));
        assert!(out.contains("export interface FilmLookEntry {"));
        assert!(out.contains("readonly id: string;"));
        assert!(out.contains("readonly category: FilmCategory;"));
        assert!(out.contains("export const FILM_CATALOG: readonly FilmLookEntry[] = ["));
        assert!(out.contains(
            "{ id: 'black_white_agfa_apx_100', name: 'Agfa APX 100', category: 'black_white' },"
        ));
    }

    #[test]
    fn category_ordering_is_canonical() {
        // Category union / CaseIterable order is fixed, not table-derived —
        // pin it so a future catalog re-sort can't silently reorder it.
        assert_eq!(
            ALL_CATEGORIES.map(category_snake),
            [
                "black_white",
                "cinema_print",
                "color_negative",
                "consumer_vintage",
                "instant",
                "slide",
            ]
        );
    }

    #[test]
    fn determinism_double_emit_is_identical() {
        let a = emit_swift(FILM_CATALOG);
        let b = emit_swift(FILM_CATALOG);
        assert_eq!(a, b);
        let a = emit_ts(FILM_CATALOG);
        let b = emit_ts(FILM_CATALOG);
        assert_eq!(a, b);
    }
}
