//! The mask-group discriminants/stride travel through every host and WGSL.
use crate::Target;
use raw_core::types::local_adjustment::flat::*;
use raw_core::types::MaskCombine;

pub fn emit(target: Target) -> String {
    let constants = [
        ("LAYER_FLAT_LEN", LAYER_FLAT_LEN as f32, false),
        ("KIND_LINEAR", KIND_LINEAR, true),
        ("KIND_RADIAL", KIND_RADIAL, true),
        ("KIND_BITMAP", KIND_BITMAP, true),
        ("KIND_EVERYWHERE", KIND_EVERYWHERE, true),
        ("KIND_GROUP", KIND_GROUP, true),
        ("KIND_COMPONENT_BASE", KIND_COMPONENT_BASE, true),
        (
            "COMPONENT_COMBINE_STRIDE",
            COMPONENT_COMBINE_STRIDE as f32,
            false,
        ),
        (
            "COMPONENT_INVERT_OFFSET",
            COMPONENT_INVERT_OFFSET as f32,
            false,
        ),
        ("COMPONENT_CODE_COUNT", COMPONENT_CODE_COUNT as f32, false),
        ("MASK_GROUP_VERSION", MASK_GROUP_VERSION as f32, false),
    ];
    let mut out =
        String::from("// Generated by codegen --schema local-mask-wire. Do not edit.\n\n");
    match target {
        Target::Swift => out.push_str("public enum LocalMaskWire {\n"),
        Target::Cs => out
            .push_str("namespace Maple.WinUI.Generated;\n\npublic static class LocalMaskWire\n{\n"),
        Target::Rust | Target::Ts | Target::Wgsl => {}
        _ => panic!("local-mask-wire supports rust / swift / ts / cs / wgsl"),
    }
    for (name, value, float) in constants {
        out.push_str(&match target {
            Target::Rust => format!(
                "pub const {name}: {} = {}{};\n",
                if float {
                    "f32"
                } else if name == "LAYER_FLAT_LEN" {
                    "usize"
                } else {
                    "u32"
                },
                value,
                if float { ".0" } else { "" }
            ),
            Target::Wgsl => format!(
                "const {name}: {} = {}{};\n",
                if float { "f32" } else { "u32" },
                value,
                if float { ".0" } else { "u" }
            ),
            Target::Ts => format!("export const {name} = {value};\n"),
            Target::Swift => format!(
                "  public static let {}: {} = {value}\n",
                crate::camel_case(&name.to_lowercase()),
                if float { "Float" } else { "Int" }
            ),
            Target::Cs => format!(
                "    public const {} {name} = {}{};\n",
                if float { "float" } else { "int" },
                value,
                if float { "f" } else { "" }
            ),
            _ => unreachable!(),
        });
    }
    if matches!(target, Target::Swift | Target::Cs) {
        out.push_str("}\n");
    }
    match target {
        Target::Swift => {
            out.push_str(
                "\npublic enum MaskCombine: Int, CaseIterable, Codable, Sendable, Hashable {\n",
            );
            for combine in MaskCombine::ALL {
                out.push_str(&format!(
                    "  case {} = {}\n",
                    combine.name().to_lowercase(),
                    combine as u32
                ));
            }
            out.push_str("}\n");
        }
        Target::Ts => {
            out.push_str("\nexport const MASK_COMBINE_CODES = {\n");
            for combine in MaskCombine::ALL {
                out.push_str(&format!(
                    "  {}: {},\n",
                    combine.name().to_lowercase(),
                    combine as u32
                ));
            }
            out.push_str(
                "} as const;\nexport type MaskCombine = keyof typeof MASK_COMBINE_CODES;\n",
            );
        }
        Target::Cs => {
            out.push_str("\npublic enum MaskCombine\n{\n");
            for combine in MaskCombine::ALL {
                out.push_str(&format!("    {} = {},\n", combine.name(), combine as u32));
            }
            out.push_str("}\n");
        }
        _ => {}
    }
    out
}
