//! Cross-platform codegen for raw-core canonical schemas.
//!
//! Two schemas today:
//!
//! - `adjustment` (`raw_core::types::ADJUSTMENT_SCHEMA`, ticket #118) — slider
//!   range constants, the canonical field-name enum, the TS interface, and
//!   the TS default factory. Swift defaults stay hand-written in
//!   `AdjustmentModel.swift` so per-field doc-comments can live next to
//!   each `let` (per #326, sharpen converges to 40 / 1.0 / 25 / 0).
//! - `ui-tokens` (`raw_core::ui_tokens::{COLOR_TOKENS, MOTION_TOKENS}`,
//!   ticket #606) — design-system colors + motion specs. Emitter lives in
//!   `ui_tokens.rs` next to this file.
//!
//! Driven from `tools/codegen.sh`. The codegen-drift CI gate
//! (`.github/workflows/cross.yml`) runs the script then `git diff
//! --exit-code` so hand-edits to `Generated/` files fail fast.

mod color_matrices;
mod ui_tokens;

use std::fs;
use std::path::PathBuf;

use clap::{Parser, ValueEnum};
use raw_core::types::{FieldKind, FieldSpec, ADJUSTMENT_SCHEMA};
use raw_core::ui_tokens::{COLOR_TOKENS, MOTION_TOKENS};

#[derive(Copy, Clone, Debug, ValueEnum)]
enum Target {
    Swift,
    Ts,
    /// SCSS / CSS custom-property output. Only valid for `--schema ui-tokens`;
    /// the adjustment schema has no SCSS surface.
    Scss,
    /// WGSL output. Only valid for `--schema color-matrices` (epic #925 P2 /
    /// #990) — emits the GPU scene-linear kernels' baked color matrices.
    Wgsl,
}

#[derive(Copy, Clone, Debug, ValueEnum, PartialEq, Eq)]
enum Schema {
    /// `raw_core::types::ADJUSTMENT_SCHEMA` — slider ranges, field-name enums,
    /// TS interface + default factory.
    Adjustment,
    /// `raw_core::ui_tokens::{COLOR_TOKENS, MOTION_TOKENS}` — design-system
    /// color hex strings + motion duration/easing pairs. Ticket #606.
    UiTokens,
    /// Oklab + Rec.2020/sRGB color matrices (forward + inverse) consumed by the
    /// GPU scene-linear WGSL kernels. WGSL target only. Epic #925 P2 / #990.
    ColorMatrices,
}

#[derive(Parser, Debug)]
#[command(
    name = "codegen",
    about = "Emit Swift / TS / SCSS shape declarations from raw-core canonical schemas"
)]
struct Cli {
    /// Which canonical schema to emit. Defaults to `adjustment` for back-compat
    /// with the original single-schema codegen.
    #[arg(long, value_enum, default_value_t = Schema::Adjustment)]
    schema: Schema,
    #[arg(long, value_enum)]
    target: Target,
    #[arg(long)]
    out: PathBuf,
}

const BANNER_SWIFT: &str = "// THIS FILE IS GENERATED BY tools/codegen.sh. DO NOT EDIT.\n\
     // Source: src/raw-pipeline/raw-core/src/types/adjustment.rs (ADJUSTMENT_SCHEMA).\n";

const BANNER_TS: &str = "// THIS FILE IS GENERATED BY tools/codegen.sh. DO NOT EDIT.\n\
     // Source: src/raw-pipeline/raw-core/src/types/adjustment.rs (ADJUSTMENT_SCHEMA).\n";

fn main() {
    let cli = Cli::parse();
    let out = match (cli.schema, cli.target) {
        (Schema::Adjustment, Target::Swift) => emit_swift(ADJUSTMENT_SCHEMA),
        (Schema::Adjustment, Target::Ts) => emit_ts(ADJUSTMENT_SCHEMA),
        (Schema::Adjustment, Target::Scss | Target::Wgsl) => {
            eprintln!("codegen: --schema adjustment supports only swift / ts targets");
            std::process::exit(2);
        }
        (Schema::UiTokens, Target::Swift) => ui_tokens::emit_swift(COLOR_TOKENS, MOTION_TOKENS),
        (Schema::UiTokens, Target::Ts) => ui_tokens::emit_ts(COLOR_TOKENS, MOTION_TOKENS),
        (Schema::UiTokens, Target::Scss) => ui_tokens::emit_scss(COLOR_TOKENS, MOTION_TOKENS),
        (Schema::UiTokens, Target::Wgsl) => {
            eprintln!("codegen: --schema ui-tokens has no WGSL target");
            std::process::exit(2);
        }
        (Schema::ColorMatrices, Target::Wgsl) => color_matrices::emit_wgsl(),
        (Schema::ColorMatrices, Target::Swift | Target::Ts | Target::Scss) => {
            eprintln!("codegen: --schema color-matrices supports only the wgsl target");
            std::process::exit(2);
        }
    };
    if let Some(parent) = cli.out.parent() {
        fs::create_dir_all(parent).expect("create parent dir");
    }
    fs::write(&cli.out, out).expect("write generated file");
}

/// Render an `f32` schema constant in a stable, deterministic form.
///
/// Used uniformly for `range.0`, `range.1`, and `default_f32`. `{:?}` picks
/// the shortest round-tripping decimal, which is stable across Rust versions
/// for the literals in `ADJUSTMENT_SCHEMA` (they're all small exact decimals
/// like `2000.0`, `-100.0`, `0.5`, `25.0`).
fn f(v: f32) -> String {
    let s = format!("{:?}", v);
    // `{:?}` on f32 always includes a decimal point. Belt-and-braces guard
    // in case that ever changes: append `.0` if no fractional indicator.
    if s.contains('.') || s.contains('e') || s.contains('E') {
        s
    } else {
        format!("{}.0", s)
    }
}

/// snake_case -> camelCase. `temperature` -> `temperature`,
/// `sharpen_amount` -> `sharpenAmount`.
pub(crate) fn camel_case(snake: &str) -> String {
    let mut out = String::with_capacity(snake.len());
    let mut upper_next = false;
    for ch in snake.chars() {
        if ch == '_' {
            upper_next = true;
        } else if upper_next {
            out.extend(ch.to_uppercase());
            upper_next = false;
        } else {
            out.push(ch);
        }
    }
    out
}

/// Rewrite backtick-wrapped Rust-style snake_case identifiers in a doc string
/// to their target-language camelCase form. Only tokens that exactly match a
/// schema `name` are rewritten — generic snake_case text (e.g. an XMP key
/// fragment like `crs:Sharpness`) is left alone.
///
/// Motivation (PR #463 review): the canonical `ADJUSTMENT_SCHEMA` doc strings
/// reference sibling fields by their Rust snake_case names (e.g. "use
/// `capture_sharpening_sigma`"). Emitting that verbatim into Swift/TS sends
/// platform callers chasing an identifier that does not exist in their
/// language — Swift sees `captureSharpeningSigma`, TS sees
/// `captureSharpeningSigma`. Both targets use camelCase, so a single
/// rewriter covers both.
fn rewrite_doc_identifiers(doc: &str, schema: &[FieldSpec]) -> String {
    let mut out = String::with_capacity(doc.len());
    let bytes = doc.as_bytes();
    let mut i = 0;
    while i < bytes.len() {
        if bytes[i] == b'`' {
            // Find the closing backtick.
            if let Some(rel_end) = bytes[i + 1..].iter().position(|&b| b == b'`') {
                let end = i + 1 + rel_end;
                let token = &doc[i + 1..end];
                // Only rewrite if the token exactly matches a schema field
                // name (snake_case). Leaves things like `papp:Foo` and
                // `crs:Bar` untouched because they do not appear as schema
                // names.
                if schema.iter().any(|s| s.name == token) {
                    out.push('`');
                    out.push_str(&camel_case(token));
                    out.push('`');
                } else {
                    out.push_str(&doc[i..=end]);
                }
                i = end + 1;
                continue;
            }
        }
        out.push(doc[i..].chars().next().unwrap());
        i += doc[i..].chars().next().unwrap().len_utf8();
    }
    out
}

// -------------------------------------------------------------------------
// Swift
// -------------------------------------------------------------------------

fn emit_swift(schema: &[FieldSpec]) -> String {
    let mut s = String::new();
    s.push_str(BANNER_SWIFT);
    s.push_str("//\n");
    s.push_str("// Emits range constants and a canonical field-name enum for\n");
    s.push_str("// `AdjustmentModel`. The struct itself + defaults + init stay\n");
    s.push_str("// hand-written in `AdjustmentModel.swift`; Apple's defaults\n");
    s.push_str("// match raw-core's canonical values (per #326, sharpen converges\n");
    s.push_str("// to the reference renderer's import baseline: 40 / 1.0 / 25 / 0).\n\n");
    s.push_str("import Foundation\n\n");

    // FieldName enum — canonical snake_case names from the schema.
    s.push_str("extension AdjustmentModel {\n");
    s.push_str("    /// Canonical field identifiers, snake_case as recorded in\n");
    s.push_str("    /// `raw_core::types::ADJUSTMENT_SCHEMA`. Use these when you need\n");
    s.push_str("    /// a stable string key independent of Swift's camelCase property names.\n");
    s.push_str("    public enum FieldName: String, CaseIterable, Sendable, Hashable {\n");
    for spec in schema {
        // case <camel> = "<snake>"
        let case_ident = camel_case(spec.name);
        s.push_str(&format!(
            "        case {} = \"{}\"\n",
            case_ident, spec.name
        ));
    }
    s.push_str("    }\n\n");

    // Range constants for F32 fields.
    s.push_str("    // MARK: - Range constants (canonical, generated)\n\n");
    for spec in schema {
        if !matches!(spec.kind, FieldKind::F32) {
            continue;
        }
        let camel = camel_case(spec.name);
        let doc = rewrite_doc_identifiers(spec.doc, schema);
        s.push_str(&format!("    /// {}\n", doc));
        s.push_str(&format!(
            "    public static let {}Range: ClosedRange<Double> = {}...{}\n",
            camel,
            f(spec.range.0),
            f(spec.range.1),
        ));
    }
    s.push_str("}\n");
    s
}

// -------------------------------------------------------------------------
// TypeScript
// -------------------------------------------------------------------------

fn emit_ts(schema: &[FieldSpec]) -> String {
    let mut s = String::new();
    s.push_str(BANNER_TS);
    s.push_str("//\n");
    s.push_str("// Emits the AdjustmentModel field interface, range constants, and a\n");
    s.push_str("// default factory. Hand-written extensions (e.g. `WhiteBalancePreset`)\n");
    s.push_str("// live alongside in `adjustment-model.ts` and augment this shape.\n\n");

    // HighlightRecoveryMode union. `Blend` and `Luminance` are legacy
    // back-compat variants kept so old XMP sidecars continue to parse;
    // both upgrade to `ChromaticAdaptation` at apply time (see
    // raw-core::stages::highlight_recovery). Emitted in the multi-line
    // form prettier produces past its print-width threshold so the
    // codegen-drift + format-check gates agree without a post-step
    // through `prettier --write`.
    s.push_str(
        "export type HighlightRecoveryMode =\n  \
         | 'Off'\n  \
         | 'Blend'\n  \
         | 'Luminance'\n  \
         | 'ChromaticAdaptation'\n  \
         | 'OklabChromaReduction';\n\n",
    );

    // DisplayLookCurve (ticket #371; retired in #443 — Wave-3 closing step
    // of #416). Both variants are now identical no-ops at the pipeline
    // level; the enum is kept on `AdjustmentModel` and emitted to Swift /
    // TS so `papp:Look` in pre-#443 sidecars round-trips. See
    // `raw-core::types::adjustment::Look`.
    s.push_str("export type Look = 'Neutral' | 'Default';\n\n");

    // Render-shaping profile (Auto Profile Phase 1, ticket #536). `Auto`
    // (default) fits a per-image curve from the embedded JPEG preview at
    // render time; `Neutral` runs the AgX scene-referred view transform.
    // Pre-#536 sidecars carrying `papp:Look` migrate transparently in the
    // parser (Default → Auto, Neutral → Neutral). See
    // raw-core::types::adjustment::Profile.
    s.push_str("export type Profile = 'Auto' | 'Neutral';\n\n");

    // Tone-curve application mode (ticket #436). `PerChannel` applies the
    // three R/G/B curves independently (hue shifts); `RatioPreserving`
    // folds them through Rec.2020 luma to preserve hue. Default is
    // `PerChannel` for backward compatibility (see
    // raw-core::stages::tone_curves).
    s.push_str("export type ToneCurveMode = 'PerChannel' | 'RatioPreserving';\n\n");

    // User white-balance method (ticket #431). `Cat16` performs proper
    // chromatic adaptation in CAT16 LMS cone space (default since #431);
    // `DiagonalRec2020` is the legacy von-Kries diagonal-gain path
    // retained for parity A/B (see raw-core::stages::white_balance).
    s.push_str("export type WbMethod = 'Cat16' | 'DiagonalRec2020';\n\n");

    // Per-image auto-exposure mode (ticket #429). `On` (default) anchors
    // scene mid-gray to 0.18 before AgX so every camera lands at the
    // same point on the sigmoid by default; `Off` skips anchoring for
    // strict scene-referred output. The user `exposure` slider stacks
    // additively in EV on top (see raw-core::stages::auto_exposure).
    s.push_str("export type AutoExposureMode = 'Off' | 'On';\n\n");

    // Hot/dead-pixel suppression (#1106). `Off` (default) skips the
    // pre-demosaic defect-replacement stage bit-identically; `On` replaces
    // same-color-neighbor outliers with the neighborhood median inside the
    // decode product (see raw-core::stages::hot_pixel).
    s.push_str("export type HotPixelSuppressionMode = 'Off' | 'On';\n\n");

    // Generated interface.
    s.push_str("export interface GeneratedAdjustmentModel {\n");
    for spec in schema {
        let camel = camel_case(spec.name);
        let doc = rewrite_doc_identifiers(spec.doc, schema);
        match spec.kind {
            FieldKind::F32 => {
                s.push_str(&format!(
                    "  /** {} Range: [{}, {}]. */\n  {}: number;\n",
                    doc,
                    f(spec.range.0),
                    f(spec.range.1),
                    camel,
                ));
            }
            FieldKind::Enum => {
                // Only HighlightRecoveryMode exists today; emit its TS type name.
                let ts_ty = spec.enum_name;
                s.push_str(&format!("  /** {} */\n  {}: {};\n", doc, camel, ts_ty,));
            }
        }
    }
    s.push_str("}\n\n");

    // Range constants.
    s.push_str(
        "/** Canonical `[min, max]` range for each scalar field, generated from raw-core. */\n",
    );
    s.push_str("export const ADJUSTMENT_RANGES = {\n");
    for spec in schema {
        if !matches!(spec.kind, FieldKind::F32) {
            continue;
        }
        let camel = camel_case(spec.name);
        s.push_str(&format!(
            "  {}: [{}, {}] as const,\n",
            camel,
            f(spec.range.0),
            f(spec.range.1),
        ));
    }
    s.push_str("} as const;\n\n");

    // Default factory.
    s.push_str("/** Canonical raw-core defaults, generated from `ADJUSTMENT_SCHEMA`. */\n");
    s.push_str("export function defaultGeneratedAdjustmentModel(): GeneratedAdjustmentModel {\n");
    s.push_str("  return {\n");
    for spec in schema {
        let camel = camel_case(spec.name);
        match spec.kind {
            FieldKind::F32 => {
                s.push_str(&format!("    {}: {},\n", camel, f(spec.default_f32)));
            }
            FieldKind::Enum => {
                // No enum-default slot on `FieldSpec` (the existing schema
                // only carries `default_f32` for scalars). Hard-coded per
                // enum_name; mirrors raw-core's `Default for <Enum>` impls.
                let default_variant = match spec.enum_name {
                    "HighlightRecoveryMode" => "ChromaticAdaptation",
                    // DisplayLookCurve (#371). New users get the empirical
                    // Look, not Neutral.
                    "Look" => "Default",
                    // Tone-curve mode (#436). Default preserves pre-#436
                    // behavior (absent attribute = current pipeline output).
                    "ToneCurveMode" => "PerChannel",
                    // User WB method (#431). New users get proper chromatic
                    // adaptation in CAT16 cone space.
                    "WbMethod" => "Cat16",
                    // Per-image auto-exposure (#429). `On` is the new default —
                    // anchor scene mid-gray to 0.18 before AgX.
                    "AutoExposureMode" => "On",
                    // Auto Profile (#536). Default fits a per-image curve
                    // from the embedded preview; `Neutral` runs AgX.
                    "Profile" => "Auto",
                    // Hot/dead-pixel suppression (#1106). Off until a
                    // harness sweep shows enabling is free on clean fixtures.
                    "HotPixelSuppressionMode" => "Off",
                    other => panic!(
                        "codegen: no default mapping for enum `{}` — add one \
                         alongside the matching Rust `Default` impl",
                        other
                    ),
                };
                s.push_str(&format!("    {}: '{}',\n", camel, default_variant));
            }
        }
    }
    s.push_str("  };\n");
    s.push_str("}\n");
    s
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn camel_case_basic() {
        assert_eq!(camel_case("temperature"), "temperature");
        assert_eq!(camel_case("sharpen_amount"), "sharpenAmount");
        assert_eq!(camel_case("nr_color"), "nrColor");
        assert_eq!(camel_case("highlight_recovery"), "highlightRecovery");
    }

    #[test]
    fn f_renders_with_decimal() {
        assert!(f(2000.0).contains('.'));
        assert!(f(-100.0).contains('.'));
        assert!(f(0.5).contains('.'));
        assert!(f(25.0).contains('.'));
    }

    #[test]
    fn swift_emits_field_name_enum_and_ranges() {
        let out = emit_swift(ADJUSTMENT_SCHEMA);
        assert!(out.contains("public enum FieldName"));
        assert!(out.contains("case temperature = \"temperature\""));
        assert!(out.contains("case sharpenAmount = \"sharpen_amount\""));
        assert!(out.contains("public static let temperatureRange: ClosedRange<Double>"));
        // No defaults emitted.
        assert!(!out.contains("public static let `default`"));
        assert!(!out.contains("defaultAdjustmentModel"));
    }

    #[test]
    fn ts_emits_interface_ranges_and_defaults() {
        let out = emit_ts(ADJUSTMENT_SCHEMA);
        assert!(out.contains("export interface GeneratedAdjustmentModel"));
        assert!(out.contains("temperature: number;"));
        assert!(out.contains("highlightRecovery: HighlightRecoveryMode;"));
        assert!(out.contains("ADJUSTMENT_RANGES"));
        assert!(out.contains("defaultGeneratedAdjustmentModel"));
        assert!(out.contains("temperature: 6500"));
        // Auto Profile (#536): Profile enum is in ADJUSTMENT_SCHEMA, so the
        // codegen must emit the type, the interface field, and a default.
        assert!(out.contains("export type Profile = 'Auto' | 'Neutral';"));
        assert!(out.contains("profile: Profile;"));
        assert!(out.contains("profile: 'Auto'"));
    }

    #[test]
    fn rewrite_doc_identifiers_rewrites_schema_names_only() {
        // Backtick-wrapped tokens that match a schema field name are
        // rewritten to camelCase; anything else (XMP keys, prose) is left
        // alone. Per PR #463 review.
        let doc = "Deprecated: use `capture_sharpening_sigma`. See the XMP \
                   `papp:CaptureSharpeningRadius` read-path; not the \
                   `temperature` field.";
        let rewritten = rewrite_doc_identifiers(doc, ADJUSTMENT_SCHEMA);
        assert!(
            rewritten.contains("`captureSharpeningSigma`"),
            "schema field name should be camelCased, got: {}",
            rewritten
        );
        assert!(
            rewritten.contains("`temperature`"),
            "single-word schema names should pass through unchanged"
        );
        assert!(
            rewritten.contains("`papp:CaptureSharpeningRadius`"),
            "XMP keys are not schema names — must be left alone, got: {}",
            rewritten
        );
        assert!(
            !rewritten.contains("`capture_sharpening_sigma`"),
            "snake_case schema reference should have been rewritten, got: {}",
            rewritten
        );
    }

    #[test]
    fn determinism_double_emit_is_identical() {
        // Running the emitters twice in-process produces identical strings;
        // the on-disk determinism check happens in tools/codegen.sh.
        let a = emit_swift(ADJUSTMENT_SCHEMA);
        let b = emit_swift(ADJUSTMENT_SCHEMA);
        assert_eq!(a, b);
        let a = emit_ts(ADJUSTMENT_SCHEMA);
        let b = emit_ts(ADJUSTMENT_SCHEMA);
        assert_eq!(a, b);
    }
}
