//! Cross-platform codegen for `raw-core::types::AdjustmentModel`.
//!
//! Reads `ADJUSTMENT_SCHEMA` from `raw_core::types` (the canonical schema
//! landed in #117) and emits Swift + TypeScript shape declarations to keep
//! the platform mirrors from drifting. Driven from `tools/codegen.sh`.
//!
//! Per #118: emit ranges, field names, the TS interface, and a TS default
//! factory. Do NOT emit Swift defaults — Apple's `AdjustmentModel` uses
//! ACR-like sharpen defaults (45 / 1.0) that intentionally differ from the
//! Rust canonical defaults (0 / 0.5); those stay hand-written.

use std::fs;
use std::path::PathBuf;

use clap::{Parser, ValueEnum};
use raw_core::types::{FieldKind, FieldSpec, ADJUSTMENT_SCHEMA};

#[derive(Copy, Clone, Debug, ValueEnum)]
enum Target {
    Swift,
    Ts,
}

#[derive(Parser, Debug)]
#[command(
    name = "codegen",
    about = "Emit Swift + TS shape declarations from raw_core::types::ADJUSTMENT_SCHEMA"
)]
struct Cli {
    #[arg(long, value_enum)]
    target: Target,
    #[arg(long)]
    out: PathBuf,
}

const BANNER_SWIFT: &str =
    "// THIS FILE IS GENERATED BY tools/codegen.sh. DO NOT EDIT.\n\
     // Source: src/raw-pipeline/raw-core/src/types/adjustment.rs (ADJUSTMENT_SCHEMA).\n";

const BANNER_TS: &str =
    "// THIS FILE IS GENERATED BY tools/codegen.sh. DO NOT EDIT.\n\
     // Source: src/raw-pipeline/raw-core/src/types/adjustment.rs (ADJUSTMENT_SCHEMA).\n";

fn main() {
    let cli = Cli::parse();
    let out = match cli.target {
        Target::Swift => emit_swift(ADJUSTMENT_SCHEMA),
        Target::Ts => emit_ts(ADJUSTMENT_SCHEMA),
    };
    if let Some(parent) = cli.out.parent() {
        fs::create_dir_all(parent).expect("create parent dir");
    }
    fs::write(&cli.out, out).expect("write generated file");
}

/// Render an `f32` schema constant in a stable, deterministic form.
///
/// Used uniformly for `range.0`, `range.1`, and `default_f32`. `{:?}` picks
/// the shortest round-tripping decimal, which is stable across Rust versions
/// for the literals in `ADJUSTMENT_SCHEMA` (they're all small exact decimals
/// like `2000.0`, `-100.0`, `0.5`, `25.0`).
fn f(v: f32) -> String {
    let s = format!("{:?}", v);
    // `{:?}` on f32 always includes a decimal point. Belt-and-braces guard
    // in case that ever changes: append `.0` if no fractional indicator.
    if s.contains('.') || s.contains('e') || s.contains('E') {
        s
    } else {
        format!("{}.0", s)
    }
}

/// snake_case -> camelCase. `temperature` -> `temperature`,
/// `sharpen_amount` -> `sharpenAmount`.
fn camel_case(snake: &str) -> String {
    let mut out = String::with_capacity(snake.len());
    let mut upper_next = false;
    for ch in snake.chars() {
        if ch == '_' {
            upper_next = true;
        } else if upper_next {
            out.extend(ch.to_uppercase());
            upper_next = false;
        } else {
            out.push(ch);
        }
    }
    out
}

// -------------------------------------------------------------------------
// Swift
// -------------------------------------------------------------------------

fn emit_swift(schema: &[FieldSpec]) -> String {
    let mut s = String::new();
    s.push_str(BANNER_SWIFT);
    s.push_str("//\n");
    s.push_str("// Emits range constants and a canonical field-name enum for\n");
    s.push_str("// `AdjustmentModel`. The struct itself + defaults + init stay\n");
    s.push_str("// hand-written in `AdjustmentModel.swift` (Apple uses ACR-like\n");
    s.push_str("// sharpen defaults that diverge from the canonical Rust defaults).\n\n");
    s.push_str("import Foundation\n\n");

    // FieldName enum — canonical snake_case names from the schema.
    s.push_str("extension AdjustmentModel {\n");
    s.push_str("    /// Canonical field identifiers, snake_case as recorded in\n");
    s.push_str("    /// `raw_core::types::ADJUSTMENT_SCHEMA`. Use these when you need\n");
    s.push_str("    /// a stable string key independent of Swift's camelCase property names.\n");
    s.push_str("    public enum FieldName: String, CaseIterable, Sendable, Hashable {\n");
    for spec in schema {
        // case <camel> = "<snake>"
        let case_ident = camel_case(spec.name);
        s.push_str(&format!(
            "        case {} = \"{}\"\n",
            case_ident, spec.name
        ));
    }
    s.push_str("    }\n\n");

    // Range constants for F32 fields.
    s.push_str("    // MARK: - Range constants (canonical, generated)\n\n");
    for spec in schema {
        if !matches!(spec.kind, FieldKind::F32) {
            continue;
        }
        let camel = camel_case(spec.name);
        s.push_str(&format!("    /// {}\n", spec.doc));
        s.push_str(&format!(
            "    public static let {}Range: ClosedRange<Double> = {}...{}\n",
            camel,
            f(spec.range.0),
            f(spec.range.1),
        ));
    }
    s.push_str("}\n");
    s
}

// -------------------------------------------------------------------------
// TypeScript
// -------------------------------------------------------------------------

fn emit_ts(schema: &[FieldSpec]) -> String {
    let mut s = String::new();
    s.push_str(BANNER_TS);
    s.push_str("//\n");
    s.push_str("// Emits the AdjustmentModel field interface, range constants, and a\n");
    s.push_str("// default factory. Hand-written extensions (e.g. `WhiteBalancePreset`)\n");
    s.push_str("// live alongside in `adjustment-model.ts` and augment this shape.\n\n");

    // HighlightRecoveryMode union (only enum field today). `Blend` and
    // `Luminance` are legacy back-compat variants kept so old XMP sidecars
    // continue to parse; both upgrade to `ChromaticAdaptation` at apply time
    // (see raw-core::stages::highlight_recovery).
    s.push_str(
        "export type HighlightRecoveryMode = \
         'Off' | 'Blend' | 'Luminance' | 'ChromaticAdaptation';\n\n",
    );

    // Generated interface.
    s.push_str("export interface GeneratedAdjustmentModel {\n");
    for spec in schema {
        let camel = camel_case(spec.name);
        match spec.kind {
            FieldKind::F32 => {
                s.push_str(&format!(
                    "  /** {} Range: [{}, {}]. */\n  {}: number;\n",
                    spec.doc,
                    f(spec.range.0),
                    f(spec.range.1),
                    camel,
                ));
            }
            FieldKind::Enum => {
                // Only HighlightRecoveryMode exists today; emit its TS type name.
                let ts_ty = spec.enum_name;
                s.push_str(&format!(
                    "  /** {} */\n  {}: {};\n",
                    spec.doc, camel, ts_ty,
                ));
            }
        }
    }
    s.push_str("}\n\n");

    // Range constants.
    s.push_str("/** Canonical `[min, max]` range for each scalar field, generated from raw-core. */\n");
    s.push_str("export const ADJUSTMENT_RANGES = {\n");
    for spec in schema {
        if !matches!(spec.kind, FieldKind::F32) {
            continue;
        }
        let camel = camel_case(spec.name);
        s.push_str(&format!(
            "  {}: [{}, {}] as const,\n",
            camel,
            f(spec.range.0),
            f(spec.range.1),
        ));
    }
    s.push_str("} as const;\n\n");

    // Default factory.
    s.push_str("/** Canonical raw-core defaults, generated from `ADJUSTMENT_SCHEMA`. */\n");
    s.push_str("export function defaultGeneratedAdjustmentModel(): GeneratedAdjustmentModel {\n");
    s.push_str("  return {\n");
    for spec in schema {
        let camel = camel_case(spec.name);
        match spec.kind {
            FieldKind::F32 => {
                s.push_str(&format!("    {}: {},\n", camel, f(spec.default_f32)));
            }
            FieldKind::Enum => {
                // The only enum today is HighlightRecoveryMode; its default
                // is `ChromaticAdaptation` (ticket #336 — tuned algorithm
                // ships as the default; see `HighlightRecoveryMode` docs).
                // Hard-coded because there's no enum default slot on
                // `FieldSpec`.
                s.push_str(&format!("    {}: 'ChromaticAdaptation',\n", camel));
            }
        }
    }
    s.push_str("  };\n");
    s.push_str("}\n");
    s
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn camel_case_basic() {
        assert_eq!(camel_case("temperature"), "temperature");
        assert_eq!(camel_case("sharpen_amount"), "sharpenAmount");
        assert_eq!(camel_case("nr_color"), "nrColor");
        assert_eq!(camel_case("highlight_recovery"), "highlightRecovery");
    }

    #[test]
    fn f_renders_with_decimal() {
        assert!(f(2000.0).contains('.'));
        assert!(f(-100.0).contains('.'));
        assert!(f(0.5).contains('.'));
        assert!(f(25.0).contains('.'));
    }

    #[test]
    fn swift_emits_field_name_enum_and_ranges() {
        let out = emit_swift(ADJUSTMENT_SCHEMA);
        assert!(out.contains("public enum FieldName"));
        assert!(out.contains("case temperature = \"temperature\""));
        assert!(out.contains("case sharpenAmount = \"sharpen_amount\""));
        assert!(out.contains("public static let temperatureRange: ClosedRange<Double>"));
        // No defaults emitted.
        assert!(!out.contains("public static let `default`"));
        assert!(!out.contains("defaultAdjustmentModel"));
    }

    #[test]
    fn ts_emits_interface_ranges_and_defaults() {
        let out = emit_ts(ADJUSTMENT_SCHEMA);
        assert!(out.contains("export interface GeneratedAdjustmentModel"));
        assert!(out.contains("temperature: number;"));
        assert!(out.contains("highlightRecovery: HighlightRecoveryMode;"));
        assert!(out.contains("ADJUSTMENT_RANGES"));
        assert!(out.contains("defaultGeneratedAdjustmentModel"));
        assert!(out.contains("temperature: 6500"));
    }

    #[test]
    fn determinism_double_emit_is_identical() {
        // Running the emitters twice in-process produces identical strings;
        // the on-disk determinism check happens in tools/codegen.sh.
        let a = emit_swift(ADJUSTMENT_SCHEMA);
        let b = emit_swift(ADJUSTMENT_SCHEMA);
        assert_eq!(a, b);
        let a = emit_ts(ADJUSTMENT_SCHEMA);
        let b = emit_ts(ADJUSTMENT_SCHEMA);
        assert_eq!(a, b);
    }
}
