//! Experimental model pins shared with authoring workers (#3941).
use raw_core::types::removal_models::EXPERIMENTAL_REMOVAL_MODELS;

pub fn emit_ts() -> String {
    let mut out = "// Generated by tools/codegen.sh from raw-core experimental pins (#3941).\nexport const EXPERIMENTAL_REMOVAL_MODELS = [\n".to_owned();
    for pin in EXPERIMENTAL_REMOVAL_MODELS {
        out.push_str("  {\n");
        for (key, value) in [
            ("id", pin.id),
            ("file", pin.file),
            ("probe_path", pin.probe_path),
            ("sha256", pin.sha256),
            ("source_revision", pin.source_revision),
            ("checkpoint_sha256", pin.checkpoint_sha256),
            ("license", pin.license),
        ] {
            out.push_str(&crate::support_tiers::ts_string_prop(4, key, value));
        }
        out.push_str(&format!(
            "    size: {},\n    native_side: {},\n    release_qualified: {},\n  }},\n",
            pin.size, pin.native_side, pin.release_qualified
        ));
    }
    out.push_str("] as const;\nexport type RemovalModelId = (typeof EXPERIMENTAL_REMOVAL_MODELS)[number]['id'];\n");
    out
}
