//! Experimental model pins shared with authoring workers (#3941).
use raw_core::pipeline::{
    SavedRemovalAction, SAVED_REMOVAL_EDIT_VERSION, SAVED_REMOVAL_ENTRY_FIELDS,
};
use raw_core::stages::removal_people::PersonRole;
use raw_core::types::removal_models::{
    EXPERIMENTAL_REMOVAL_MODELS, REMOVAL_FRINGE_RADIUS, REMOVAL_HOLE_RADIUS,
    REMOVAL_PERSON_MIN_SCORE,
};

pub fn emit_ts() -> String {
    let mut out = "// Generated by tools/codegen.sh from raw-core experimental pins (#3941).\nexport const EXPERIMENTAL_REMOVAL_MODELS = [\n".to_owned();
    for pin in EXPERIMENTAL_REMOVAL_MODELS {
        out.push_str("  {\n");
        for (key, value) in [
            ("id", pin.id),
            ("file", pin.file),
            ("probe_path", pin.probe_path),
            ("sha256", pin.sha256),
            ("source_revision", pin.source_revision),
            ("checkpoint_sha256", pin.checkpoint_sha256),
            ("license", pin.license),
        ] {
            out.push_str(&crate::support_tiers::ts_string_prop(4, key, value));
        }
        out.push_str(&format!(
            "    size: {},\n    native_side: {},\n    release_qualified: {},\n  }},\n",
            pin.size, pin.native_side, pin.release_qualified
        ));
    }
    out.push_str("] as const;\nexport type RemovalModelId = (typeof EXPERIMENTAL_REMOVAL_MODELS)[number]['id'];\n");
    out.push_str(&format!(
        "export const REMOVAL_AUTHORING_DEFAULTS = {{\n  personMinScore: {REMOVAL_PERSON_MIN_SCORE},\n  holeRadius: {REMOVAL_HOLE_RADIUS},\n  fringeRadius: {REMOVAL_FRINGE_RADIUS},\n}} as const;\n"
    ));
    out.push_str("export const REMOVAL_PERSON_ROLES = {\n");
    for role in PersonRole::ALL {
        out.push_str(&crate::support_tiers::ts_string_prop(
            2,
            role.name(),
            role.label(),
        ));
    }
    out.push_str(
        "} as const;\nexport type RemovalPersonRole = keyof typeof REMOVAL_PERSON_ROLES;\n",
    );
    out.push_str("export interface RemovalPersonSuggestion {\n  detection: import('../removal/removal-inference.types').RemovalDetection;\n  role: RemovalPersonRole;\n  keep: boolean;\n}\n");
    out.push_str(&format!("export const SAVED_REMOVAL_EDIT_VERSION = {SAVED_REMOVAL_EDIT_VERSION};\nexport interface SavedRemovalEntry {{\n"));
    for (field, kind) in SAVED_REMOVAL_ENTRY_FIELDS {
        out.push_str(&format!("  readonly {field}: {kind};\n"));
    }
    out.push_str("}\n");
    emit_saved_actions(&mut out, false);
    out
}

fn swift_number(value: u64) -> String {
    let digits = value.to_string();
    digits
        .chars()
        .enumerate()
        .map(|(index, digit)| {
            if index > 0 && (digits.len() - index) % 3 == 0 {
                format!("_{digit}")
            } else {
                digit.to_string()
            }
        })
        .collect()
}

pub fn emit_swift() -> String {
    let mut out = "// Generated by tools/codegen.sh from raw-core experimental pins (#3941).\n// These models are not release-qualified.\npublic struct ExperimentalRemovalModelPin: Sendable {\n".to_owned();
    for field in [
        "id",
        "file",
        "probePath",
        "sha256",
        "sourceRevision",
        "checkpointSha256",
        "license",
    ] {
        out.push_str(&format!("  public let {field}: String\n"));
    }
    out.push_str("  public let size: UInt64\n  public let nativeSide: UInt32\n  public let releaseQualified: Bool\n}\n\npublic enum ExperimentalRemovalModels {\n");
    out.push_str(&format!(
        "  public static let personMinScore: Float = {REMOVAL_PERSON_MIN_SCORE}\n  public static let holeRadius: UInt32 = {REMOVAL_HOLE_RADIUS}\n  public static let fringeRadius: Float = {REMOVAL_FRINGE_RADIUS}\n"
    ));
    for pin in EXPERIMENTAL_REMOVAL_MODELS {
        out.push_str(&format!(
            "  public static let {} = ExperimentalRemovalModelPin(\n",
            pin.id
        ));
        for (key, value) in [
            ("id", pin.id),
            ("file", pin.file),
            ("probePath", pin.probe_path),
            ("sha256", pin.sha256),
            ("sourceRevision", pin.source_revision),
            ("checkpointSha256", pin.checkpoint_sha256),
            ("license", pin.license),
        ] {
            out.push_str(&format!("    {key}: \"{value}\",\n"));
        }
        out.push_str(&format!(
            "    size: {}, nativeSide: {}, releaseQualified: {}\n  )\n",
            swift_number(pin.size),
            swift_number(u64::from(pin.native_side)),
            pin.release_qualified
        ));
    }
    let names = EXPERIMENTAL_REMOVAL_MODELS.map(|pin| pin.id).join(", ");
    out.push_str(&format!("  public static let all = [{names}]\n}}\n"));
    out.push_str("\npublic enum RemovalPersonRole: String, Decodable, Sendable {\n");
    for role in PersonRole::ALL {
        out.push_str(&format!("  case {}\n", role.name()));
    }
    out.push_str("  public var label: String {\n    switch self {\n");
    for role in PersonRole::ALL {
        out.push_str(&format!(
            "    case .{}: return \"{}\"\n",
            role.name(),
            role.label()
        ));
    }
    out.push_str("    }\n  }\n}\n\npublic struct RemovalPersonSuggestion: Decodable, Sendable {\n  public let detection: NativeRemovalDetection\n  public let role: RemovalPersonRole\n  public let keep: Bool\n}\n");
    out.push_str(&format!("\npublic let savedRemovalEditVersion = {SAVED_REMOVAL_EDIT_VERSION}\npublic struct SavedRemovalEntry: Decodable, Sendable, Identifiable {{\n"));
    for (field, kind) in SAVED_REMOVAL_ENTRY_FIELDS {
        let swift = match *kind {
            "string" => "String",
            "number" => "Int",
            "boolean" => "Bool",
            "number[]" => "[Float]",
            "string | null" => "String?",
            _ => panic!("unknown saved removal field type"),
        };
        out.push_str(&format!("  public let {}: {swift}\n", camel_case(field)));
    }
    out.push_str("  private enum CodingKeys: String, CodingKey {\n");
    for (field, _) in SAVED_REMOVAL_ENTRY_FIELDS {
        out.push_str(&format!("    case {} = \"{field}\"\n", camel_case(field)));
    }
    out.push_str("  }\n}\n");
    emit_saved_actions(&mut out, true);
    out
}

fn emit_saved_actions(out: &mut String, swift: bool) {
    out.push_str(if swift {
        "\npublic enum SavedRemovalAction: String, Encodable, Sendable {\n"
    } else {
        "export const SAVED_REMOVAL_ACTIONS = {\n"
    });
    for action in SavedRemovalAction::ALL {
        let value = serde_json::to_value(action).expect("saved action is serializable");
        let wire = value.as_str().expect("saved action is a string");
        let name = camel_case(wire);
        out.push_str(&if swift {
            format!("  case {name} = \"{wire}\"\n")
        } else {
            format!("  {name}: '{wire}',\n")
        });
    }
    out.push_str(if swift {"}\n"} else {"} as const;\nexport type SavedRemovalAction = (typeof SAVED_REMOVAL_ACTIONS)[keyof typeof SAVED_REMOVAL_ACTIONS];\n"});
}

fn camel_case(wire: &str) -> String {
    let mut words = wire.split(['-', '_']);
    let mut name = words.next().unwrap().to_owned();
    for word in words {
        name.push_str(&word[..1].to_uppercase());
        name.push_str(&word[1..]);
    }
    name
}

#[cfg(test)]
mod tests {
    use super::*;
    #[test]
    fn saved_rows_keep_wire_keys_and_use_valid_swift_names() {
        let swift = emit_swift();
        let ts = emit_ts();
        for (wire, _) in SAVED_REMOVAL_ENTRY_FIELDS {
            assert!(ts.contains(&format!("readonly {wire}:")));
            assert!(swift.contains(&format!("public let {}:", camel_case(wire))));
            assert!(swift.contains(&format!("case {} = \"{wire}\"", camel_case(wire))));
        }
        assert!(swift.contains("case setActive = \"set-active\""));
    }
}
