//! Experimental model pins shared with authoring workers (#3941).
use raw_core::types::removal_models::{
    EXPERIMENTAL_REMOVAL_MODELS, REMOVAL_FRINGE_RADIUS, REMOVAL_HOLE_RADIUS,
    REMOVAL_PERSON_MIN_SCORE,
};

pub fn emit_ts() -> String {
    let mut out = "// Generated by tools/codegen.sh from raw-core experimental pins (#3941).\nexport const EXPERIMENTAL_REMOVAL_MODELS = [\n".to_owned();
    for pin in EXPERIMENTAL_REMOVAL_MODELS {
        out.push_str("  {\n");
        for (key, value) in [
            ("id", pin.id),
            ("file", pin.file),
            ("probe_path", pin.probe_path),
            ("sha256", pin.sha256),
            ("source_revision", pin.source_revision),
            ("checkpoint_sha256", pin.checkpoint_sha256),
            ("license", pin.license),
        ] {
            out.push_str(&crate::support_tiers::ts_string_prop(4, key, value));
        }
        out.push_str(&format!(
            "    size: {},\n    native_side: {},\n    release_qualified: {},\n  }},\n",
            pin.size, pin.native_side, pin.release_qualified
        ));
    }
    out.push_str("] as const;\nexport type RemovalModelId = (typeof EXPERIMENTAL_REMOVAL_MODELS)[number]['id'];\n");
    out.push_str(&format!(
        "export const REMOVAL_AUTHORING_DEFAULTS = {{\n  personMinScore: {REMOVAL_PERSON_MIN_SCORE},\n  holeRadius: {REMOVAL_HOLE_RADIUS},\n  fringeRadius: {REMOVAL_FRINGE_RADIUS},\n}} as const;\n"
    ));
    out
}

fn swift_number(value: u64) -> String {
    let digits = value.to_string();
    digits
        .chars()
        .enumerate()
        .map(|(index, digit)| {
            if index > 0 && (digits.len() - index) % 3 == 0 {
                format!("_{digit}")
            } else {
                digit.to_string()
            }
        })
        .collect()
}

pub fn emit_swift() -> String {
    let mut out = "// Generated by tools/codegen.sh from raw-core experimental pins (#3941).\n// These models are not release-qualified.\npublic struct ExperimentalRemovalModelPin: Sendable {\n".to_owned();
    for field in [
        "id",
        "file",
        "probePath",
        "sha256",
        "sourceRevision",
        "checkpointSha256",
        "license",
    ] {
        out.push_str(&format!("  public let {field}: String\n"));
    }
    out.push_str("  public let size: UInt64\n  public let nativeSide: UInt32\n  public let releaseQualified: Bool\n}\n\npublic enum ExperimentalRemovalModels {\n");
    out.push_str(&format!(
        "  public static let personMinScore: Float = {REMOVAL_PERSON_MIN_SCORE}\n  public static let holeRadius: UInt32 = {REMOVAL_HOLE_RADIUS}\n  public static let fringeRadius: Float = {REMOVAL_FRINGE_RADIUS}\n"
    ));
    for pin in EXPERIMENTAL_REMOVAL_MODELS {
        out.push_str(&format!(
            "  public static let {} = ExperimentalRemovalModelPin(\n",
            pin.id
        ));
        for (key, value) in [
            ("id", pin.id),
            ("file", pin.file),
            ("probePath", pin.probe_path),
            ("sha256", pin.sha256),
            ("sourceRevision", pin.source_revision),
            ("checkpointSha256", pin.checkpoint_sha256),
            ("license", pin.license),
        ] {
            out.push_str(&format!("    {key}: \"{value}\",\n"));
        }
        out.push_str(&format!(
            "    size: {}, nativeSide: {}, releaseQualified: {}\n  )\n",
            swift_number(pin.size),
            swift_number(u64::from(pin.native_side)),
            pin.release_qualified
        ));
    }
    let names = EXPERIMENTAL_REMOVAL_MODELS.map(|pin| pin.id).join(", ");
    out.push_str(&format!("  public static let all = [{names}]\n}}\n"));
    out
}
