//! Windows graticule directions derived from the actual scope producer.
//! UI code interpolates the ring geometrically, without a mirrored matrix.
pub fn emit_cs() -> String {
    let mut out = String::from(
        "// Generated by codegen --schema scope-targets. Do not edit.\n\nnamespace Maple.UI;\n\ninternal static class ScopeTargets\n{\n    internal readonly record struct Target(double R, double G, double B, double Cb, double Cr);\n    internal static readonly Target[] Values =\n    [\n",
    );
    for rgb in [
        [1.0, 0.0, 0.0],
        [1.0, 1.0, 0.0],
        [0.0, 1.0, 0.0],
        [0.0, 1.0, 1.0],
        [0.0, 0.0, 1.0],
        [1.0, 0.0, 1.0],
    ] {
        let (cb, cr) = raw_core::scope::cb_cr_rec709(rgb);
        out.push_str(&format!(
            "        new({:.1}, {:.1}, {:.1}, {:.9}, {:.9}),\n",
            rgb[0], rgb[1], rgb[2], cb, cr
        ));
    }
    out.push_str("    ];\n}\n");
    out
}
