//! The camera / lens support summaries (#2440): the human-readable
//! `docs/camera-support.md` and the machine-readable
//! `docs/camera-support.json`.
//!
//! Both are derived from the same `SupportRegistry::compute` pass the Swift
//! and TypeScript consumers in `support_tiers.rs` use, so the four never
//! disagree about a body's tier or why it holds it. Markdown is headings +
//! lists only (no tables) and JSON is printed by the shared
//! prettier-shaped printer, so both files are stable under the repo's
//! `prettier --check` gate without a formatting pass.
//!
//! The JSON summary is also the only output that carries the full bundled
//! model list — ~1,400 bodies that are `profiled` by construction, which
//! would be dead weight in two app bundles but is exactly what answers
//! "does Maple know my camera".

use raw_core::capability_registry::Evidence;
use raw_core::support_tiers::{
    BodyClassification, CameraTier, LensSupport, SupportRegistry, SUPPORT_TIER_SCHEMA_VERSION,
};

use crate::capability_summary::{json_string, md_findings, print_json, strs, J};
use crate::support_tiers::fallback_rows;

// -------------------------------------------------------------------------
// Markdown
// -------------------------------------------------------------------------

pub(crate) fn emit_md(registry: &SupportRegistry, evidence: &Evidence) -> String {
    let build = evidence.build.expect("evidence carries a build identity");
    let count = |tier: CameraTier| registry.at_tier(tier).len();
    let mut s = String::new();
    s.push_str("# Camera and lens support\n\n");
    s.push_str("<!-- THIS FILE IS GENERATED BY tools/codegen.sh. DO NOT EDIT. -->\n\n");
    s.push_str(
        "Generated from `src/raw-pipeline/raw-core/src/support_tiers/` (the fixture corpus, reviewed Rust), the bundled profile index, and the harness evidence records under `test-fixtures/qualification/`, by `codegen --schema support-tiers --target md` (ticket #2440). The `codegen-drift` CI job regenerates this file on every push; a hand edit fails that gate.\n\n",
    );
    s.push_str(
        "A tier is computed, never asserted. The four lower tiers follow the profile resolver's own fallback order; `qualified` additionally requires every declared qualification suite to be satisfied on the current build, so losing a record demotes a body in the next build rather than leaving a stale claim standing.\n\n",
    );
    s.push_str("## Build\n\n");
    s.push_str(&format!(
        "- Tier schema version: {SUPPORT_TIER_SCHEMA_VERSION}\n"
    ));
    s.push_str(&format!(
        "- Pipeline output version: {}\n",
        build.pipeline_version
    ));
    s.push_str(&format!(
        "- Sidecar schema version: {}\n",
        build.schema_version
    ));
    s.push_str(&format!(
        "- Bundled camera models: {}\n",
        registry.bundled_models.len()
    ));
    s.push_str(&format!(
        "- Fixtured bodies: {} ({} qualified, {} profiled, {} matrix-only, {} decode-only, {} unsupported)\n\n",
        registry.bodies.len(),
        count(CameraTier::Qualified),
        count(CameraTier::Profiled),
        count(CameraTier::MatrixOnly),
        count(CameraTier::DecodeOnly),
        count(CameraTier::Unsupported),
    ));

    s.push_str("## Tiers\n\n");
    for tier in CameraTier::ALL.iter().rev() {
        s.push_str(&format!("### `{}` — {}\n\n", tier.id(), tier.label()));
        s.push_str(&format!("{}\n\n", tier.explanation()));
    }

    s.push_str("## Lens support\n\n");
    s.push_str(
        "A separate axis: lens correction never follows from the camera tier. Maple maintains no lens profile database, so the only source is the correction the camera writes into the file.\n\n",
    );
    for lens in LensSupport::ALL {
        s.push_str(&format!("### `{}` — {}\n\n", lens.id(), lens.label()));
        s.push_str(&format!("{}\n\n", lens.explanation()));
    }

    s.push_str("## Profile fallback order\n\n");
    s.push_str(
        "The order `color::dcp::profile_for_with_source` tries its branches, best evidence first, and the tier each one earns.\n\n",
    );
    for (resolution, tier) in fallback_rows() {
        s.push_str(&format!("- `{resolution}` → `{tier}`\n"));
    }
    s.push('\n');

    s.push_str("## Fixtured bodies\n\n");
    s.push_str(
        "Every camera Maple holds a physical file for. No other body can reach `qualified`, because no other body has anything to measure.\n\n",
    );
    for body in &registry.bodies {
        s.push_str(&format!("### {}\n\n", body.display_name));
        s.push_str(&format!("- Tier: **{}**\n", body.tier.id()));
        s.push_str(&format!("- Lookup key: `{}`\n", body.key));
        s.push_str(&format!("- Fixture: `{}`\n", body.fixture));
        s.push_str(&format!(
            "- Profile resolution: `{}`\n",
            body.resolution.id()
        ));
        s.push_str(&format!("- Lens: `{}`\n", body.lens.id()));
        s.push_str(&md_findings("Qualification evidence", &body.findings));
        s.push('\n');
    }

    s.push_str("## Bundled bodies\n\n");
    s.push_str(&format!(
        "The bundled profile table covers {} camera models beyond the fixture set. Each resolves to real calibration data, so each is at least `profiled` — and none is `qualified`, because Maple has no physical sample to measure. The full list is in `docs/camera-support.json`.\n",
        registry.bundled_models.len()
    ));
    s
}

// -------------------------------------------------------------------------
// JSON
// -------------------------------------------------------------------------

fn body_json(body: &BodyClassification) -> J {
    J::Obj(vec![
        ("key", J::Str(body.key.to_owned())),
        ("display_name", J::Str(body.display_name.to_owned())),
        ("fixture", J::Str(body.fixture.to_owned())),
        ("tier", J::Str(body.tier.id().to_owned())),
        ("lens", J::Str(body.lens.id().to_owned())),
        (
            "profile_resolution",
            J::Str(body.resolution.id().to_owned()),
        ),
        (
            "qualification",
            J::Arr(
                body.findings
                    .iter()
                    .map(|f| {
                        J::Obj(vec![
                            ("source", J::Str(f.source.id().to_owned())),
                            ("status", J::Str(f.status.id().to_owned())),
                            ("detail", J::Str(f.status.describe())),
                        ])
                    })
                    .collect(),
            ),
        ),
    ])
}

pub(crate) fn emit_json(registry: &SupportRegistry, evidence: &Evidence) -> String {
    let build = evidence.build.expect("evidence carries a build identity");
    let tiers = CameraTier::ALL
        .iter()
        .map(|t| {
            J::Obj(vec![
                ("id", J::Str(t.id().to_owned())),
                ("label", J::Str(t.label().to_owned())),
                ("explanation", J::Str(t.explanation().to_owned())),
                (
                    "count",
                    J::Num(registry.at_tier(*t).len().try_into().unwrap_or(0)),
                ),
            ])
        })
        .collect();
    let lens = LensSupport::ALL
        .iter()
        .map(|l| {
            J::Obj(vec![
                ("id", J::Str(l.id().to_owned())),
                ("label", J::Str(l.label().to_owned())),
                ("explanation", J::Str(l.explanation().to_owned())),
            ])
        })
        .collect();
    let fallback = fallback_rows()
        .into_iter()
        .map(|(resolution, tier)| {
            J::Obj(vec![
                ("resolution", J::Str(resolution.to_owned())),
                ("tier", J::Str(tier.to_owned())),
            ])
        })
        .collect();
    let root = J::Obj(vec![
        (
            "generator",
            J::Str("tools/codegen.sh (codegen --schema support-tiers --target json)".into()),
        ),
        (
            "build",
            J::Obj(vec![
                (
                    "tier_schema_version",
                    J::Num(SUPPORT_TIER_SCHEMA_VERSION.into()),
                ),
                (
                    "pipeline_output_version",
                    J::Num(build.pipeline_version.into()),
                ),
                ("schema_version", J::Num(build.schema_version.into())),
            ]),
        ),
        ("tiers", J::Arr(tiers)),
        ("lens_support", J::Arr(lens)),
        ("profile_fallback_order", J::Arr(fallback)),
        (
            "fixtured_bodies",
            J::Arr(registry.bodies.iter().map(body_json).collect()),
        ),
        (
            "bundled_models",
            strs(registry.bundled_models.iter().copied()),
        ),
    ]);
    let mut out = String::new();
    print_json(&root, 0, 0, &mut out);
    out.push('\n');
    out
}

/// Shared fixtures for both support-tier emitter modules' tests.
#[cfg(test)]
pub(crate) mod test_support {
    use super::*;

    pub(crate) fn evidence() -> Evidence {
        Evidence {
            build: Some(raw_core::capability_registry::BuildIdentity::current()),
            ..Evidence::default()
        }
    }

    pub(crate) fn registry() -> SupportRegistry {
        SupportRegistry::compute(&evidence())
    }
}

#[cfg(test)]
mod tests {
    use super::test_support::{evidence, registry};
    use super::*;

    #[test]
    fn md_is_table_free_and_lists_every_body() {
        let out = emit_md(&registry(), &evidence());
        assert!(out.starts_with("# Camera and lens support\n\n<!-- THIS FILE IS GENERATED"));
        for body in &registry().bodies {
            assert!(out.contains(&format!("- Lookup key: `{}`\n", body.key)));
        }
        assert!(
            !out.contains('|'),
            "tables are not prettier-stable; lists only"
        );
    }

    #[test]
    fn json_is_valid_and_carries_the_bundled_models() {
        let out = emit_json(&registry(), &evidence());
        let v: serde_json::Value = serde_json::from_str(&out).expect("valid JSON");
        assert_eq!(
            v["build"]["tier_schema_version"],
            SUPPORT_TIER_SCHEMA_VERSION
        );
        assert_eq!(
            v["fixtured_bodies"].as_array().unwrap().len(),
            registry().bodies.len()
        );
        assert!(v["bundled_models"].as_array().unwrap().len() > 1_000);
        // With no evidence at all, nothing is qualified.
        assert!(v["fixtured_bodies"]
            .as_array()
            .unwrap()
            .iter()
            .all(|b| b["tier"] != "qualified"));
    }

    #[test]
    fn json_string_escapes_the_explanations() {
        for tier in CameraTier::ALL {
            assert!(json_string(tier.explanation()).starts_with('"'));
        }
    }
}
