//! Camera / lens support-tier emitters (#2440).
//!
//! The Swift and TypeScript consumers of
//! `raw_core::support_tiers::SupportRegistry`, computed against the same
//! evidence records the capability registry reads: the tier vocabulary,
//! its user-facing explanations, the resolver mapping, and the
//! fixtured-body table. The human and machine summaries
//! (`docs/camera-support.md` / `.json`) live in `support_tiers_summary.rs`.
//!
//! Only the fixtured bodies are emitted as rows. The ~1,400 bundled bodies
//! are `Profiled` by construction — the bundle entry *is* the calibration —
//! so shipping 1,400 identical rows into two app bundles would buy nothing
//! a `tierForResolution` call does not already give at render time. The
//! full model list is emitted once, into the JSON summary, where "does
//! Maple know my camera" is actually answerable.

use raw_core::capability_registry::Evidence;
use raw_core::support_tiers::{
    tier_for_profile_source, CameraTier, LensSupport, ProfileResolution, SupportRegistry,
    SUPPORT_TIER_SCHEMA_VERSION,
};

use crate::camel_case;

pub(crate) const BANNER: &str = "THIS FILE IS GENERATED BY tools/codegen.sh. DO NOT EDIT.\n\
     Source: src/raw-pipeline/raw-core/src/support_tiers/ (FIXTURED_BODIES,\n\
     the bundled profile index) and the evidence records under\n\
     test-fixtures/qualification/ (#2440).\n\
     \n\
     A camera tier is COMPUTED, never asserted. The four lower tiers are a\n\
     total function of which branch the profile resolver takes; promotion\n\
     to `qualified` additionally needs every declared qualification suite\n\
     satisfied on the current pipeline + schema version, over the current\n\
     corpus, with executed == expected cases and zero failures or skips.\n\
     See docs/camera-support.md.";

fn banner(prefix: &str) -> String {
    BANNER
        .lines()
        .map(|l| {
            if l.is_empty() {
                format!("{prefix}\n")
            } else {
                format!("{prefix} {l}\n")
            }
        })
        .collect()
}

/// `(enum name, cases as (id, label, explanation))`, in one place so the
/// four targets cannot disagree on membership, order or wording.
pub(crate) fn closed_enums() -> Vec<(
    &'static str,
    Vec<(&'static str, &'static str, &'static str)>,
)> {
    vec![
        (
            "CameraTier",
            CameraTier::ALL
                .iter()
                .map(|t| (t.id(), t.label(), t.explanation()))
                .collect(),
        ),
        (
            "LensSupport",
            LensSupport::ALL
                .iter()
                .map(|l| (l.id(), l.label(), l.explanation()))
                .collect(),
        ),
    ]
}

/// The resolver's fallback order as `(resolution id, tier id)` pairs — the
/// versioned, testable fallback order the ticket asks the registry to
/// publish, so a surface can map a render-time resolution to a tier
/// without reimplementing the ladder.
pub(crate) fn fallback_rows() -> Vec<(&'static str, &'static str)> {
    raw_core::support_tiers::PROFILE_FALLBACK_ORDER
        .iter()
        .chain(std::iter::once(&ProfileResolution::DecodeFailed))
        .map(|r| (r.id(), tier_for_profile_source(*r).id()))
        .collect()
}

fn escape_swift(s: &str) -> String {
    s.replace('\\', "\\\\").replace('"', "\\\"")
}

/// A TS string literal shaped the way `prettier --single-quote` prints it:
/// single quotes normally, double quotes when the text contains an
/// apostrophe and no double quote (prettier picks whichever quote needs
/// fewer escapes).
fn ts_string(s: &str) -> String {
    let escaped = s.replace('\\', "\\\\");
    if escaped.contains('\'') && !escaped.contains('"') {
        format!("\"{escaped}\"")
    } else {
        format!("'{}'", escaped.replace('\'', "\\'"))
    }
}

/// A `key: <string>,` property at `indent` spaces, broken the way prettier
/// breaks it: onto a continuation line, indented two further, when the
/// one-line form would pass 100 columns.
fn ts_string_prop(indent: usize, key: &str, value: &str) -> String {
    let pad = " ".repeat(indent);
    let literal = ts_string(value);
    let compact = format!("{pad}{key}: {literal},");
    if compact.len() <= 100 {
        return format!("{compact}\n");
    }
    format!("{pad}{key}:\n{}{literal},\n", " ".repeat(indent + 2))
}

/// A string-literal union, printed the way prettier does: one line when it
/// fits in 100 columns, otherwise one member per line.
fn ts_union(name: &str, members: &[String]) -> String {
    let compact = format!("export type {name} = {};", members.join(" | "));
    if compact.len() <= 100 {
        return format!("{compact}\n");
    }
    let mut s = format!("export type {name} =\n");
    for (i, m) in members.iter().enumerate() {
        let sep = if i + 1 == members.len() { ";" } else { "" };
        s.push_str(&format!("  | {m}{sep}\n"));
    }
    s
}

// -------------------------------------------------------------------------
// Swift
// -------------------------------------------------------------------------

pub(crate) fn emit_swift(registry: &SupportRegistry, evidence: &Evidence) -> String {
    let build = evidence.build.expect("evidence carries a build identity");
    let mut s = banner("//");
    s.push_str("\nimport Foundation\n\n");
    for (name, cases) in closed_enums() {
        s.push_str(&format!(
            "public enum {name}: String, CaseIterable, Sendable {{\n"
        ));
        for (id, _, _) in &cases {
            s.push_str(&format!("    case {} = \"{}\"\n", camel_case(id), id));
        }
        s.push_str("\n    /// Short label for a badge or a list row.\n");
        s.push_str("    public var label: String {\n        switch self {\n");
        for (id, label, _) in &cases {
            s.push_str(&format!(
                "        case .{}: return \"{}\"\n",
                camel_case(id),
                escape_swift(label)
            ));
        }
        s.push_str("        }\n    }\n\n");
        s.push_str("    /// The one fixed sentence this state explains itself with.\n");
        s.push_str("    public var explanation: String {\n        switch self {\n");
        for (id, _, explanation) in &cases {
            s.push_str(&format!(
                "        case .{}:\n            return \"{}\"\n",
                camel_case(id),
                escape_swift(explanation)
            ));
        }
        s.push_str("        }\n    }\n}\n\n");
    }
    s.push_str("/// Which branch of the profile resolver produced a render.\n");
    s.push_str("public enum ProfileResolution: String, CaseIterable, Sendable {\n");
    for (id, _) in fallback_rows() {
        s.push_str(&format!("    case {} = \"{}\"\n", camel_case(id), id));
    }
    s.push_str("}\n\n");
    s.push_str("/// One camera body Maple holds a physical fixture for.\n");
    s.push_str("public struct SupportedCamera: Sendable {\n");
    s.push_str("    public let key: String\n");
    s.push_str("    public let displayName: String\n");
    s.push_str("    public let fixture: String\n");
    s.push_str("    public let tier: CameraTier\n");
    s.push_str("    public let lens: LensSupport\n");
    s.push_str("    public let resolution: ProfileResolution\n");
    s.push_str("}\n\n");
    s.push_str("public enum CameraSupportRegistry {\n");
    s.push_str(&format!(
        "    public static let schemaVersion: UInt32 = {SUPPORT_TIER_SCHEMA_VERSION}\n"
    ));
    s.push_str(&format!(
        "    public static let pipelineOutputVersion: UInt32 = {}\n",
        build.pipeline_version
    ));
    s.push_str(&format!(
        "    /// Camera bodies the bundled profile table covers. Each is at\n\
         \x20   /// least `.profiled`; the full list is in docs/camera-support.json.\n\
         \x20   public static let bundledModelCount: Int = {}\n\
         \x20   /// The profile data every tier here was computed against.\n\
         \x20   public static let profileBundleFormat: UInt16 = {}\n\
         \x20   public static let profileBundleDigest: String = \"{}\"\n\n",
        registry.bundled_models.len(),
        registry.profile_bundle_format,
        registry.profile_bundle_digest,
    ));
    s.push_str("    /// Every body with a physical fixture — the only bodies that can\n");
    s.push_str("    /// ever reach `.qualified`.\n");
    s.push_str("    public static let fixturedBodies: [SupportedCamera] = [\n");
    for body in &registry.bodies {
        s.push_str("        SupportedCamera(\n");
        s.push_str(&format!(
            "            key: \"{}\",\n",
            escape_swift(body.key)
        ));
        s.push_str(&format!(
            "            displayName: \"{}\",\n",
            escape_swift(body.display_name)
        ));
        s.push_str(&format!("            fixture: \"{}\",\n", body.fixture));
        s.push_str(&format!(
            "            tier: .{},\n",
            camel_case(body.tier.id())
        ));
        s.push_str(&format!(
            "            lens: .{},\n",
            camel_case(body.lens.id())
        ));
        s.push_str(&format!(
            "            resolution: .{}\n",
            camel_case(body.resolution.id())
        ));
        s.push_str("        ),\n");
    }
    s.push_str("    ]\n\n");
    s.push_str("    /// The tier a resolver outcome earns before any measured evidence.\n");
    s.push_str("    public static func tier(for resolution: ProfileResolution) -> CameraTier {\n");
    s.push_str("        switch resolution {\n");
    for (resolution, tier) in fallback_rows() {
        s.push_str(&format!(
            "        case .{}: return .{}\n",
            camel_case(resolution),
            camel_case(tier)
        ));
    }
    s.push_str("        }\n    }\n\n");
    s.push_str("    /// The tier for the file in hand. A measured body keeps its\n");
    s.push_str("    /// promotion only when this file resolved at least as well as the\n");
    s.push_str("    /// measured one did.\n");
    s.push_str(
        "    public static func tier(forKey key: String, resolution: ProfileResolution) \
         -> CameraTier {\n",
    );
    s.push_str("        let resolved = tier(for: resolution)\n");
    s.push_str("        guard let body = fixturedBodies.first(where: { $0.key == key }),\n");
    s.push_str("              resolved >= tier(for: body.resolution) else { return resolved }\n");
    s.push_str("        return body.tier\n");
    s.push_str("    }\n}\n\n");
    s.push_str("extension CameraTier: Comparable {\n");
    s.push_str("    /// Worst to best, matching `raw_core::support_tiers::CameraTier`.\n");
    s.push_str("    private var rank: Int { CameraTier.allCases.firstIndex(of: self) ?? 0 }\n");
    s.push_str(
        "    public static func < (lhs: CameraTier, rhs: CameraTier) -> Bool \
         { lhs.rank < rhs.rank }\n",
    );
    s.push_str("}\n");
    s
}

// -------------------------------------------------------------------------
// TypeScript
// -------------------------------------------------------------------------

pub(crate) fn emit_ts(registry: &SupportRegistry, evidence: &Evidence) -> String {
    let build = evidence.build.expect("evidence carries a build identity");
    let mut s = banner("//");
    s.push('\n');
    for (name, cases) in closed_enums() {
        let members: Vec<String> = cases.iter().map(|(id, _, _)| format!("'{id}'")).collect();
        s.push_str(&ts_union(name, &members));
        s.push('\n');
        s.push_str(&format!(
            "export const {}_LABEL: Readonly<Record<{name}, string>> = {{\n",
            screaming(name)
        ));
        for (id, label, _) in &cases {
            s.push_str(&ts_string_prop(2, id, label));
        }
        s.push_str("};\n\n");
        s.push_str(&format!(
            "export const {}_EXPLANATION: Readonly<Record<{name}, string>> = {{\n",
            screaming(name)
        ));
        for (id, _, explanation) in &cases {
            s.push_str(&ts_string_prop(2, id, explanation));
        }
        s.push_str("};\n\n");
    }
    let resolutions: Vec<String> = fallback_rows()
        .iter()
        .map(|(id, _)| format!("'{id}'"))
        .collect();
    s.push_str("/** Which branch of the profile resolver produced a render. */\n");
    s.push_str(&ts_union("ProfileResolution", &resolutions));
    s.push('\n');
    s.push_str("/** The tier a resolver outcome earns before any measured evidence. */\n");
    s.push_str(
        "export const TIER_FOR_RESOLUTION: Readonly<Record<ProfileResolution, CameraTier>> = {\n",
    );
    for (resolution, tier) in fallback_rows() {
        s.push_str(&format!("  {resolution}: '{tier}',\n"));
    }
    s.push_str("};\n\n");
    s.push_str("/** One camera body Maple holds a physical fixture for. */\n");
    s.push_str("export interface SupportedCamera {\n");
    s.push_str("  readonly key: string;\n");
    s.push_str("  readonly displayName: string;\n");
    s.push_str("  readonly fixture: string;\n");
    s.push_str("  readonly tier: CameraTier;\n");
    s.push_str("  readonly lens: LensSupport;\n");
    s.push_str("  readonly resolution: ProfileResolution;\n");
    s.push_str("}\n\n");
    s.push_str("export const CAMERA_SUPPORT_BUILD = {\n");
    s.push_str(&format!(
        "  schemaVersion: {SUPPORT_TIER_SCHEMA_VERSION},\n"
    ));
    s.push_str(&format!(
        "  pipelineOutputVersion: {},\n",
        build.pipeline_version
    ));
    s.push_str(&format!(
        "  bundledModelCount: {},\n",
        registry.bundled_models.len()
    ));
    s.push_str(&format!(
        "  profileBundleFormat: {},\n",
        registry.profile_bundle_format
    ));
    s.push_str(&ts_string_prop(
        2,
        "profileBundleDigest",
        &registry.profile_bundle_digest,
    ));
    s.push_str("} as const;\n\n");
    s.push_str("/**\n");
    s.push_str(" * Every body with a physical fixture — the only bodies that can ever\n");
    s.push_str(" * reach `qualified`.\n");
    s.push_str(" */\n");
    s.push_str("export const FIXTURED_CAMERAS: readonly SupportedCamera[] = [\n");
    for body in &registry.bodies {
        s.push_str("  {\n");
        s.push_str(&ts_string_prop(4, "key", body.key));
        s.push_str(&ts_string_prop(4, "displayName", body.display_name));
        s.push_str(&format!("    fixture: '{}',\n", body.fixture));
        s.push_str(&format!("    tier: '{}',\n", body.tier.id()));
        s.push_str(&format!("    lens: '{}',\n", body.lens.id()));
        s.push_str(&format!("    resolution: '{}',\n", body.resolution.id()));
        s.push_str("  },\n");
    }
    s.push_str("];\n");
    s
}

/// `CameraTier` -> `CAMERA_TIER`.
fn screaming(pascal: &str) -> String {
    let mut out = String::new();
    for (i, ch) in pascal.chars().enumerate() {
        if ch.is_uppercase() && i > 0 {
            out.push('_');
        }
        out.extend(ch.to_uppercase());
    }
    out
}
#[cfg(test)]
mod tests {
    use super::*;
    use crate::support_tiers_summary::test_support::{evidence, registry};

    #[test]
    fn swift_carries_every_tier_and_body() {
        let out = emit_swift(&registry(), &evidence());
        assert!(out.starts_with("// THIS FILE IS GENERATED"));
        for tier in CameraTier::ALL {
            assert!(
                out.contains(&format!("= \"{}\"", tier.id())),
                "{}",
                tier.id()
            );
        }
        for body in &registry().bodies {
            assert!(out.contains(&format!("key: \"{}\"", body.key)));
        }
        assert!(out.contains("public static func tier(for resolution: ProfileResolution)"));
    }

    #[test]
    fn ts_carries_every_tier_and_body() {
        let out = emit_ts(&registry(), &evidence());
        for tier in CameraTier::ALL {
            assert!(out.contains(&format!("  {}: ", tier.id())), "{}", tier.id());
        }
        for body in &registry().bodies {
            assert!(out.contains(&format!("key: '{}'", body.key)));
        }
        assert!(out.contains("CAMERA_TIER_EXPLANATION"));
        assert!(out.contains("LENS_SUPPORT_EXPLANATION"));
    }

    #[test]
    fn ts_strings_switch_quotes_the_way_prettier_does() {
        assert_eq!(ts_string("plain"), "'plain'");
        assert_eq!(ts_string("camera's"), "\"camera's\"");
        assert_eq!(
            ts_string("a \"quoted\" and camera's"),
            "'a \"quoted\" and camera\\'s'"
        );
    }

    #[test]
    fn screaming_case_matches_the_emitted_constant_names() {
        assert_eq!(screaming("CameraTier"), "CAMERA_TIER");
        assert_eq!(screaming("LensSupport"), "LENS_SUPPORT");
    }
}
