//! Codegen for `raw_core::ui_tokens` (ticket #606).
//!
//! Reads `COLOR_TOKENS` + `MOTION_TOKENS` from `raw_core::ui_tokens` and
//! emits the per-platform value sheets that `DesignTokens.swift` /
//! `tokens.ts` / `motion.ts` / `tokens.scss` / `motion.scss` re-export.
//!
//! Driven from `tools/codegen.sh` via the `--schema ui-tokens` flag on the
//! `codegen` binary. Adjustment-schema emission lives in `main.rs`.

use raw_core::ui_tokens::{ColorToken, MotionToken};

use crate::camel_case;

pub const BANNER_UI_SWIFT: &str = "// THIS FILE IS GENERATED BY tools/codegen.sh. DO NOT EDIT.\n\
     // Source: src/raw-pipeline/raw-core/src/ui_tokens.rs (COLOR_TOKENS, MOTION_TOKENS).\n";

pub const BANNER_UI_TS: &str = "// THIS FILE IS GENERATED BY tools/codegen.sh. DO NOT EDIT.\n\
     // Source: src/raw-pipeline/raw-core/src/ui_tokens.rs (COLOR_TOKENS, MOTION_TOKENS).\n";

pub const BANNER_UI_SCSS: &str = "// THIS FILE IS GENERATED BY tools/codegen.sh. DO NOT EDIT.\n\
     // Source: src/raw-pipeline/raw-core/src/ui_tokens.rs (COLOR_TOKENS, MOTION_TOKENS).\n";

/// snake_case -> kebab-case. `surface_alt` -> `surface-alt`.
fn kebab_case(snake: &str) -> String {
    snake.replace('_', "-")
}

/// Render a multi-line doc comment with the given line-prefix (e.g. `/// ` or
/// `// ` or `/** ... */`). Collapses runs of whitespace inside the source
/// doc, then word-wraps lines to a soft maximum so the generated output is
/// readable without a separate formatter pass.
fn doc_lines(doc: &str, prefix: &str, max_cols: usize) -> String {
    let one_line: String = doc.split_whitespace().collect::<Vec<_>>().join(" ");
    let budget = max_cols.saturating_sub(prefix.len()).max(20);
    let mut out = String::new();
    let mut line = String::new();
    for word in one_line.split_whitespace() {
        if line.is_empty() {
            line.push_str(word);
        } else if line.len() + 1 + word.len() > budget {
            out.push_str(prefix);
            out.push_str(&line);
            out.push('\n');
            line.clear();
            line.push_str(word);
        } else {
            line.push(' ');
            line.push_str(word);
        }
    }
    if !line.is_empty() {
        out.push_str(prefix);
        out.push_str(&line);
        out.push('\n');
    }
    out
}

/// Render a doc string as a TypeScript JSDoc comment. Single-line stays
/// `/** ... */`; multi-line uses the block form `/**\n * ...\n */`.
fn jsdoc(doc: &str, indent: &str, max_cols: usize) -> String {
    let one_line: String = doc.split_whitespace().collect::<Vec<_>>().join(" ");
    let budget = max_cols.saturating_sub(indent.len() + 3).max(20); // ` * ` prefix
    let mut wrapped: Vec<String> = Vec::new();
    let mut line = String::new();
    for word in one_line.split_whitespace() {
        if line.is_empty() {
            line.push_str(word);
        } else if line.len() + 1 + word.len() > budget {
            wrapped.push(std::mem::take(&mut line));
            line.push_str(word);
        } else {
            line.push(' ');
            line.push_str(word);
        }
    }
    if !line.is_empty() {
        wrapped.push(line);
    }
    if wrapped.len() <= 1 {
        format!(
            "{}/** {} */\n",
            indent,
            wrapped.first().map(String::as_str).unwrap_or("")
        )
    } else {
        let mut out = String::new();
        out.push_str(indent);
        out.push_str("/**\n");
        for w in &wrapped {
            out.push_str(indent);
            out.push_str(" * ");
            out.push_str(w);
            out.push('\n');
        }
        out.push_str(indent);
        out.push_str(" */\n");
        out
    }
}

pub fn emit_swift(colors: &[ColorToken], motion: &[MotionToken]) -> String {
    let mut s = String::new();
    s.push_str(BANNER_UI_SWIFT);
    s.push_str("//\n");
    s.push_str("// Pure value constants — hex strings, integer milliseconds, CSS easing\n");
    s.push_str("// strings. SwiftUI wrapping (`Color(hex:)`, `Animation.timingCurve(...)`)\n");
    s.push_str("// happens in `DesignTokens.swift`, which re-exports these under the\n");
    s.push_str("// stable `MapleTokens` / `MapleTokens.Motion` API surface.\n\n");
    s.push_str("import Foundation\n\n");

    s.push_str("public enum MapleUITokens {\n");
    s.push_str("    // MARK: - Color hex strings\n\n");
    for tok in colors {
        s.push_str(&doc_lines(tok.doc, "    /// ", 90));
        s.push_str(&format!(
            "    public static let {}: String = \"{}\"\n",
            camel_case(tok.name),
            tok.value,
        ));
    }
    s.push_str("\n    // MARK: - Motion\n\n");
    s.push_str("    /// Motion-token duration + easing pair. `ms` is integer milliseconds;\n");
    s.push_str("    /// `ease` is a CSS easing-function string. SwiftUI consumers translate\n");
    s.push_str("    /// these at the call site.\n");
    s.push_str("    public struct MotionSpec: Sendable, Hashable {\n");
    s.push_str("        public let ms: UInt32\n");
    s.push_str("        public let ease: String\n");
    s.push_str("        public init(ms: UInt32, ease: String) {\n");
    s.push_str("            self.ms = ms\n");
    s.push_str("            self.ease = ease\n");
    s.push_str("        }\n");
    s.push_str("        /// Seconds, as a `Double` — convenient for `Animation` constructors.\n");
    s.push_str("        public var seconds: Double { Double(ms) / 1000.0 }\n");
    s.push_str("    }\n\n");
    s.push_str("    public enum Motion {\n");
    for tok in motion {
        s.push_str(&doc_lines(tok.doc, "        /// ", 90));
        s.push_str(&format!(
            "        public static let {}: MotionSpec = MotionSpec(ms: {}, ease: \"{}\")\n",
            camel_case(tok.name),
            tok.ms,
            tok.ease,
        ));
    }
    s.push_str("    }\n");
    s.push_str("}\n");
    s
}

pub fn emit_ts(colors: &[ColorToken], motion: &[MotionToken]) -> String {
    let mut s = String::new();
    s.push_str(BANNER_UI_TS);
    s.push_str("//\n");
    s.push_str("// Pure value constants — hex strings, integer milliseconds, CSS easing\n");
    s.push_str("// strings. The `MapleTokens` and `MapleMotion` shapes used by app code\n");
    s.push_str("// live in `tokens.ts` and `motion.ts`, which re-export these under the\n");
    s.push_str("// stable public-api surface.\n\n");

    s.push_str("export const MAPLE_UI_COLORS = {\n");
    for tok in colors {
        s.push_str(&jsdoc(tok.doc, "  ", 96));
        s.push_str(&format!("  {}: '{}',\n", camel_case(tok.name), tok.value));
    }
    s.push_str("} as const;\n\n");

    s.push_str("export type MapleUIColorKey = keyof typeof MAPLE_UI_COLORS;\n\n");

    s.push_str("/** Motion-token duration + easing pair. */\n");
    s.push_str("export interface MapleMotionSpec {\n");
    s.push_str("  /** Duration in milliseconds. */\n");
    s.push_str("  readonly ms: number;\n");
    s.push_str("  /** CSS easing-function string. */\n");
    s.push_str("  readonly ease: string;\n");
    s.push_str("}\n\n");

    s.push_str("export const MAPLE_UI_MOTION = {\n");
    for tok in motion {
        s.push_str(&jsdoc(tok.doc, "  ", 96));
        s.push_str(&format!(
            "  {}: {{ ms: {}, ease: '{}' }} as const,\n",
            camel_case(tok.name),
            tok.ms,
            tok.ease,
        ));
    }
    s.push_str("} as const;\n\n");

    s.push_str("export type MapleUIMotionKey = keyof typeof MAPLE_UI_MOTION;\n");
    s
}

pub fn emit_scss(colors: &[ColorToken], motion: &[MotionToken]) -> String {
    let mut s = String::new();
    s.push_str(BANNER_UI_SCSS);
    s.push_str("//\n");
    s.push_str("// Raw token map — consumed by `tokens.scss` (which declares the Tailwind\n");
    s.push_str("// `@theme` block and the SCSS `$color-*` aliases) and `motion.scss`\n");
    s.push_str("// (which declares the `--motion-*` custom properties and `$motion-*`\n");
    s.push_str("// aliases). This file emits a SCSS map plus SCSS variables — no\n");
    s.push_str("// Tailwind-specific syntax — so it's safe to import from anywhere.\n\n");

    s.push_str("// -------------------------------------------------------------------------\n");
    s.push_str("// Colors\n");
    s.push_str("// -------------------------------------------------------------------------\n\n");
    for tok in colors {
        s.push_str(&doc_lines(tok.doc, "// ", 90));
        s.push_str(&format!(
            "$maple-color-{}: {};\n",
            kebab_case(tok.name),
            tok.value
        ));
    }
    s.push_str("\n");

    // SCSS map for iteration in tokens.scss.
    s.push_str("$maple-colors: (\n");
    for tok in colors {
        s.push_str(&format!("  '{}': {},\n", kebab_case(tok.name), tok.value));
    }
    s.push_str(");\n\n");

    s.push_str("// -------------------------------------------------------------------------\n");
    s.push_str("// Motion\n");
    s.push_str("// -------------------------------------------------------------------------\n\n");
    for tok in motion {
        s.push_str(&doc_lines(tok.doc, "// ", 90));
        s.push_str(&format!(
            "$maple-motion-{}-ms: {}ms;\n",
            kebab_case(tok.name),
            tok.ms,
        ));
        s.push_str(&format!(
            "$maple-motion-{}-ease: {};\n",
            kebab_case(tok.name),
            tok.ease,
        ));
    }
    s.push_str("\n");

    // SCSS map of motion specs for iteration. Emitted in the multi-line
    // form prettier produces past its print-width threshold so the
    // codegen-drift + format-check gates agree without a post-step through
    // `prettier --write`.
    s.push_str("$maple-motion: (\n");
    for tok in motion {
        s.push_str(&format!("  '{}': (\n", kebab_case(tok.name)));
        s.push_str(&format!("    'ms': {}ms,\n", tok.ms));
        s.push_str(&format!("    'ease': {},\n", tok.ease));
        s.push_str("  ),\n");
    }
    s.push_str(");\n");
    s
}

#[cfg(test)]
mod tests {
    use super::*;
    use raw_core::ui_tokens::{COLOR_TOKENS, MOTION_TOKENS};

    #[test]
    fn kebab_case_basic() {
        assert_eq!(kebab_case("bg"), "bg");
        assert_eq!(kebab_case("surface_alt"), "surface-alt");
        assert_eq!(kebab_case("border_hi"), "border-hi");
        assert_eq!(kebab_case("sheet_present"), "sheet-present");
    }

    #[test]
    fn swift_emits_colors_and_motion() {
        let out = emit_swift(COLOR_TOKENS, MOTION_TOKENS);
        assert!(out.contains("public enum MapleUITokens"));
        assert!(out.contains("public static let bg: String = \"#1c1917\""));
        assert!(out.contains("public static let borderHi: String = \"#5a5552\""));
        assert!(out.contains("public static let warn: String = \"#fbbf24\""));
        assert!(out.contains("public static let bgHover: String = \"rgba(255, 255, 255, 0.06)\""));
        assert!(out.contains("public enum Motion"));
        assert!(out.contains("MotionSpec(ms: 240, ease: \"cubic-bezier(0.22, 1, 0.36, 1)\")"));
        assert!(out.contains("MotionSpec(ms: 120, ease: \"linear\")"));
    }

    #[test]
    fn ts_emits_colors_and_motion() {
        let out = emit_ts(COLOR_TOKENS, MOTION_TOKENS);
        assert!(out.contains("export const MAPLE_UI_COLORS"));
        assert!(out.contains("bg: '#1c1917'"));
        assert!(out.contains("borderHi: '#5a5552'"));
        assert!(out.contains("warn: '#fbbf24'"));
        assert!(out.contains("export const MAPLE_UI_MOTION"));
        assert!(out.contains("drawer: { ms: 240, ease: 'cubic-bezier(0.22, 1, 0.36, 1)' }"));
        assert!(out.contains("filterFade: { ms: 120, ease: 'linear' }"));
    }

    #[test]
    fn scss_emits_colors_and_motion() {
        let out = emit_scss(COLOR_TOKENS, MOTION_TOKENS);
        assert!(out.contains("$maple-color-bg: #1c1917;"));
        assert!(out.contains("$maple-color-border-hi: #5a5552;"));
        assert!(out.contains("$maple-color-warn: #fbbf24;"));
        assert!(out.contains("$maple-colors: ("));
        assert!(out.contains("'bg': #1c1917"));
        // Lowercase hex (prettier normalizes uppercase).
        assert!(out.contains("$maple-color-star: #ef9f27;"));
        // Trailing zero stripped (prettier normalizes `0.10` -> `0.1`).
        assert!(out.contains("$maple-color-bg-active: rgba(255, 255, 255, 0.1);"));
        assert!(out.contains("$maple-motion-drawer-ms: 240ms;"));
        assert!(out.contains("$maple-motion-drawer-ease: cubic-bezier(0.22, 1, 0.36, 1);"));
        assert!(out.contains("$maple-motion: ("));
        // Motion entries use the multi-line form prettier produces past its
        // print-width threshold — keeps `prettier --check` and the codegen
        // drift gate in agreement without a post-write step.
        assert!(out.contains(
            "'drawer': (\n    'ms': 240ms,\n    'ease': cubic-bezier(0.22, 1, 0.36, 1),\n  ),"
        ));
    }

    #[test]
    fn emitters_are_deterministic() {
        let a = emit_swift(COLOR_TOKENS, MOTION_TOKENS);
        let b = emit_swift(COLOR_TOKENS, MOTION_TOKENS);
        assert_eq!(a, b);
        let a = emit_ts(COLOR_TOKENS, MOTION_TOKENS);
        let b = emit_ts(COLOR_TOKENS, MOTION_TOKENS);
        assert_eq!(a, b);
        let a = emit_scss(COLOR_TOKENS, MOTION_TOKENS);
        let b = emit_scss(COLOR_TOKENS, MOTION_TOKENS);
        assert_eq!(a, b);
    }
}
