//! WinUI/XAML emitter for `raw_core::ui_tokens` (ticket #606).
//!
//! Split out of `ui_tokens.rs` (which still holds the Swift/TS/SCSS
//! emitters) to keep that file under the repo's per-file LOC ceiling. See
//! `ui_tokens.rs` for the shared `pascal_case`/`format_px` helpers this
//! module imports.

use raw_core::ui_tokens::{ColorToken, RadiusToken, SpacingToken};

use crate::ui_tokens::{format_px, pascal_case};

/// Convert a CSS color literal (`#rrggbb` or `rgba(r, g, b, a)`) into a WinUI
/// XAML `Color` markup value. Hex passes through unchanged; `rgba(...)`
/// becomes `#aarrggbb` since XAML's `Color` literal has no separate-channel
/// alpha syntax — alpha is the leading hex byte.
fn to_xaml_color(value: &str) -> String {
    if let Some(inner) = value.strip_prefix("rgba(").and_then(|s| s.strip_suffix(')')) {
        let parts: Vec<&str> = inner.split(',').map(|p| p.trim()).collect();
        assert_eq!(parts.len(), 4, "expected rgba(r, g, b, a), got `{value}`");
        let r: u8 = parts[0].parse().expect("r channel");
        let g: u8 = parts[1].parse().expect("g channel");
        let b: u8 = parts[2].parse().expect("b channel");
        let a: f64 = parts[3].parse().expect("alpha channel");
        let a_byte = (a * 255.0).round() as u8;
        format!("#{a_byte:02X}{r:02X}{g:02X}{b:02X}")
    } else {
        value.to_string()
    }
}

pub fn emit_xaml(colors: &[ColorToken], radius: &[RadiusToken], spacing: &[SpacingToken]) -> String {
    let mut s = String::new();
    s.push_str("<!--\n");
    s.push_str("  THIS FILE IS GENERATED BY tools/codegen.sh. DO NOT EDIT.\n");
    s.push_str("  Source: src/raw-pipeline/raw-core/src/ui_tokens.rs\n");
    s.push_str("  (COLOR_TOKENS, RADIUS_TOKENS, SPACING_TOKENS).\n");
    s.push_str("\n");
    s.push_str("  Pure value resources — Color and x:Double. Framework wrapping (brushes are\n");
    s.push_str("  declared directly below since WinUI has no separate \"DesignTokens\" re-export\n");
    s.push_str("  layer the way Swift/CSS do) happens in this file only for colors, which need a\n");
    s.push_str("  SolidColorBrush to be usable as a Background/Foreground value.\n");
    s.push_str("-->\n");
    s.push_str("<ResourceDictionary\n");
    s.push_str("    xmlns=\"http://schemas.microsoft.com/winfx/2006/xaml/presentation\"\n");
    s.push_str("    xmlns:x=\"http://schemas.microsoft.com/winfx/2006/xaml\">\n\n");

    for tok in colors {
        let key = pascal_case(tok.name);
        s.push_str(&format!(
            "    <Color x:Key=\"Maple{key}Color\">{}</Color>\n",
            to_xaml_color(tok.value)
        ));
    }
    s.push_str("\n");
    for tok in colors {
        let key = pascal_case(tok.name);
        s.push_str(&format!(
            "    <SolidColorBrush x:Key=\"Maple{key}\" Color=\"{{StaticResource Maple{key}Color}}\" />\n"
        ));
    }

    s.push_str("\n    <!-- Radius (px) — wrap at the call site, e.g. `new CornerRadius((double)\n");
    s.push_str("         Resources[\"MapleRadiusMd\"])`. -->\n");
    for tok in radius {
        s.push_str(&format!(
            "    <x:Double x:Key=\"MapleRadius{}\">{}</x:Double>\n",
            pascal_case(tok.name),
            format_px(tok.px)
        ));
    }

    s.push_str("\n    <!-- Spacing (px) — wrap at the call site, e.g. `new Thickness((double)\n");
    s.push_str("         Resources[\"MapleSpacingMd\"])`. -->\n");
    for tok in spacing {
        s.push_str(&format!(
            "    <x:Double x:Key=\"MapleSpacing{}\">{}</x:Double>\n",
            pascal_case(tok.name),
            tok.px
        ));
    }

    s.push_str("\n</ResourceDictionary>\n");
    s
}

#[cfg(test)]
mod tests {
    use super::*;
    use raw_core::ui_tokens::{COLOR_TOKENS, RADIUS_TOKENS, SPACING_TOKENS};

    #[test]
    fn xaml_emits_colors_radius_and_spacing() {
        let out = emit_xaml(COLOR_TOKENS, RADIUS_TOKENS, SPACING_TOKENS);
        assert!(out.contains("<ResourceDictionary"));
        assert!(out.contains(r#"<Color x:Key="MapleBgColor">#1c1917</Color>"#));
        assert!(out.contains(r#"<SolidColorBrush x:Key="MapleBg" Color="{StaticResource MapleBgColor}" />"#));
        // rgba tokens convert to WinUI's #AARRGGBB Color literal.
        assert!(out.contains(r#"<Color x:Key="MapleBgHoverColor">#0FFFFFFF</Color>"#));
        assert!(out.contains(r#"<Color x:Key="MapleBgActiveColor">#1AFFFFFF</Color>"#));
        assert!(out.contains(r#"<Color x:Key="MapleSuccessBgColor">#2622C55E</Color>"#));
        assert!(out.contains(r#"<Color x:Key="MapleErrorBgColor">#26EF4444</Color>"#));
        assert!(out.contains(r#"<x:Double x:Key="MapleRadiusMd">8</x:Double>"#));
        assert!(out.contains(r#"<x:Double x:Key="MapleRadiusFull">9999</x:Double>"#));
        assert!(out.contains(r#"<x:Double x:Key="MapleSpacingXs">4</x:Double>"#));
        assert!(out.contains(r#"<x:Double x:Key="MapleSpacingXxl">48</x:Double>"#));
    }

    #[test]
    fn to_xaml_color_converts_rgba_to_argb_hex() {
        assert_eq!(to_xaml_color("#1c1917"), "#1c1917");
        assert_eq!(to_xaml_color("rgba(255, 255, 255, 0.06)"), "#0FFFFFFF");
        assert_eq!(to_xaml_color("rgba(255, 255, 255, 0.1)"), "#1AFFFFFF");
        assert_eq!(to_xaml_color("rgba(34, 197, 94, 0.15)"), "#2622C55E");
        assert_eq!(to_xaml_color("rgba(239, 68, 68, 0.15)"), "#26EF4444");
    }

    #[test]
    fn xaml_is_deterministic() {
        let a = emit_xaml(COLOR_TOKENS, RADIUS_TOKENS, SPACING_TOKENS);
        let b = emit_xaml(COLOR_TOKENS, RADIUS_TOKENS, SPACING_TOKENS);
        assert_eq!(a, b);
    }
}
