//! Picker vocabulary and values from the same named-preset resolver as XMP.
use raw_core::stages::auto_adjustments::AUTO_WB_ALGORITHM_VERSION;
use raw_core::types::adjustment::WhiteBalancePreset;

fn swift_case(preset: WhiteBalancePreset) -> String {
    let compact = preset.name().replace(' ', "");
    format!("{}{}", compact[..1].to_lowercase(), &compact[1..])
}

pub fn emit_swift() -> String {
    let mut out =
        String::from("// Generated by codegen --schema white-balance-presets. Do not edit.\n\n");
    out.push_str("public enum WhiteBalancePreset: String, CaseIterable, Codable, Sendable {\n");
    for preset in WhiteBalancePreset::ALL {
        out.push_str(&format!(
            "  case {} = \"{}\"\n",
            swift_case(preset),
            preset.name()
        ));
    }
    out.push_str(
        "\n  public var pair: (temperature: Double, tint: Double)? {\n    switch self {\n",
    );
    for preset in WhiteBalancePreset::ALL {
        if let Some((temperature, tint)) = preset.pair() {
            out.push_str(&format!(
                "    case .{}: return ({temperature:.1}, {tint:.1})\n",
                swift_case(preset)
            ));
        }
    }
    out.push_str("    default: return nil\n    }\n  }\n}\n\n");
    out.push_str(&format!(
        "public let autoWhiteBalanceAlgorithmVersion: Double = {AUTO_WB_ALGORITHM_VERSION}.0\n"
    ));
    out
}

pub fn emit_ts() -> String {
    let mut out =
        String::from("// Generated by codegen --schema white-balance-presets. Do not edit.\n\n");
    out.push_str("export const WHITE_BALANCE_PRESETS = [\n");
    for preset in WhiteBalancePreset::ALL {
        out.push_str(&format!("  '{}',\n", preset.name()));
    }
    out.push_str("] as const;\n");
    out.push_str("export type WhiteBalancePreset = (typeof WHITE_BALANCE_PRESETS)[number];\n\n");
    out.push_str("export const WHITE_BALANCE_PRESET_VALUES: Readonly<\n  Partial<Record<WhiteBalancePreset, { temperature: number; tint: number }>>\n> = {\n");
    for preset in WhiteBalancePreset::ALL {
        if let Some((temperature, tint)) = preset.pair() {
            out.push_str(&format!(
                "  {}: {{ temperature: {temperature}, tint: {tint} }},\n",
                preset.name()
            ));
        }
    }
    out.push_str("};\n\n");
    out.push_str(&format!(
        "export const AUTO_WB_ALGORITHM_VERSION = {AUTO_WB_ALGORITHM_VERSION};\n"
    ));
    out
}

/// `As Shot` → `AsShot`: the names are already title-cased words, so the
/// C# identifier is the name with its spaces removed.
fn cs_ident(preset: WhiteBalancePreset) -> String {
    preset.name().replace(' ', "")
}

/// The WinUI shell's copy (#2434): the `crs:WhiteBalance` vocabulary its
/// sidecar reader validates against, the pair a named illuminant resolves
/// to on read, and the AUTO derivation version it stamps — so Windows
/// carries no hand-typed twin of any of the three.
pub fn emit_cs() -> String {
    let mut out = String::from(
        "// Generated by codegen --schema white-balance-presets. Do not edit.\n#nullable enable\n\nnamespace Maple.WinUI.Generated;\n\n",
    );
    out.push_str("/// <summary>Named XMP illuminants (<c>crs:WhiteBalance</c>) and the AUTO\n/// white-balance derivation version, single-sourced from raw-core (#3307).</summary>\npublic static class WhiteBalancePresets\n{\n");
    for preset in WhiteBalancePreset::ALL {
        out.push_str(&format!(
            "    public const string {} = \"{}\";\n",
            cs_ident(preset),
            preset.name()
        ));
    }
    out.push_str("\n    public static readonly string[] Names =\n    {\n");
    for preset in WhiteBalancePreset::ALL {
        out.push_str(&format!("        {},\n", cs_ident(preset)));
    }
    out.push_str("    };\n\n");
    out.push_str("    /// <summary>The slider pair a named illuminant resolves to on read;\n    /// null for the names that carry no pair (As Shot, Auto, Custom).</summary>\n");
    out.push_str(
        "    public static (double Temperature, double Tint)? Pair(string name) => name switch\n    {\n",
    );
    for preset in WhiteBalancePreset::ALL {
        if let Some((temperature, tint)) = preset.pair() {
            out.push_str(&format!(
                "        {} => ({temperature:.1}, {tint:.1}),\n",
                cs_ident(preset)
            ));
        }
    }
    out.push_str("        _ => null,\n    };\n\n");
    out.push_str(&format!(
        "    public const double AutoWhiteBalanceAlgorithmVersion = {AUTO_WB_ALGORITHM_VERSION}.0;\n}}\n"
    ));
    out
}
