//! Workflow DTO fields and constants come from raw-core (#4035/#2437).
use raw_core::workflow::{
    WireKind, HISTORY_LIMIT, MAX_TIMESTAMP_MS, PRIMARY_VARIANT_ID, WORKFLOW_ACTIONS,
    WORKFLOW_MARKUP_PATTERN, WORKFLOW_MAX_BYTES, WORKFLOW_RECORDS, WORKFLOW_UUID_PATTERN,
    WORKFLOW_VERSION,
};

const HEADER: &str = "// Generated by codegen --schema workflow. Do not edit.\n// Storage stage #4035/#2437: raw-core validates checkpoint XML before persistence.\n";

pub fn emit_ts() -> String {
    let mut out = format!("{HEADER}export const WORKFLOW_VERSION = {WORKFLOW_VERSION};\nexport const WORKFLOW_HISTORY_LIMIT = {HISTORY_LIMIT};\nexport const WORKFLOW_MAX_BYTES = {WORKFLOW_MAX_BYTES};\nexport const PRIMARY_VARIANT_ID = '{PRIMARY_VARIANT_ID}';\nexport const WORKFLOW_MAX_TIMESTAMP_MS = {MAX_TIMESTAMP_MS};\n");
    let pattern = serde_json::to_string(WORKFLOW_MARKUP_PATTERN).unwrap();
    out.push_str(&format!(
        "export const WORKFLOW_MARKUP_PATTERN = '{}';\n",
        &pattern[1..pattern.len() - 1]
    ));
    out.push_str(&format!(
        "export const WORKFLOW_UUID_PATTERN = '{WORKFLOW_UUID_PATTERN}';\n"
    ));
    out.push_str("export const WORKFLOW_ACTIONS = [\n");
    for action in WORKFLOW_ACTIONS {
        out.push_str(&format!("  '{action}',\n"));
    }
    out.push_str("] as const;\n\n");
    for record in WORKFLOW_RECORDS {
        out.push_str(&format!("export interface {} {{\n", record.name));
        for field in record.fields {
            let ty = match field.kind {
                WireKind::Text => "string".into(),
                WireKind::U32 | WireKind::U64 => "number".into(),
                WireKind::List(record) => format!("readonly {record}[]"),
            };
            out.push_str(&format!("  readonly {}: {};\n", field.name, ty));
        }
        out.push_str("}\n\n");
    }
    out.push_str("const WORKFLOW_FIELDS: Record<string, Record<string, string>> = {\n");
    for record in WORKFLOW_RECORDS {
        out.push_str(&format!("  {}: {{\n", record.name));
        for field in record.fields {
            let kind: String = match field.kind {
                WireKind::Text => "string".into(),
                WireKind::U32 => "u32".into(),
                WireKind::U64 => "u64".into(),
                WireKind::List(record) => record.into(),
            };
            out.push_str(&format!("    {}: '{}',\n", field.name, kind));
        }
        out.push_str("  },\n");
    }
    out.push_str("};\n");
    out.push_str(include_str!("workflow_validation.ts"));
    out
}

pub fn emit_swift() -> String {
    let timestamp = MAX_TIMESTAMP_MS.to_string();
    let groups: Vec<_> = timestamp
        .as_bytes()
        .rchunks(3)
        .map(|bytes| std::str::from_utf8(bytes).unwrap())
        .collect();
    let timestamp = groups.into_iter().rev().collect::<Vec<_>>().join("_");
    let actions = WORKFLOW_ACTIONS
        .iter()
        .map(|value| format!("    \"{value}\",\n"))
        .collect::<String>();
    let pattern = WORKFLOW_MARKUP_PATTERN.replace('\\', "\\\\");
    let mut out = format!("{HEADER}import Foundation\n\npublic enum WorkflowContract {{\n  public static let version: UInt32 = {WORKFLOW_VERSION}\n  public static let historyLimit = {HISTORY_LIMIT}\n  public static let maxTimestampMS: UInt64 = {timestamp}\n  public static let maxBytes = {WORKFLOW_MAX_BYTES}\n  public static let primaryVariantID = \"{PRIMARY_VARIANT_ID}\"\n  public static let markupPattern = \"{pattern}\"\n  public static let uuidPattern = \"{WORKFLOW_UUID_PATTERN}\"\n  public static let actions = [\n{actions}  ]\n}}\n\n");
    for record in WORKFLOW_RECORDS {
        out.push_str(&format!(
            "public struct {}: Codable, Equatable, Sendable {{\n",
            record.name
        ));
        let fields: Vec<_> = record
            .fields
            .iter()
            .map(|field| {
                let ty = match field.kind {
                    WireKind::Text => "String".into(),
                    WireKind::U32 => "UInt32".into(),
                    WireKind::U64 => "UInt64".into(),
                    WireKind::List(record) => format!("[{record}]"),
                };
                (field.name, ty)
            })
            .collect();
        for (name, ty) in &fields {
            out.push_str(&format!("  public let {name}: {ty}\n"));
        }
        let args = fields
            .iter()
            .map(|(name, ty)| format!("    {name}: {ty}"))
            .collect::<Vec<_>>()
            .join(",\n");
        out.push_str(&format!("\n  public init(\n{args}\n  ) {{\n"));
        for (name, _) in &fields {
            out.push_str(&format!("    self.{name} = {name}\n"));
        }
        out.push_str("  }\n\n");
        out.push_str("  enum CodingKeys: String, CodingKey, CaseIterable {\n");
        for (name, _) in &fields {
            out.push_str(&format!("    case {name}\n"));
        }
        out.push_str("  }\n\n  public init(from decoder: Decoder) throws {\n    let all = try decoder.container(keyedBy: WorkflowAnyKey.self)\n    guard Set(all.allKeys.map(\\.stringValue)) == Set(CodingKeys.allCases.map(\\.rawValue)) else {\n      throw WorkflowWireError.invalid\n    }\n    let values = try decoder.container(keyedBy: CodingKeys.self)\n");
        for (name, ty) in &fields {
            out.push_str(&format!(
                "    {name} = try values.decode({ty}.self, forKey: .{name})\n"
            ));
        }
        out.push_str("    try validateWire()\n  }\n\n  public func encode(to encoder: Encoder) throws {\n    try validateWire()\n    var values = encoder.container(keyedBy: CodingKeys.self)\n");
        for (name, _) in &fields {
            out.push_str(&format!("    try values.encode({name}, forKey: .{name})\n"));
        }
        out.push_str("  }\n}\n\n");
    }
    out.push_str(include_str!("workflow_validation.swift").trim_start());
    out
}
