import { describe, expect, it, beforeAll, afterAll } from 'bun:test';
import { mkdtemp, rm, writeFile, stat } from 'node:fs/promises';
import * as os from 'node:os';
import * as path from 'node:path';
import sharp from 'sharp';
import { ffmpegBinary, extractVideoPosterJpeg } from './video-poster.ts';

/**
 * Tests for poster-frame extraction (#1649).
 *
 * The cases that need to actually decode video are gated on the host having a
 * runnable ffmpeg and skip-pass without one — the same convention as the
 * fixture-gated color harness (`test_color_pipeline.sh`) and the XCUITest
 * visual harness. CI containers without ffmpeg are exactly the deployment this
 * feature is designed to degrade gracefully on, so "no ffmpeg" must not be a
 * red build.
 *
 * The contract cases below the gate hold on every host and always run.
 */

let dir: string;
/** Resolved once — also the gate for the decode-dependent cases. */
let ffmpeg: string | null = null;
/** A real 2-second 640x360 video, generated by ffmpeg itself. Null when gated
 * out. Generating rather than committing a fixture keeps a binary out of git
 * and guarantees the container matches whatever the host's ffmpeg produces. */
let sampleVideo: string | null = null;

beforeAll(async () => {
  dir = await mkdtemp(path.join(os.tmpdir(), 'maple-video-poster-'));
  ffmpeg = await ffmpegBinary();
  if (!ffmpeg) return;
  sampleVideo = await makeTestVideo(ffmpeg, path.join(dir, 'sample.mp4'), 2);
});

afterAll(async () => {
  await rm(dir, { recursive: true, force: true });
});

/** Synthesize `seconds` of colour-bar video at 640x360. Returns the path, or
 * null if this host's ffmpeg can't produce it (missing encoder) — the caller
 * treats that like an absent ffmpeg. */
async function makeTestVideo(bin: string, out: string, seconds: number): Promise<string | null> {
  const proc = Bun.spawn(
    [
      bin,
      '-hide_banner',
      '-loglevel',
      'error',
      '-f',
      'lavfi',
      '-i',
      `testsrc=duration=${seconds}:size=640x360:rate=10`,
      '-pix_fmt',
      'yuv420p',
      '-y',
      out,
    ],
    { stdout: 'ignore', stderr: 'ignore' },
  );
  return (await proc.exited) === 0 ? out : null;
}

describe('extractVideoPosterJpeg — contract (every host)', () => {
  it('returns false and writes nothing for a file that does not exist', async () => {
    const out = path.join(dir, 'missing-src.jpg');
    expect(await extractVideoPosterJpeg(path.join(dir, 'nope.mov'), out)).toBe(false);
    await expect(stat(out)).rejects.toMatchObject({ code: 'ENOENT' });
  });

  it('returns false and leaves no partial output for bytes that are not a video', async () => {
    // The failure that matters: a zero-byte or truncated output left at the
    // caller's temp path would be handed to the imgdecode pool as if it were a
    // real poster. Assert the path is clean, not merely that we returned false.
    const src = path.join(dir, 'garbage.mov');
    await writeFile(src, Buffer.from('this is definitely not an mp4 container'));
    const out = path.join(dir, 'garbage.jpg');
    expect(await extractVideoPosterJpeg(src, out)).toBe(false);
    await expect(stat(out)).rejects.toMatchObject({ code: 'ENOENT' });
  });
});

describe('extractVideoPosterJpeg — real decode (needs host ffmpeg)', () => {
  it('extracts a decodable JPEG at the source frame size', async () => {
    if (!sampleVideo) return; // gated: no runnable ffmpeg on this host
    const out = path.join(dir, 'poster.jpg');
    expect(await extractVideoPosterJpeg(sampleVideo, out)).toBe(true);

    // Decode-verified, not just "a file exists": the whole point of this
    // artefact is that the downstream imgdecode pool can read it.
    const meta = await sharp(out).metadata();
    expect(meta.format).toBe('jpeg');
    expect(meta.width).toBe(640);
    expect(meta.height).toBe(360);
  });

  it('falls back to the first frame for a clip shorter than the seek offset', async () => {
    if (!ffmpeg) return; // gated
    // The seek is 1s in. A 0.4s clip leaves ffmpeg past EOF, where it exits 0
    // having written nothing — which is why success is judged on output bytes
    // rather than exit code, and why the retry-from-zero path exists. Without
    // it every short clip (the common case for phone videos of a moment) would
    // silently get no poster at all.
    const shortClip = await makeTestVideo(ffmpeg, path.join(dir, 'short.mp4'), 0.4);
    if (!shortClip) return;
    const out = path.join(dir, 'short-poster.jpg');
    expect(await extractVideoPosterJpeg(shortClip, out)).toBe(true);
    expect((await sharp(out).metadata()).format).toBe('jpeg');
  });

  it('overwrites a stale output already at the target path', async () => {
    if (!sampleVideo) return; // gated
    // The caller hands us a temp path it owns; a leftover from a crashed prior
    // run must not be mistaken for this run's poster.
    const out = path.join(dir, 'stale.jpg');
    await writeFile(out, Buffer.from('stale bytes from a previous run'));
    expect(await extractVideoPosterJpeg(sampleVideo, out)).toBe(true);
    expect((await sharp(out).metadata()).format).toBe('jpeg');
  });
});

describe('ffmpegBinary', () => {
  it('memoizes — repeated calls return the identical result without re-probing', async () => {
    const a = await ffmpegBinary();
    const b = await ffmpegBinary();
    expect(a).toBe(b);
  });

  it('resolves to an absolute path or null, never a bare command name', async () => {
    // A bare "ffmpeg" would mean we returned something we never verified is
    // executable — the dangling-dylib case this probe exists to catch.
    const bin = await ffmpegBinary();
    if (bin !== null) expect(path.isAbsolute(bin)).toBe(true);
  });
});
