//! Generated by src/scripts/derive_agx_lut.py — DO NOT EDIT BY HAND.
//!
//! Single-source-of-truth AgX constants. Re-run the derivation script
//! when coefficients change; bump `viewTransformVersion` in
//! RenderedPreviewCache (spec § 05-performance.md) at the same time.

/// AgX log-encode domain: scene values below MID_GRAY * 2^MIN_EV
/// clamp to the toe; values above MID_GRAY * 2^MAX_EV clamp to the
/// shoulder.
pub const AGX_MIN_EV: f32 = -10.0;
pub const AGX_MAX_EV: f32 = 6.5;

/// Scene-linear middle gray — the AgX sigmoid's pivot anchor on the
/// scene-side (used for log-encoding reference).
pub const AGX_MID_GRAY: f32 = 0.18;

/// Display-linear target at the mid-gray anchor. Decoupled from
/// AGX_MID_GRAY so the output can be lifted above the pure
/// scene-referred 0.18 reference to match ACR-style baseline
/// midtone brightness.
pub const AGX_MID_DISPLAY: f32 = 0.18;

/// Blender 4.x AgX_Base default contrast slope.
pub const AGX_BASE_SLOPE: f32 = 2.4;

/// Size of the per-channel sigmoid LUT embedded in agx_lut.bin.
pub const AGX_LUT_SIZE: usize = 512;

/// Cache-invalidation key — every time this file's bytes change
/// (due to coefficient edits or LUT recompute), bump this. It is
/// propagated into RenderedPreviewCache's viewTransformVersion
/// so every cached preview re-renders on the next cold open.
pub const AGX_VERSION: u32 = 3;
