//! Generated by src/scripts/derive_agx_lut.py — DO NOT EDIT BY HAND.
//!
//! Canonical Sobotka AgX constants for the Rust raw-core view
//! transform. The pipeline is:
//!
//! ```text
//!     scene-linear Rec.2020
//!         → AGX_INSET_MATRIX
//!         → per-channel log2 encode + normalize
//!         → ratio-preserving sigmoid: the sigmoid LUT (agx_lut.bin)
//!           is evaluated on max(R,G,B), then RGB is scaled by
//!           sigmoid_norm / norm so hue is invariant (post-#435)
//!         → AGX_OUTSET_MATRIX
//!         → Oklab hue-preserving gamut compression to [0, 1] =
//!           display-linear Rec.2020
//! ```
//!
//! Re-run the derivation script when coefficients change; bump
//! `viewTransformVersion` in RenderedPreviewCache (spec
//! § 05-performance.md) at the same time.

/// AgX log-encode domain: scene values below MID_GRAY * 2^MIN_EV
/// clamp to the toe; values above MID_GRAY * 2^MAX_EV clamp to the
/// shoulder.
pub const AGX_MIN_EV: f32 = -10.0;
pub const AGX_MAX_EV: f32 = 6.5;

/// Scene-linear middle gray — the AgX log-encoding reference point.
pub const AGX_MID_GRAY: f32 = 0.18;

/// Display-linear value at the mid-gray log pivot. With Y_PIVOT
/// set to MID_GRAY (Maple photography-tuned), this is 0.18 exactly:
/// scene 0.18 → display 0.18 along the neutral axis.
pub const AGX_MID_DISPLAY: f32 = 0.18;

/// Jed Smith / Sobotka sigmoid pivot in normalized-log space.
/// `AGX_X_PIVOT = |MIN_EV| / (MAX_EV - MIN_EV)` so the pivot sits
/// exactly at scene-linear mid-gray on the log axis.
pub const AGX_X_PIVOT: f32 = 0.6060606061;

/// Sigmoid pivot in display-linear space. Maple sets this to
/// `AGX_MID_GRAY` to preserve mid-gray through the curve. Sobotka's
/// cinematic default is 0.50.
pub const AGX_Y_PIVOT: f32 = 0.18;

/// Slope at the pivot (Jed Smith `slope_pivot`). Sobotka's AgX-S2O3
/// default is 2.0, but the Jed Smith scale equation requires
/// slope > (1 - Y_PIVOT) / (1 - X_PIVOT) ≈ 2.08 with Y_PIVOT=0.18,
/// so 2.4 is the smallest slope that produces a real sigmoid at
/// the chosen pivot. Photography-tuned.
pub const AGX_BASE_SLOPE: f32 = 2.4;

/// Toe / shoulder powers in the Jed Smith sigmoid (Sobotka
/// AgX-S2O3 defaults: `limits_contrast=[3.0, 3.25]`).
pub const AGX_TOE_POWER: f32 = 3.0;
pub const AGX_SHOULDER_POWER: f32 = 3.25;

/// Size of the per-channel sigmoid LUT embedded in agx_lut.bin.
pub const AGX_LUT_SIZE: usize = 512;

/// Inset matrix: scene-linear Rec.2020 → AgX-Base-Rec.2020. The AgX-Base primaries are constructed by pushing each Rec.2020 primary AWAY from D65 by scale 1/(1-0.20) = 1.25 along the (primary - white) chromaticity ray (the gamut triangle widens by 25%); the resulting Rec.2020 -> AgX-Base RGB->RGB transform is per-channel desaturating on saturated inputs, which is the AgX inset behaviour. Computed by `src/scripts/derive_agx_lut.py::derive_inset_outset()`; construction mirrors `AgX_compressed_matrix(compression=0.20)` in https://github.com/sobotka/AgX-S2O3/blob/main/AgX.py L17-50. Row sums are 1.0 (numerically), so neutral triples pass through the inset unchanged — load-bearing for mid-gray preservation.
#[rustfmt::skip]
pub const AGX_INSET_MATRIX: [[f32; 3]; 3] = [
    [ 8.591975135285663e-01_f32,  5.597524856454414e-02_f32,  8.482723790688949e-02_f32],
    [ 5.919751352856634e-02_f32,  8.559752485645438e-01_f32,  8.482723790688945e-02_f32],
    [ 5.919751352856627e-02_f32,  5.597524856454419e-02_f32,  8.848272379068893e-01_f32],
];

/// Outset matrix: numerical inverse of `AGX_INSET_MATRIX`. Applied after the per-channel sigmoid LUT to map back from AgX-Base-Rec.2020 to scene-linear Rec.2020 primaries (restoring chroma the inset compressed). Row sums are 1.0 — neutrals unchanged.
#[rustfmt::skip]
pub const AGX_OUTSET_MATRIX: [[f32; 3]; 3] = [
    [ 1.176003108089292e+00_f32, -6.996906070568021e-02_f32, -1.060340473836119e-01_f32],
    [-7.399689191070798e-02_f32,  1.180030939294320e+00_f32, -1.060340473836119e-01_f32],
    [-7.399689191070784e-02_f32, -6.996906070568031e-02_f32,  1.143965952616388e+00_f32],
];

/// Cache-invalidation key — every time this file's bytes change
/// (due to coefficient edits or LUT recompute), bump this. It is
/// propagated into RenderedPreviewCache's viewTransformVersion
/// so every cached preview re-renders on the next cold open.
pub const AGX_VERSION: u32 = 8;
