//! Generated by src/scripts/derive_agx_lut.py — DO NOT EDIT BY HAND.
//!
//! Single-source-of-truth AgX constants. Re-run the derivation script
//! when coefficients change; bump `viewTransformVersion` in
//! RenderedPreviewCache (spec § 05-performance.md) at the same time.

/// AgX log-encode domain: scene values below MID_GRAY * 2^MIN_EV
/// clamp to the toe; values above MID_GRAY * 2^MAX_EV clamp to the
/// shoulder.
pub const AGX_MIN_EV: f32 = -10.0;
pub const AGX_MAX_EV: f32 = 6.5;

/// Scene-linear middle gray — the AgX log-encoding reference point.
pub const AGX_MID_GRAY: f32 = 0.18;

/// Display-linear value at the mid-gray log-pivot (norm = MID_NORM).
/// Computed from the Maple AgX polynomial at norm = (0-MIN_EV)/EV_RANGE.
/// Maple AgX is photography-tuned: this anchor sits near MID_GRAY
/// (~0.18), preserving mid-gray through the curve. Blender 4.x AgX
/// (the prior shape) lifted it to ~0.50 for cinematic look.
pub const AGX_MID_DISPLAY: f32 = 0.237056;

/// Slope-modulation constant. Mirrored across platforms so the
/// contrast slider drives identical behavior in Rust / Metal / WebGL.
pub const AGX_BASE_SLOPE: f32 = 2.4;

/// Size of the per-channel sigmoid LUT embedded in agx_lut.bin.
pub const AGX_LUT_SIZE: usize = 512;

/// Cache-invalidation key — every time this file's bytes change
/// (due to coefficient edits or LUT recompute), bump this. It is
/// propagated into RenderedPreviewCache's viewTransformVersion
/// so every cached preview re-renders on the next cold open.
pub const AGX_VERSION: u32 = 6;
