#!/usr/bin/env python3
"""WGSL emitter for the AgX GPU kernel constants (epic #925 P2 / #990).

Split out of `derive_agx_lut.py` to keep that file under the file-size budget
(tools/check-file-budget.sh; precedent #924). This is a **leaf** module —
stdlib imports only, no back-import of `derive_agx_lut` — so the script run
(`derive_agx_lut.py` as `__main__`) can't hit a partially-initialized circular
import. The AgX constants + `derive_inset_outset()` live in `derive_agx_lut`;
`emit_wgsl` takes them as parameters (named identically to the source globals
so the emitted-body f-strings are byte-for-byte the same as before the split).

The headless GPU AgX kernel (raw-gpu/src/agx.wgsl) bakes the inset/outset
matrices + scalar log-encode constants as WGSL consts, single-sourced from the
SAME coefficients `derive_agx_lut.py` emits to agx_coeffs.rs (the Rust pipeline)
and the GLSL shader. The 512-entry sigmoid LUT itself is NOT baked as a const
here: raw-gpu uploads agx_lut.bin to a storage buffer at runtime
(`include_bytes!`), matching raw-core's `sample_lut` path exactly. So this
emitter only needs the matrices + the log-encode/normalize scalars; the LUT
bytes ride agx_lut.bin (the byte-identity of which is already gated by
`lut_hash_matches_apple_bundle`).

Convention mirrors codegen's color_matrices.wgsl exactly: row-major Matrix3
is emitted as three `const` row `vec3<f32>`s named `<NAME>_R0/_R1/_R2` plus
a `mul_<name>(v)` dot-product helper, so `out[i] = dot(row_i, v)` matches
the Rust `matrix_mul` row-major semantics (a column-major `mat3x3<f32>`
would silently transpose and break parity).
"""
from __future__ import annotations

import struct
from pathlib import Path


def _wgsl_f(v: float) -> str:
    """Format a value as a WGSL `f32` literal that round-trips through f32 and
    always carries an `f` suffix. The value is first rounded to f32 (the
    precision raw-core's `const … f32` literals concretise to), then printed
    with Python's shortest round-tripping `repr` — the float-side analog of
    the Rust emitter's `format!("{v:?}")` on an `f32`."""
    f32v = struct.unpack("<f", struct.pack("<f", v))[0]
    s = repr(f32v)
    if "." not in s and "e" not in s and "E" not in s:
        s = f"{s}.0"
    return f"{s}f"


def _emit_wgsl_matrix(name: str, fn_name: str, doc: str, M: list[list[float]]) -> str:
    rows = "".join(
        f"const {name}_R{i}: vec3<f32> = vec3<f32>("
        f"{_wgsl_f(M[i][0])}, {_wgsl_f(M[i][1])}, {_wgsl_f(M[i][2])});\n"
        for i in range(3)
    )
    helper = (
        f"fn {fn_name}(v: vec3<f32>) -> vec3<f32> {{\n"
        f"    return vec3<f32>(dot({name}_R0, v), dot({name}_R1, v), dot({name}_R2, v));\n"
        f"}}\n"
    )
    return f"// {doc}\n{rows}{helper}\n"


def emit_wgsl(
    path: Path,
    *,
    MIN_EV: float,
    MAX_EV: float,
    MID_GRAY: float,
    EV_RANGE: float,
    LUT_SIZE: int,
    inset: list[list[float]],
    outset: list[list[float]],
    P2W_AMOUNT: float,
    P2W_KNEE: float,
    P2W_POWER: float,
) -> None:
    """AgX constants as a WGSL module for the raw-gpu kernel (epic #925 P2 /
    #990). Inset/outset matrices (row-`vec3` consts + `mul_*` helpers) plus the
    log-encode/normalize scalars. The sigmoid LUT is uploaded at runtime (see
    module docstring above), so it is NOT emitted here.

    Coefficients (`MIN_EV`/`MAX_EV`/`MID_GRAY`/`EV_RANGE`/`LUT_SIZE`) and the
    `inset`/`outset` matrices are passed in by `derive_agx_lut.py` (the single
    source of truth); param names match the source globals so the emitted body
    is byte-identical to the pre-split inline version."""
    mid_norm = (0.0 - MIN_EV) / EV_RANGE

    body = (
        "// THIS FILE IS GENERATED BY tools/codegen.sh. DO NOT EDIT.\n"
        "// Source: src/scripts/derive_agx_lut.py (the SAME coefficients that\n"
        "//   produce agx_coeffs.rs + the GLSL agx-view-transform shader).\n"
        "// The 512-entry sigmoid LUT is NOT baked here — raw-gpu uploads\n"
        "//   agx_lut.bin to a storage buffer at runtime, matching raw-core's\n"
        "//   `sample_lut` path. This module carries only the matrices + the\n"
        "//   log-encode/normalize scalars.\n"
        "\n"
        "// AgX log-encode domain (Sobotka open_domain_to_normalized_log2):\n"
        "// scene below MID_GRAY*2^MIN_EV clamps to the toe, above\n"
        "// MID_GRAY*2^MAX_EV to the shoulder.\n"
        f"const AGX_MIN_EV: f32 = {_wgsl_f(MIN_EV)};\n"
        f"const AGX_MAX_EV: f32 = {_wgsl_f(MAX_EV)};\n"
        "// Scene-linear middle gray — the log-encode reference point.\n"
        f"const AGX_MID_GRAY: f32 = {_wgsl_f(MID_GRAY)};\n"
        "// Normalized-log position of mid-gray; contrast pivots around this.\n"
        f"const AGX_MID_NORM: f32 = {_wgsl_f(mid_norm)};\n"
        "// Sigmoid LUT entry count (linear-interpolated at runtime).\n"
        f"const AGX_LUT_SIZE: u32 = {LUT_SIZE}u;\n"
        "// Highlight path-to-white (#1624): w = AMOUNT * clamp((sn - KNEE) /\n"
        "// (1 - KNEE), 0, 1)^POWER on the sigmoided AgX-Base pixel, rgb += w *\n"
        "// (max - rgb). Mirror of raw_core AGX_P2W_*.\n"
        f"const AGX_P2W_AMOUNT: f32 = {_wgsl_f(P2W_AMOUNT)};\n"
        f"const AGX_P2W_KNEE: f32 = {_wgsl_f(P2W_KNEE)};\n"
        f"const AGX_P2W_POWER: f32 = {_wgsl_f(P2W_POWER)};\n"
        "\n"
        + _emit_wgsl_matrix(
            "AGX_INSET",
            "mul_agx_inset",
            "Inset matrix: scene-linear Rec.2020 -> AgX-Base-Rec.2020 "
            "(per-channel desaturating; row sums 1.0). Mirror of "
            "raw_core AGX_INSET_MATRIX.",
            inset,
        )
        + _emit_wgsl_matrix(
            "AGX_OUTSET",
            "mul_agx_outset",
            "Outset matrix: AgX-Base-Rec.2020 -> Rec.2020 (numerical inverse "
            "of INSET; restores chroma; row sums 1.0). Mirror of "
            "raw_core AGX_OUTSET_MATRIX.",
            outset,
        )
    )
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(body)
