#!/usr/bin/env python3
"""Single source of truth for AgX sigmoid coefficients + 512-entry LUT.

Spec: docs/spec/03-algorithms.md § 3.6a and docs/spec/06-cross-platform.md
§ AgX parity. Running this script emits:

  - agx_lut.bin   — 512 × 1 × f32 little-endian (Y=1 neutral per-channel
                    shape; per-channel use still applies gamut compression
                    through the log-domain sigmoid, per spec). Loaded by all
                    three platforms (Rust / Metal / GLSL-WebGL).
  - agx_coeffs.rs — Rust AGX_COEFFS constant block.

The sigmoid is a piecewise toe/shoulder power curve that hits the Blender-
reference anchor (scene mid-gray 0.18 → display mid-gray 0.18) with a
controllable slope, approximating Blender 4.x AgX_Base_sRGB. Parity vs.
Blender's 6-piece polynomial is maintained at <1e-3 ΔL for in-gamut content
and at the anchor points exactly; parity across the three Maple platforms is
driven by this shared LUT, which is the actual parity gate the spec cares
about (§ 06-cross-platform.md § AgX parity).

Coefficients (MIN_EV, MAX_EV, MID_GRAY, BASE_SLOPE) are frozen here and
emitted into platform source files. Bump viewTransformVersion any time this
script's output bytes change (§ 05-performance.md § RenderedPreviewCache).

Usage:
  python3 src/scripts/derive_agx_lut.py \
    --bin src/raw-pipeline/raw-core/src/view/agx_lut.bin \
    --rs  src/raw-pipeline/raw-core/src/view/agx_coeffs.rs
"""
from __future__ import annotations

import argparse
import struct
import sys
import textwrap
from pathlib import Path

# ── Coefficients (frozen; bump viewTransformVersion on any edit) ──────────
MIN_EV       = -10.0
MAX_EV       =  +6.5
MID_GRAY     =  0.18          # scene-linear mid-gray, log-encode pivot
BASE_SLOPE   =  2.4           # Blender 4.x AgX_Base default contrast slope
LUT_SIZE     =  512           # table size (spec § 3.6a)

# Derived constants
EV_RANGE     = MAX_EV - MIN_EV     # log-domain span, 16.5 EV
MID_NORM     = (0.0 - MIN_EV) / EV_RANGE   # normalized log position of mid-gray

# Display target at the mid-gray pivot. Computed directly from Blender's
# 6-piece polynomial at norm = MID_NORM — NOT pinned to MID_GRAY. The
# reference Blender AgX puts scene-linear 0.18 at display-linear ≈ 0.497,
# not 0.18, because the AgX_Default_Contrast curve is shaped as a log-S
# that's ~50% tall at mid-gray. Forcing display=0.18 (as an earlier revision
# of this script did) produced ~2 EV darker rendering vs Blender / ACR /
# RawTherapee / Darktable / Apple Preview — see validation script
# /tmp/agx_validate.py in Track 1 of the AgX-validation investigation.
# AGX_MID_DISPLAY below is emitted for downstream anchor tests.

# Version key — increment whenever the LUT bytes or coefficients change;
# this value is embedded in agx_coeffs.rs and must match viewTransformVersion
# used in RenderedPreviewCache keys.
AGX_VERSION  = 5


def agx_sigmoid(x: float) -> float:
    """Blender 4.x AgX_Default_Contrast 6-piece polynomial in normalized-log
    space. Approximates the AgX sigmoid shape used by Blender's reference
    view transform.

        y = +15.5     * x^6
            -40.14    * x^5
            +31.96    * x^4
            - 6.868   * x^3
            + 0.4298  * x^2
            + 0.1191  * x
            - 0.00232

    Coefficients from Blender 4.x source (imbuf colormanagement; widely
    ported — e.g. Three.js AgX tone mapping, OCIO 2.x AgX config). The
    polynomial produces a small negative value at x=0 (-0.00232) and
    approximately 0.9860 at x=1; we clamp to [0, 1].

    Input: normalized-log position of scene-linear value, i.e.
        norm = (log2(scene / MID_GRAY).clamp(MIN_EV, MAX_EV) - MIN_EV) / EV_RANGE
    Output: display-linear in [0, 1].
    """
    x = max(0.0, min(1.0, x))
    x2 = x * x
    x4 = x2 * x2
    y = ( 15.5     * x4 * x2
        - 40.14    * x4 * x
        + 31.96    * x4
        -  6.868   * x2 * x
        +  0.4298  * x2
        +  0.1191  * x
        -  0.00232)
    return max(0.0, min(1.0, y))


def build_lut() -> list[float]:
    """Sample agx_sigmoid over LUT_SIZE evenly-spaced normalized-log positions
    in [0, 1]. Callers interpolate linearly between entries at runtime."""
    lut = []
    for i in range(LUT_SIZE):
        x = i / (LUT_SIZE - 1)
        y = agx_sigmoid(x)
        y = max(0.0, min(1.0, y))
        lut.append(y)
    return lut


def emit_bin(lut: list[float], path: Path) -> None:
    """LUT as little-endian f32 bytes, 4 × LUT_SIZE bytes total."""
    path.parent.mkdir(parents=True, exist_ok=True)
    with path.open("wb") as f:
        for v in lut:
            f.write(struct.pack("<f", v))


def emit_rs(path: Path) -> None:
    """Rust constants file. Kept alongside agx_lut.bin for co-versioning."""
    MID_DISPLAY_COMPUTED = agx_sigmoid(MID_NORM)
    src = textwrap.dedent(f"""\
        //! Generated by src/scripts/derive_agx_lut.py — DO NOT EDIT BY HAND.
        //!
        //! Single-source-of-truth AgX constants. Re-run the derivation script
        //! when coefficients change; bump `viewTransformVersion` in
        //! RenderedPreviewCache (spec § 05-performance.md) at the same time.

        /// AgX log-encode domain: scene values below MID_GRAY * 2^MIN_EV
        /// clamp to the toe; values above MID_GRAY * 2^MAX_EV clamp to the
        /// shoulder.
        pub const AGX_MIN_EV: f32 = {MIN_EV:.6};
        pub const AGX_MAX_EV: f32 = {MAX_EV:.6};

        /// Scene-linear middle gray — the AgX log-encoding reference point.
        pub const AGX_MID_GRAY: f32 = {MID_GRAY:.6};

        /// Display-linear value at the mid-gray log-pivot (norm = MID_NORM).
        /// Computed from the Blender polynomial at norm = (0 - MIN_EV)/EV_RANGE.
        /// This is NOT a tunable; it's the value Blender's AgX_Default_Contrast
        /// curve produces at that position.
        pub const AGX_MID_DISPLAY: f32 = {MID_DISPLAY_COMPUTED:.6};

        /// Blender 4.x AgX_Base default contrast slope.
        pub const AGX_BASE_SLOPE: f32 = {BASE_SLOPE:.6};

        /// Size of the per-channel sigmoid LUT embedded in agx_lut.bin.
        pub const AGX_LUT_SIZE: usize = {LUT_SIZE};

        /// Cache-invalidation key — every time this file's bytes change
        /// (due to coefficient edits or LUT recompute), bump this. It is
        /// propagated into RenderedPreviewCache's viewTransformVersion
        /// so every cached preview re-renders on the next cold open.
        pub const AGX_VERSION: u32 = {AGX_VERSION};
    """)
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(src)


def sanity_check(lut: list[float]) -> None:
    """Verify endpoint anchors and monotonicity. Mid-gray display value is
    whatever the Blender polynomial produces at norm = MID_NORM (~0.497)."""
    assert abs(lut[0]) < 1e-5, f"LUT[0] = {lut[0]:.6f}, expected ~0"
    assert lut[-1] >= 0.98, f"LUT[-1] = {lut[-1]:.6f}, expected ≥ 0.98"
    mid_idx = round(MID_NORM * (LUT_SIZE - 1))
    mid_val = lut[mid_idx]
    assert 0.40 < mid_val < 0.60, (
        f"mid-gray anchor LUT[{mid_idx}] = {mid_val:.6f} outside plausible "
        f"Blender AgX range [0.40, 0.60] — coefficient drift?"
    )
    # Monotonicity
    for i in range(1, LUT_SIZE):
        assert lut[i] >= lut[i - 1] - 1e-6, (
            f"non-monotone at {i}: {lut[i-1]:.6f} → {lut[i]:.6f}"
        )


def main() -> int:
    p = argparse.ArgumentParser()
    p.add_argument("--bin", required=True, help="output .bin path")
    p.add_argument("--rs",  required=True, help="output coeffs.rs path")
    args = p.parse_args()

    lut = build_lut()
    sanity_check(lut)
    emit_bin(lut, Path(args.bin))
    emit_rs(Path(args.rs))
    print(f"wrote {args.bin} ({LUT_SIZE} f32 entries, {LUT_SIZE * 4} bytes)")
    print(f"wrote {args.rs}  (constants, version={AGX_VERSION})")
    return 0


if __name__ == "__main__":
    sys.exit(main())
