/**
 * Every source collection is either imported or named here, and the run
 * refuses to start if one is neither.
 *
 * The importer's report prints a "not imported, deliberately" list, and a list
 * like that is only worth reading if it is exhaustive. It was not: five
 * collections a live install carries — the ACME material behind managed LAN
 * HTTPS, the indexer's resume points, the three Meilisearch backfill tables —
 * had no plan, no entry, and no mention anywhere. Nothing enumerated the source
 * database, so running the importer could not reveal the gap; only reading the
 * plan against every `db.collection(…)` call in the API could. That is the
 * worst shape a data-loss bug can take on a one-way migration, because the
 * operator finds out when they need the data and the source is already gone.
 *
 * So the check is the other way round now. {@link uncoveredCollections} asks
 * MongoDB what is actually in the database and subtracts what the plan imports
 * and what {@link SKIPPED_COLLECTIONS} declares; anything left stops the run
 * before it writes a row. A collection that is genuinely disposable costs one
 * line and a sentence saying why; one that is not costs a plan. Neither can be
 * skipped by accident.
 */

import type { Db } from 'mongodb';
import type { CollectionPlan } from '../types.ts';

/**
 * Source collections read but not written, with the reason each is safe to
 * leave behind. An entry here is a claim that nothing is lost that the install
 * cannot rebuild for itself.
 *
 * Four entries used to rest on a weaker claim than that — "something
 * downstream can re-derive this" — and three of them turned out to be the
 * expensive half of the cutover rather than the cheap one (#3797). The
 * certificate, the indexer's resume points and the Meilisearch cursor are
 * imported now; see `plan/settings.ts` for what each cost. The bar an entry
 * here has to clear is that copying the collection would be actively harmful
 * or that there is nothing on the other side to copy it into, not that a
 * plausible story exists for rebuilding it.
 */
export const SKIPPED_COLLECTIONS: Record<string, string> = {
  migrations: 'Mongo migration sentinels; SQLite keeps its own schema_migrations',
  worker_status: 'cached status snapshot, rewritten by the workers on first boot',
  generated_searches: 'regenerated by the generated-search worker; no destination table',
  video_geo_backfill_audit: 'audit log of a completed one-shot migration; no destination table',
  image_access_tokens: 'capability tokens that live for minutes; a client mints another',
  indexer_config: 'retired pipeline pool sizes, superseded by worker_config — see below',
  indexer_dead_letter:
    "retired pipeline's redrive queue; a stage that gives up marks its asset — see below",
  meilisearch_backfill_leases: 'a claim held by a process the cutover ends — see below',
  probe: 'connectivity ping, not data',
};

/**
 * `meilisearch_backfill_leases` is the one entry that survived the #3797 sweep
 * with its two neighbours imported, so the reason is worth stating properly.
 *
 * The row is a single-runner claim: an owner id and an expiry, written by a
 * backfill worker while it holds the index and deleted when it lets go. The
 * process that holds it does not survive the cutover, so the claim is false
 * the moment it is copied — and the only thing the copy can do is make the new
 * install's first runner wait out somebody else's expiry before it may start.
 * There is no work state in the row to lose: the cursor and the counters are
 * in `meilisearch_backfill_state`, which IS imported, and the redrive list is
 * in `meilisearch_backfill_failures`, which is too. So this is the rare case
 * where copying is the harmful option and skipping is the safe one, rather
 * than the re-derivable-in-principle argument the other two rested on.
 */

/**
 * The two `indexer_*` entries above are the ones that look like operator
 * tuning being thrown away, so they are spelled out too. They are what the
 * first boot against a real production library turned up (#3786): both are
 * written by a subsystem that has since been deleted, which is why neither
 * appears in any `db.collection(…)` call site here and why reading this
 * repository could not have found them.
 *
 * `indexer_config` is one document per install, `_id: "workers"`, holding the
 * per-stage worker pool sizes of the bounded-channel indexer that ran
 * `discover → hash → exif → thumb → ai → mongo` in memory. That pipeline is
 * retired and the module that read the document back on startup
 * (`indexer/indexer-config.repo.ts`, behind `PUT /api/indexer/config`) went
 * with it, so nothing has turned those numbers into a running worker since.
 *
 * What replaced it is `worker_config` — one row per worker, written from
 * Settings → Workers and read by the worker tier on every poll tick — and
 * `worker_config` is imported in full, concurrency included. The production
 * library shows the two apart rather than in agreement: its `indexer_config`
 * was last written on 2026-05-09 and says every stage is 32, while its twenty
 * `worker_config` rows, the oldest created the following day and the newest in
 * September, say thumb 100, preview 50, exif 10, describe 3, face paused. The
 * live tuning is the one being carried across; carrying the old document too
 * could only mean writing a retired pipeline's numbers over it.
 *
 * `indexer_dead_letter` is the same pipeline's redrive queue: one document per
 * (file, stage) that failed three times, keyed by maple id or absolute path.
 * The concept survives, the rows do not. A per-asset stage that exhausts its
 * retries marks `dead` on that asset's own stage row, and the slow-tier
 * enrichment stages record theirs in `enrichment_state`; both travel with the
 * asset they belong to. There is no destination for a queue keyed by a path
 * and a stage vocabulary that no longer exists — `hash` and `mongo` are not
 * stages any more, so no code on either side could re-drive one of these rows.
 * Production's copy is empty, which is a consequence of the retirement rather
 * than the reason this is safe: the entry would read the same at a thousand
 * rows.
 */

/** Collections MongoDB itself owns, which are not the library's. */
function isInternal(name: string): boolean {
  return name.startsWith('system.');
}

/**
 * Collections present in the source that the plan neither imports nor declares.
 *
 * Read from the server rather than from a list in the repository, because the
 * whole point is to catch the collection nobody here knew about.
 */
export async function uncoveredCollections(
  db: Db,
  plan: readonly CollectionPlan[],
): Promise<string[]> {
  // `alsoReads` is what keeps a plan that consumes a second collection from
  // having to declare that collection skipped. The lens-profile bucket is the
  // only such case: its chunks are read and written, so calling them skipped
  // would be the false claim this file exists to prevent.
  const covered = new Set<string>([
    ...plan.map((entry) => entry.source),
    ...plan.flatMap((entry) => entry.alsoReads ?? []),
    ...Object.keys(SKIPPED_COLLECTIONS),
  ]);
  const present = await db.listCollections({}, { nameOnly: true }).toArray();
  return present
    .map((entry) => entry.name)
    .filter((name) => !isInternal(name) && !covered.has(name))
    .sort();
}

/** The refusal an uncovered collection earns, addressed to whoever reads it. */
export function uncoveredMessage(names: readonly string[]): string {
  return [
    `The source database holds ${names.length} collection(s) this importer does not know about: `,
    `${names.join(', ')}. `,
    'Each would be left behind at cutover with nothing in the report to say so, which is why ',
    'the run stops here rather than finishing and looking complete. Give each one a plan in ',
    'src/api/src/db/sqlite/import/plan/, or name it in SKIPPED_COLLECTIONS in ',
    'plan/coverage.ts with the reason it is safe to leave behind.',
  ].join('');
}
