/**
 * Every source collection is either imported or named here, and the run
 * refuses to start if one is neither.
 *
 * The importer's report prints a "not imported, deliberately" list, and a list
 * like that is only worth reading if it is exhaustive. It was not: five
 * collections a live install carries — the ACME material behind managed LAN
 * HTTPS, the indexer's resume points, the three Meilisearch backfill tables —
 * had no plan, no entry, and no mention anywhere. Nothing enumerated the source
 * database, so running the importer could not reveal the gap; only reading the
 * plan against every `db.collection(…)` call in the API could. That is the
 * worst shape a data-loss bug can take on a one-way migration, because the
 * operator finds out when they need the data and the source is already gone.
 *
 * So the check is the other way round now. {@link uncoveredCollections} asks
 * MongoDB what is actually in the database and subtracts what the plan imports
 * and what {@link SKIPPED_COLLECTIONS} declares; anything left stops the run
 * before it writes a row. A collection that is genuinely disposable costs one
 * line and a sentence saying why; one that is not costs a plan. Neither can be
 * skipped by accident.
 */

import type { Db } from 'mongodb';
import type { CollectionPlan } from '../types.ts';

/**
 * Source collections read but not written, with the reason each is safe to
 * leave behind. An entry here is a claim that nothing is lost that the install
 * cannot rebuild for itself.
 */
export const SKIPPED_COLLECTIONS: Record<string, string> = {
  migrations: 'Mongo migration sentinels; SQLite keeps its own schema_migrations',
  worker_status: 'cached status snapshot, rewritten by the workers on first boot',
  generated_searches: 'regenerated by the generated-search worker; no destination table',
  video_geo_backfill_audit: 'audit log of a completed one-shot migration; no destination table',
  image_access_tokens: 'capability tokens that live for minutes; a client mints another',
  managed_certificates: 'ACME account and LAN certificate; re-issued on first boot — see below',
  indexer_checkpoints: 'per-library walk resume points; the next sweep re-derives them',
  meilisearch_backfill_state: 'search backfill cursor; a fresh backfill restarts from the top',
  meilisearch_backfill_leases: 'search backfill worker leases, seconds old and self-expiring',
  meilisearch_backfill_failures: 'search backfill redrive list; re-derived by the next backfill',
  probe: 'connectivity ping, not data',
};

/**
 * `managed_certificates` is the entry that costs the operator something, so it
 * is spelled out rather than left to a table cell.
 *
 * The collection holds the ACME account key, the issued LAN certificate and
 * any DNS-01 challenge records still outstanding. A cutover that leaves it
 * behind means the server re-issues from scratch on first boot: a new account
 * key, a new certificate against Let's Encrypt's duplicate-certificate rate
 * limit, and any TXT records the old challenges created left orphaned in
 * Cloudflare. That is recoverable and it is not silent — this is printed at
 * the end of every run — but an operator who has just cut over should expect a
 * certificate re-issue rather than discover one.
 */
export const MANAGED_CERTIFICATES_WARNING =
  'The ACME account key and the issued LAN certificate are not carried over: the server ' +
  're-issues on first boot, against the duplicate-certificate rate limit, and any DNS-01 ' +
  'challenge records outstanding at cutover are orphaned in Cloudflare.';

/** Collections MongoDB itself owns, which are not the library's. */
function isInternal(name: string): boolean {
  return name.startsWith('system.');
}

/**
 * Collections present in the source that the plan neither imports nor declares.
 *
 * Read from the server rather than from a list in the repository, because the
 * whole point is to catch the collection nobody here knew about.
 */
export async function uncoveredCollections(
  db: Db,
  plan: readonly CollectionPlan[],
): Promise<string[]> {
  const covered = new Set<string>([
    ...plan.map((entry) => entry.source),
    ...Object.keys(SKIPPED_COLLECTIONS),
  ]);
  const present = await db.listCollections({}, { nameOnly: true }).toArray();
  return present
    .map((entry) => entry.name)
    .filter((name) => !isInternal(name) && !covered.has(name))
    .sort();
}

/** The refusal an uncovered collection earns, addressed to whoever reads it. */
export function uncoveredMessage(names: readonly string[]): string {
  return [
    `The source database holds ${names.length} collection(s) this importer does not know about: `,
    `${names.join(', ')}. `,
    'Each would be left behind at cutover with nothing in the report to say so, which is why ',
    'the run stops here rather than finishing and looking complete. Give each one a plan in ',
    'src/api/src/db/sqlite/import/plan/, or name it in SKIPPED_COLLECTIONS in ',
    'plan/coverage.ts with the reason it is safe to leave behind.',
  ].join('');
}
