/**
 * Every source collection is either imported or named here, and the run
 * refuses to start if one is neither.
 *
 * The importer's report prints a "not imported, deliberately" list, and a list
 * like that is only worth reading if it is exhaustive. It was not: five
 * collections a live install carries — the ACME material behind managed LAN
 * HTTPS, the indexer's resume points, the three Meilisearch backfill tables —
 * had no plan, no entry, and no mention anywhere. Nothing enumerated the source
 * database, so running the importer could not reveal the gap; only reading the
 * plan against every `db.collection(…)` call in the API could. That is the
 * worst shape a data-loss bug can take on a one-way migration, because the
 * operator finds out when they need the data and the source is already gone.
 *
 * So the check is the other way round now. {@link uncoveredCollections} asks
 * MongoDB what is actually in the database and subtracts what the plan imports
 * and what {@link SKIPPED_COLLECTIONS} declares; anything left stops the run
 * before it writes a row. A collection that is genuinely disposable costs one
 * line and a sentence saying why; one that is not costs a plan. Neither can be
 * skipped by accident.
 */

import type { Db } from 'mongodb';
import type { CollectionPlan } from '../types.ts';

/**
 * Source collections read but not written, with the reason each is safe to
 * leave behind. An entry here is a claim that nothing is lost that the install
 * cannot rebuild for itself.
 */
export const SKIPPED_COLLECTIONS: Record<string, string> = {
  migrations: 'Mongo migration sentinels; SQLite keeps its own schema_migrations',
  worker_status: 'cached status snapshot, rewritten by the workers on first boot',
  generated_searches: 'regenerated by the generated-search worker; no destination table',
  video_geo_backfill_audit: 'audit log of a completed one-shot migration; no destination table',
  image_access_tokens: 'capability tokens that live for minutes; a client mints another',
  managed_certificates: 'ACME account and LAN certificate; re-issued on first boot — see below',
  indexer_checkpoints: 'per-library walk resume points; the next sweep re-derives them',
  indexer_config: 'retired pipeline pool sizes, superseded by worker_config — see below',
  indexer_dead_letter:
    "retired pipeline's redrive queue; a stage that gives up marks its asset — see below",
  meilisearch_backfill_state: 'search backfill cursor; a fresh backfill restarts from the top',
  meilisearch_backfill_leases: 'search backfill worker leases, seconds old and self-expiring',
  meilisearch_backfill_failures: 'search backfill redrive list; re-derived by the next backfill',
  probe: 'connectivity ping, not data',
};

/**
 * `managed_certificates` is the entry that costs the operator something, so it
 * is spelled out rather than left to a table cell.
 *
 * The collection holds the ACME account key, the issued LAN certificate and
 * any DNS-01 challenge records still outstanding. A cutover that leaves it
 * behind means the server re-issues from scratch on first boot: a new account
 * key, a new certificate against Let's Encrypt's duplicate-certificate rate
 * limit, and any TXT records the old challenges created left orphaned in
 * Cloudflare. That is recoverable and it is not silent — this is printed at
 * the end of every run — but an operator who has just cut over should expect a
 * certificate re-issue rather than discover one.
 */
export const MANAGED_CERTIFICATES_WARNING =
  'The ACME account key and the issued LAN certificate are not carried over: the server ' +
  're-issues on first boot, against the duplicate-certificate rate limit, and any DNS-01 ' +
  'challenge records outstanding at cutover are orphaned in Cloudflare.';

/**
 * The two `indexer_*` entries above are the ones that look like operator
 * tuning being thrown away, so they are spelled out too. They are what the
 * first boot against a real production library turned up (#3786): both are
 * written by a subsystem that has since been deleted, which is why neither
 * appears in any `db.collection(…)` call site here and why reading this
 * repository could not have found them.
 *
 * `indexer_config` is one document per install, `_id: "workers"`, holding the
 * per-stage worker pool sizes of the bounded-channel indexer that ran
 * `discover → hash → exif → thumb → ai → mongo` in memory. That pipeline is
 * retired and the module that read the document back on startup
 * (`indexer/indexer-config.repo.ts`, behind `PUT /api/indexer/config`) went
 * with it, so nothing has turned those numbers into a running worker since.
 *
 * What replaced it is `worker_config` — one row per worker, written from
 * Settings → Workers and read by the worker tier on every poll tick — and
 * `worker_config` is imported in full, concurrency included. The production
 * library shows the two apart rather than in agreement: its `indexer_config`
 * was last written on 2026-05-09 and says every stage is 32, while its twenty
 * `worker_config` rows, the oldest created the following day and the newest in
 * September, say thumb 100, preview 50, exif 10, describe 3, face paused. The
 * live tuning is the one being carried across; carrying the old document too
 * could only mean writing a retired pipeline's numbers over it.
 *
 * `indexer_dead_letter` is the same pipeline's redrive queue: one document per
 * (file, stage) that failed three times, keyed by maple id or absolute path.
 * The concept survives, the rows do not. A per-asset stage that exhausts its
 * retries marks `dead` on that asset's own stage row, and the slow-tier
 * enrichment stages record theirs in `enrichment_state`; both travel with the
 * asset they belong to. There is no destination for a queue keyed by a path
 * and a stage vocabulary that no longer exists — `hash` and `mongo` are not
 * stages any more, so no code on either side could re-drive one of these rows.
 * Production's copy is empty, which is a consequence of the retirement rather
 * than the reason this is safe: the entry would read the same at a thousand
 * rows.
 */

/** Collections MongoDB itself owns, which are not the library's. */
function isInternal(name: string): boolean {
  return name.startsWith('system.');
}

/**
 * Collections present in the source that the plan neither imports nor declares.
 *
 * Read from the server rather than from a list in the repository, because the
 * whole point is to catch the collection nobody here knew about.
 */
export async function uncoveredCollections(
  db: Db,
  plan: readonly CollectionPlan[],
): Promise<string[]> {
  // `alsoReads` is what keeps a plan that consumes a second collection from
  // having to declare that collection skipped. The lens-profile bucket is the
  // only such case: its chunks are read and written, so calling them skipped
  // would be the false claim this file exists to prevent.
  const covered = new Set<string>([
    ...plan.map((entry) => entry.source),
    ...plan.flatMap((entry) => entry.alsoReads ?? []),
    ...Object.keys(SKIPPED_COLLECTIONS),
  ]);
  const present = await db.listCollections({}, { nameOnly: true }).toArray();
  return present
    .map((entry) => entry.name)
    .filter((name) => !isInternal(name) && !covered.has(name))
    .sort();
}

/** The refusal an uncovered collection earns, addressed to whoever reads it. */
export function uncoveredMessage(names: readonly string[]): string {
  return [
    `The source database holds ${names.length} collection(s) this importer does not know about: `,
    `${names.join(', ')}. `,
    'Each would be left behind at cutover with nothing in the report to say so, which is why ',
    'the run stops here rather than finishing and looking complete. Give each one a plan in ',
    'src/api/src/db/sqlite/import/plan/, or name it in SKIPPED_COLLECTIONS in ',
    'plan/coverage.ts with the reason it is safe to leave behind.',
  ].join('');
}
