/**
 * The import plan: every source collection, in the order it is read.
 *
 * ## Why the order still matters when foreign keys are off
 *
 * The bulk load runs with `PRAGMA foreign_keys = OFF`, because the source has a
 * genuine reference cycle the loader cannot order its way out of: a face points
 * at a person, and a person's cover points at an asset. One of the two has to
 * be written before its target exists, so the load defers enforcement and
 * `PRAGMA foreign_key_check` becomes the gate at the end instead.
 *
 * The order below is still the foreign-key order, because it makes that final
 * check meaningful. Almost every reference resolves naturally when the parents
 * are loaded first, so a violation the check reports is a real dangling
 * reference in the source — a face assigned to a deleted person, a location in
 * a library that was unregistered — rather than an artefact of the order rows
 * happened to arrive in.
 *
 * ## Collections deliberately not imported
 *
 * | Collection                 | Why not                                                                                                  |
 * | -------------------------- | -------------------------------------------------------------------------------------------------------- |
 * | `migrations`               | Mongo migration ids describing Mongo-shaped backfills. The SQLite runner keeps its own `schema_migrations`. |
 * | `worker_status`            | One cached status snapshot, rewritten by the workers within a poll cycle of the first boot.               |
 * | `generated_searches`       | AI-generated search suggestions, regenerated by their worker; no table in the schema.                     |
 * | `video_geo_backfill_audit` | The audit log of a one-shot migration that has already run; no table in the schema.                       |
 * | `image_access_tokens`      | Shape mismatch, and minute-long lifetimes. See `plan/auth.ts`.                                            |
 * | `probe`                    | A connectivity ping, not data.                                                                            |
 */

import type { CollectionPlan } from '../types.ts';
import { assetsPlan } from './assets.ts';
import { AUTH_PLANS } from './auth.ts';
import { LIBRARY_PLANS } from './library.ts';
import { OPERATIONS_PLANS } from './operations.ts';

/** Source collections read but not written, with the reason. */
export const SKIPPED_COLLECTIONS: Record<string, string> = {
  migrations: 'Mongo migration sentinels; SQLite keeps its own schema_migrations',
  worker_status: 'cached status snapshot, rewritten by the workers on first boot',
  generated_searches: 'regenerated by the generated-search worker; no destination table',
  video_geo_backfill_audit: 'audit log of a completed one-shot migration; no destination table',
  image_access_tokens: 'shape mismatch with the destination table; minute-long lifetimes',
  probe: 'connectivity ping, not data',
};

/**
 * Every plan, in execution order: the roots the rest of the graph points at,
 * then assets and their fan-out, then users, then the queues — which reference
 * both a library root and a user.
 */
export const IMPORT_PLAN: readonly CollectionPlan[] = [
  ...LIBRARY_PLANS,
  assetsPlan,
  ...AUTH_PLANS,
  ...OPERATIONS_PLANS,
];

export { DEFAULT_CHANGES_WINDOW } from './library.ts';
