//! AcrMatch view transform — GPU pass (epic #1710, slice 2 / #1722).
//!
//! Applies the baked `acr_match_lut.bin` 3D scene-linear cube LUT across an
//! RGBA f32 buffer (alpha untouched). Input: scene-linear Rec.2020. Output:
//! display-linear Rec.2020. The LUT is uploaded ONCE to a read-only storage
//! buffer (pooled, like `AgxPass`'s baked sigmoid LUT).
//!
//! ## LUT encoding
//!
//! The LUT uses the same AgX log2 shaper as the AgX kernel (MIN_EV = −10,
//! MAX_EV = +6.5, MID_GRAY = 0.18) so each axis maps to the [0, 1] range:
//!   `t[c] = (log2(scene[c] / MID_GRAY) − MIN_EV) / (MAX_EV − MIN_EV)`
//! Layout: `((b·N+g)·N+r)·3+ch`, matching `ColorLut`'s convention. The node
//! count per axis is `ACR_MATCH_LUT_N = 33` (33³×3×4 ≈ 431 KB).
//!
//! ## Accuracy note
//!
//! The 33-node RGB cube LUT introduces substantial error for highly saturated
//! colors: measured peak ~0.61 vs direct `apply_model` on a saturated green
//! `(0.1, 0.7, 0.1)` scene value. The source of the inaccuracy is that
//! `apply_model` parameterises the hue/chroma field in Oklab space (hue angle,
//! chroma magnitude), but the LUT samples an isometric RGB cube — a 15° hue
//! swing at high chroma can land in two different HUE_BIN slots yet sample the
//! same RGB-cube cell. A future ticket will port `apply_model` directly to WGSL
//! (uploading the tonescale knots and hue/chroma lattice as storage buffers) for
//! sub-0.01 accuracy. This GPU pass is "good enough for a selectable preview mode"
//! (the profile is NOT the default in this slice; high-saturation scenes are the
//! least common case for a profile designed to match ACR's film-like neutral tone).
//!
//! Three pieces (the per-stage template):
//! 1. [`apply_acr_match`] — the CPU oracle: samples the baked LUT over a flat
//!    RGBA f32 buffer (alpha untouched), matching the baked bytes the GPU kernel
//!    reads. `gpu_matches_lut_oracle_within_float_rounding` confirms the GPU
//!    kernel faithfully executes this path (< 1e-4). The EXACT reference is
//!    `raw_core::view::acr_match::apply` (direct `apply_model`).
//! 2. [`AcrMatchPass`] — the GPU-resident [`Pass`]; no per-pass fields (the
//!    LUT is a constant). Uploads the baked LUT to storage binding 3 inside
//!    `encode`.
//! 3. The headless parity test ([`mod tests`], in `acr_match_pass/tests.rs`) —
//!    GPU vs the real `raw_core::view::acr_match::apply` (via the test-only
//!    `raw-core` dev-dep). The parity budget is 0.7 (documenting the known LUT
//!    accuracy floor, measured on the structured test buffer), NOT the usual
//!    1e-4; a comment in the test calls this out.

use crate::chain::Pass;
use crate::context::GpuContext;
use crate::spatial::{encode_simple, pool_data_storage};

/// The baked AcrMatch 3D cube LUT — `ACR_MATCH_LUT_N`³ × 3 f32 LE.
/// Generated by `cargo run --release --example bake-acr-match-lut -p raw-core`
/// and committed under `raw-core/src/view/acr_match_lut.bin`.
const ACR_MATCH_LUT_BYTES: &[u8] = include_bytes!("../../raw-core/src/view/acr_match_lut.bin");

/// LUT node count per axis. Must match `raw_core::view::acr_match::ACR_MATCH_LUT_N`.
/// Derived from byte length: `n³ × 3 × 4 = byte_len` → `n = (byte_len/12)^(1/3)`.
const ACR_MATCH_LUT_N: usize = {
    let float_count = ACR_MATCH_LUT_BYTES.len() / 4;
    let node_count = float_count / 3; // n³
                                      // Cube root: iterate from 2 to 256 and find n³ == node_count.
                                      // Evaluated at compile time (const context).
    let mut n = 2usize;
    loop {
        if n * n * n == node_count {
            break n;
        }
        n += 1;
        if n > 256 {
            panic!("ACR_MATCH_LUT_BYTES length is not n³×3×4 for any n ≤ 256");
        }
    }
};

// ── AgX shaper parameters (mirrors acr_match.rs / agx.rs) ───────────────────
// These constants are EMBEDDED in the WGSL kernel so the GPU samples the same
// log2 shaper domain as the CPU oracle.
const ACR_LUT_MIN_EV: f32 = -10.0;
const ACR_LUT_MAX_EV: f32 = 6.5;
const ACR_LUT_MID_GRAY: f32 = 0.18;

/// Sample the baked AcrMatch 3D LUT at scene-linear `rgb` using trilinear
/// interpolation. Mirrors `raw_core::view::acr_match::sample_lut_3d`.
///
/// The input is encoded by the AgX log2 shaper before indexing; the LUT stores
/// display-linear Rec.2020 values.
fn sample_lut(data: &[f32], n: usize, rgb: [f32; 3]) -> [f32; 3] {
    let last = (n - 1) as f32;
    let floor_v = ACR_LUT_MID_GRAY * ACR_LUT_MIN_EV.exp2();
    let encode = |v: f32| -> f32 {
        let c = v.max(floor_v);
        let log2_v = (c / ACR_LUT_MID_GRAY)
            .log2()
            .clamp(ACR_LUT_MIN_EV, ACR_LUT_MAX_EV);
        (log2_v - ACR_LUT_MIN_EV) / (ACR_LUT_MAX_EV - ACR_LUT_MIN_EV)
    };

    let mut lo = [0usize; 3];
    let mut frac = [0f32; 3];
    for c in 0..3 {
        let t = encode(rgb[c]);
        let p = t.clamp(0.0, 1.0) * last;
        let l = p.floor().min(last - 1.0);
        lo[c] = l as usize;
        frac[c] = p - l;
    }

    let node = |ri: usize, gi: usize, bi: usize, ch: usize| -> f32 {
        let idx = (bi * n * n + gi * n + ri) * 3 + ch;
        data[idx]
    };

    let [fr, fg, fb] = frac;
    let [r0, g0, b0] = lo;
    let [r1, g1, b1] = [r0 + 1, g0 + 1, b0 + 1];

    let lerp = |a: f32, b: f32, t: f32| a + (b - a) * t;
    let mut out = [0.0f32; 3];
    for ch in 0..3 {
        let c00 = lerp(node(r0, g0, b0, ch), node(r1, g0, b0, ch), fr);
        let c10 = lerp(node(r0, g1, b0, ch), node(r1, g1, b0, ch), fr);
        let c01 = lerp(node(r0, g0, b1, ch), node(r1, g0, b1, ch), fr);
        let c11 = lerp(node(r0, g1, b1, ch), node(r1, g1, b1, ch), fr);
        let c0 = lerp(c00, c10, fg);
        let c1 = lerp(c01, c11, fg);
        out[ch] = lerp(c0, c1, fb);
    }
    out
}

/// Parse the baked LUT bytes to a `Vec<f32>` once. Uses `OnceLock` so the
/// parse only happens on first call (the LUT is a constant so re-parsing is
/// wasteful on the CPU oracle path).
fn lut() -> &'static Vec<f32> {
    static CELL: std::sync::OnceLock<Vec<f32>> = std::sync::OnceLock::new();
    CELL.get_or_init(|| {
        // `chunks_exact(4)` silently drops a trailing partial chunk — assert
        // the committed artifact is f32-aligned so a corrupted/truncated
        // `.bin` fails loudly here instead of quietly baking a short LUT.
        debug_assert_eq!(
            ACR_MATCH_LUT_BYTES.len() % 4,
            0,
            "acr_match_lut.bin length {} is not a multiple of 4 (f32) — file is truncated or corrupted",
            ACR_MATCH_LUT_BYTES.len()
        );
        ACR_MATCH_LUT_BYTES
            .chunks_exact(4)
            .map(|c| f32::from_le_bytes([c[0], c[1], c[2], c[3]]))
            .collect()
    })
}

/// Apply the AcrMatch LUT across an interleaved RGBA f32 buffer (alpha untouched).
/// This is the CPU oracle for the GPU parity gate — it uses the BAKED LUT (not
/// the direct `apply_model` call) so it pins the GPU kernel's code path exactly.
pub fn apply_acr_match(buf: &mut [f32]) {
    let data = lut();
    let n = ACR_MATCH_LUT_N;
    for px in buf.chunks_exact_mut(4) {
        let out = sample_lut(data, n, [px[0], px[1], px[2]]);
        px[0] = out[0];
        px[1] = out[1];
        px[2] = out[2];
        // px[3] (alpha) untouched
    }
}

/// `repr(C)` params uniform shared by the WGSL kernel (`acr_match.wgsl`).
/// `count` is the RGBA pixel count; `size` is the LUT node count per axis;
/// `_pad*` round to 16 bytes. (`params`, not `meta` — `meta` is a reserved
/// WGSL keyword.)
#[repr(C)]
#[derive(Clone, Copy, bytemuck::Pod, bytemuck::Zeroable)]
struct Params {
    count: u32,
    size: u32,
    _pad0: u32,
    _pad1: u32,
}

/// A GPU-resident AcrMatch view-transform stage (#1722). Applies the baked
/// 3D scene-linear LUT using the AgX log2 shaper + trilinear interpolation.
/// No per-pass fields — the LUT is a constant embedded in the binary and
/// uploaded once per chain shape via the pooled buffer mechanism.
pub struct AcrMatchPass;

impl Pass for AcrMatchPass {
    fn encode(
        &self,
        ctx: &GpuContext,
        encoder: &mut wgpu::CommandEncoder,
        src: &wgpu::Buffer,
        dst: &wgpu::Buffer,
        dims: (u32, u32),
    ) {
        let (width, height) = dims;
        let pixel_count = width * height;

        let params = Params {
            count: pixel_count,
            size: ACR_MATCH_LUT_N as u32,
            _pad0: 0,
            _pad1: 0,
        };

        // Baked LUT in a READ-ONLY STORAGE buffer (4-byte stride). A uniform
        // `array<f32>` would get a 16-byte per-element stride and silently
        // misalign — same trap auto_profile_curve's flat-curve buffer dodges.
        // POOLED (P4b-core C3): the baked LUT is a constant — uploaded once per
        // chain shape, reused every tick (never re-uploaded on a same-sig hit).
        let lut_buf = pool_data_storage(ctx, ACR_MATCH_LUT_BYTES, "acr-match-lut");

        // Pooled 4-binding dispatch: params @0, src @1, dst @2, LUT @3.
        encode_simple(
            ctx,
            encoder,
            ctx.acr_match_pipeline(),
            bytemuck::bytes_of(&params),
            &[src, dst, lut_buf.as_ref()],
            pixel_count,
            "acr-match",
        );
    }
}

// Parity tests live in a sibling file to keep this module under the 600-LOC
// budget (mirrors agx's `tests.rs` split). Native test builds only.
#[cfg(all(test, not(target_arch = "wasm32")))]
#[path = "acr_match_pass/tests.rs"]
mod tests;
