// maple-id.spec.ts — proves this module's `primary()`/`fallback()`/`fromHex()`
// match the server's real `src/api/src/indexer/id.ts` byte-for-byte.
//
// Expected hex values below were generated by IMPORTING AND RUNNING the real
// `primary`/`fallback` from `src/api/src/indexer/id.ts` against the exact
// same byte patterns and arguments used here (via `bun run` — see the
// scratchpad script that produced these; not committed, since `src/api` isn't
// reachable from `src/web`'s build — see this module's own doc comment for
// why). These are NOT hand-derived: they are the real server function's
// actual output for these inputs.

import { describe, it, expect } from 'vitest';
import { primary, fallback, fromHex, deriveId, TAG_PRIMARY, TAG_FALLBACK } from './maple-id';

function bytesFromPattern(len: number, seedMul: number, seedAdd: number): Uint8Array {
  const out = new Uint8Array(len);
  for (let i = 0; i < len; i++) out[i] = (i * seedMul + seedAdd) & 0xff;
  return out;
}

describe('primary — parity with src/api/src/indexer/id.ts', () => {
  it('matches the server for a basic head, no serial, no shutter', () => {
    const head = bytesFromPattern(1000, 7, 3);
    const id = primary(head, '2026-07-12T10:30:00.000Z', null, null);
    expect(id.hex).toBe('01c1d8b14783f21f538fd63d5f5559a8');
  });

  it('matches the server when a camera serial is present', () => {
    const head = bytesFromPattern(1000, 7, 3);
    const id = primary(head, '2026-07-12T10:30:00.000Z', 'CAM12345', null);
    expect(id.hex).toBe('0153e6874b1f38dda84700692129669d');
  });

  it('matches the server when serial AND shutter count are present', () => {
    const head = bytesFromPattern(1000, 7, 3);
    const id = primary(head, '2026-07-12T10:30:00.000Z', 'CAM12345', 42);
    expect(id.hex).toBe('018ee33abe14f79797b04b3951914239');
  });

  it('matches the server for a tiny (10-byte) head with shutter=0', () => {
    const head = bytesFromPattern(10, 1, 0);
    const id = primary(head, '2026-01-01T00:00:00.000Z', null, 0);
    expect(id.hex).toBe('0148bce015fe2f4dfb4900e6fa608a9a');
  });

  it('truncates a head longer than 64 KB the same way the server does', () => {
    // Both vectors share the same first 64 KB (`bytesFromPattern` is
    // deterministic per (seedMul, seedAdd), so a 70000-byte and a
    // 65536-byte buffer built from the same seeds are identical for their
    // first 65536 bytes) — the server truncates at SHA1_HEAD_BYTES before
    // hashing, so both must produce the SAME id.
    const over = bytesFromPattern(70000, 13, 5);
    const exact = bytesFromPattern(65536, 13, 5);
    const idOver = primary(over, '2020-01-01T00:00:00.000Z', null, null);
    const idExact = primary(exact, '2020-01-01T00:00:00.000Z', null, null);
    expect(idOver.hex).toBe('0136e6dc13320a14f776901e319a6d3a');
    expect(idExact.hex).toBe('0136e6dc13320a14f776901e319a6d3a');
    expect(idOver.hex).toBe(idExact.hex);
  });

  it('tags the id bytes with TAG_PRIMARY and kind "primary"', () => {
    const id = primary(bytesFromPattern(100, 1, 1), '2026-01-01T00:00:00.000Z', null, null);
    expect(id.bytes[0]).toBe(TAG_PRIMARY);
    expect(id.kind).toBe('primary');
    expect(id.bytes.length).toBe(16);
    expect(id.hex.length).toBe(32);
  });
});

describe('fallback — parity with src/api/src/indexer/id.ts', () => {
  it('matches the server for a basic 5000-byte buffer', () => {
    const bytes = bytesFromPattern(5000, 37, 11);
    const id = fallback(bytes, bytes.length);
    expect(id.hex).toBe('02195e96db4c33a5573f46025beb872d');
  });

  it('matches the server for an empty buffer', () => {
    const id = fallback(new Uint8Array(0), 0);
    expect(id.hex).toBe('026860f018c7d5223f95764b8d8c105e');
  });

  it('matches the server when the claimed filesize differs from bytes.length', () => {
    const bytes = bytesFromPattern(100, 3, 3);
    const id = fallback(bytes, 999);
    expect(id.hex).toBe('0294a6bb34816ac134472ac92138c5dd');
  });

  it('matches the server for a 200000-byte buffer (multi-chunk scale)', () => {
    const bytes = bytesFromPattern(200000, 5, 9);
    const id = fallback(bytes, bytes.length);
    expect(id.hex).toBe('0282ce38c3b570d9b261b6183775897f');
  });

  it('tags the id bytes with TAG_FALLBACK and kind "fallback"', () => {
    const id = fallback(bytesFromPattern(100, 1, 1), 100);
    expect(id.bytes[0]).toBe(TAG_FALLBACK);
    expect(id.kind).toBe('fallback');
  });
});

describe('deriveId', () => {
  it('picks primary when a capture timestamp is available', () => {
    const head = bytesFromPattern(1000, 7, 3);
    const id = deriveId(head, '2026-07-12T10:30:00.000Z', null, null);
    expect(id.kind).toBe('primary');
    expect(id.hex).toBe('01c1d8b14783f21f538fd63d5f5559a8');
  });

  it('picks fallback when no capture timestamp is available', () => {
    const bytes = bytesFromPattern(5000, 37, 11);
    const id = deriveId(bytes, null, null, null);
    expect(id.kind).toBe('fallback');
    expect(id.hex).toBe('02195e96db4c33a5573f46025beb872d');
  });
});

describe('fromHex', () => {
  it('round-trips a primary-form hex back into the same bytes/kind', () => {
    const original = primary(bytesFromPattern(1000, 7, 3), '2026-07-12T10:30:00.000Z', null, null);
    const parsed = fromHex(original.hex);
    expect(parsed.hex).toBe(original.hex);
    expect(parsed.kind).toBe('primary');
    expect(Array.from(parsed.bytes)).toEqual(Array.from(original.bytes));
  });

  it('round-trips a fallback-form hex back into the same bytes/kind', () => {
    const original = fallback(bytesFromPattern(5000, 37, 11), 5000);
    const parsed = fromHex(original.hex);
    expect(parsed.hex).toBe(original.hex);
    expect(parsed.kind).toBe('fallback');
  });

  it('lowercases mixed-case input', () => {
    const parsed = fromHex('01C1D8B14783F21F538FD63D5F5559A8');
    expect(parsed.hex).toBe('01c1d8b14783f21f538fd63d5f5559a8');
  });

  it('throws on the wrong length', () => {
    expect(() => fromHex('deadbeef')).toThrow(/32 hex chars/);
  });

  it('throws on a partially-invalid byte instead of silently truncating it (P2)', () => {
    // `Number.parseInt('0g', 16)` is `0`, not `NaN` — it parses the leading
    // valid digit and stops at the first invalid one instead of rejecting
    // the pair outright. A 32-char string is otherwise the right LENGTH, so
    // without validating every character, a string like this would have
    // silently produced a wrong-but-finite byte instead of throwing.
    const thirtyTwoCharsWithOneBadNibble = '0g1d8b14783f21f538fd63d5f5559a8'.padEnd(32, '0');
    expect(thirtyTwoCharsWithOneBadNibble).toHaveLength(32);
    expect(() => fromHex(thirtyTwoCharsWithOneBadNibble)).toThrow(/invalid hex digit/);
  });
});
