// AdjustmentModel+Init.swift — the memberwise initializer for
// `AdjustmentModel`, split out of the type's own file (#3409) so both stay
// well under the per-file LOC budget with real margin (#2311). Nothing else
// moves: the stored properties and their documentation stay on the struct,
// and this file is only the ~130-line parameter list they imply.
//
// Every parameter defaults to the fresh-import value, so `AdjustmentModel()`
// is `AdjustmentModel.default` and a caller names only what it changes.

import Foundation

extension AdjustmentModel {
  public init(
    temperature: Double = 6500,
    tint: Double = 0,
    wbScaleVersion: Int = 5,
    wbMethod: WbMethod = .cat16,
    wbSource: WbSource = .asShot,
    wbSampleX: Double = 0,
    wbSampleY: Double = 0,
    wbAlgorithmVersion: Double = 0,
    exposure: Double = 0,
    brightness: Double = 0,
    contrast: Double = 0,
    highlights: Double = 0,
    shadows: Double = 0,
    whites: Double = 0,
    blacks: Double = 0,
    parametricHighlights: Double = 0,
    parametricLights: Double = 0,
    parametricDarks: Double = 0,
    parametricShadows: Double = 0,
    parametricShadowSplit: Double = 25,
    parametricMidtoneSplit: Double = 50,
    parametricHighlightSplit: Double = 75,
    vibrance: Double = 0,
    saturation: Double = 0,
    clarity: Double = 0,
    texture: Double = 0,
    dehaze: Double = 0,
    sharpenAmount: Double = 40,
    sharpenRadius: Double = 1.0,
    sharpenDetail: Double = 25,
    sharpenMasking: Double = 0,
    captureSharpeningAmount: Double = 0,
    captureSharpeningSigma: Double = 1.0,
    nrLuminance: Double = 0,
    nrColor: Double = 25,
    vignetteAmount: Double = 0,
    vignetteFeather: Double = 50,
    grainAmount: Double = 0,
    grainSize: Double = 25,
    grainRoughness: Double = 50,
    splitToneShadowHue: Double = 0,
    splitToneShadowSaturation: Double = 0,
    splitToneHighlightHue: Double = 0,
    splitToneHighlightSaturation: Double = 0,
    splitToneBalance: Double = 0,
    colorGradeShadowLuminance: Double = 0,
    colorGradeMidtoneHue: Double = 0,
    colorGradeMidtoneSaturation: Double = 0,
    colorGradeMidtoneLuminance: Double = 0,
    colorGradeHighlightLuminance: Double = 0,
    colorGradeGlobalHue: Double = 0,
    colorGradeGlobalSaturation: Double = 0,
    colorGradeGlobalLuminance: Double = 0,
    hueAdjustmentRed: Double = 0,
    hueAdjustmentOrange: Double = 0,
    hueAdjustmentYellow: Double = 0,
    hueAdjustmentGreen: Double = 0,
    hueAdjustmentAqua: Double = 0,
    hueAdjustmentBlue: Double = 0,
    hueAdjustmentPurple: Double = 0,
    hueAdjustmentMagenta: Double = 0,
    saturationAdjustmentRed: Double = 0,
    saturationAdjustmentOrange: Double = 0,
    saturationAdjustmentYellow: Double = 0,
    saturationAdjustmentGreen: Double = 0,
    saturationAdjustmentAqua: Double = 0,
    saturationAdjustmentBlue: Double = 0,
    saturationAdjustmentPurple: Double = 0,
    saturationAdjustmentMagenta: Double = 0,
    luminanceAdjustmentRed: Double = 0,
    luminanceAdjustmentOrange: Double = 0,
    luminanceAdjustmentYellow: Double = 0,
    luminanceAdjustmentGreen: Double = 0,
    luminanceAdjustmentAqua: Double = 0,
    luminanceAdjustmentBlue: Double = 0,
    luminanceAdjustmentPurple: Double = 0,
    luminanceAdjustmentMagenta: Double = 0,
    blackWhite: BlackWhiteMode = .off,
    grayMixerRed: Double = 0,
    grayMixerOrange: Double = 0,
    grayMixerYellow: Double = 0,
    grayMixerGreen: Double = 0,
    grayMixerAqua: Double = 0,
    grayMixerBlue: Double = 0,
    grayMixerPurple: Double = 0,
    grayMixerMagenta: Double = 0,
    highlightRecovery: HighlightRecoveryMode = .chromaticAdaptation,
    autoExposure: AutoExposureMode = .on,
    look: Look = .default,
    profile: Profile = .auto,
    toneCurveMode: ToneCurveMode = .perChannel,
    toneCurveLuma: ToneCurve = .identity,
    toneCurveRed: ToneCurve = .identity,
    toneCurveGreen: ToneCurve = .identity,
    toneCurveBlue: ToneCurve = .identity,
    displayToneCurveLuma: ToneCurve = .identity,
    displayToneCurveRed: ToneCurve = .identity,
    displayToneCurveGreen: ToneCurve = .identity,
    displayToneCurveBlue: ToneCurve = .identity,
    chromaPrefilter: Double = 0,
    hotPixelSuppression: HotPixelSuppressionMode = .off,
    deepDenoise: Double = 0,
    crop: Crop = .identity,
    localAdjustments: [LocalAdjustment] = [],
    retouchSpots: [RetouchSpot] = [],
    lensProfileEnable: LensProfileEnable = .on,
    lensCorrectionDistortion: Double = 100,
    lensCorrectionCa: Double = 100,
    lensCorrectionVignetting: Double = 100,
    perspective: Perspective = .identity,
    filmLook: String = "",
    filmStrength: Double = 100,
    demosaic: DemosaicChoice = .auto
  ) {
    self.temperature = temperature
    self.tint = tint
    self.wbScaleVersion = wbScaleVersion
    self.wbMethod = wbMethod
    self.wbSource = wbSource
    self.wbSampleX = wbSampleX
    self.wbSampleY = wbSampleY
    self.wbAlgorithmVersion = wbAlgorithmVersion
    self.exposure = exposure
    self.brightness = brightness
    self.contrast = contrast
    self.highlights = highlights
    self.shadows = shadows
    self.whites = whites
    self.blacks = blacks
    self.parametricHighlights = parametricHighlights
    self.parametricLights = parametricLights
    self.parametricDarks = parametricDarks
    self.parametricShadows = parametricShadows
    self.parametricShadowSplit = parametricShadowSplit
    self.parametricMidtoneSplit = parametricMidtoneSplit
    self.parametricHighlightSplit = parametricHighlightSplit
    self.vibrance = vibrance
    self.saturation = saturation
    self.clarity = clarity
    self.texture = texture
    self.dehaze = dehaze
    self.sharpenAmount = sharpenAmount
    self.sharpenRadius = sharpenRadius
    self.sharpenDetail = sharpenDetail
    self.sharpenMasking = sharpenMasking
    self.captureSharpeningAmount = captureSharpeningAmount
    self.captureSharpeningSigma = captureSharpeningSigma
    self.nrLuminance = nrLuminance
    self.nrColor = nrColor
    self.vignetteAmount = vignetteAmount
    self.vignetteFeather = vignetteFeather
    self.grainAmount = grainAmount
    self.grainSize = grainSize
    self.grainRoughness = grainRoughness
    self.splitToneShadowHue = splitToneShadowHue
    self.splitToneShadowSaturation = splitToneShadowSaturation
    self.splitToneHighlightHue = splitToneHighlightHue
    self.splitToneHighlightSaturation = splitToneHighlightSaturation
    self.splitToneBalance = splitToneBalance
    self.colorGradeShadowLuminance = colorGradeShadowLuminance
    self.colorGradeMidtoneHue = colorGradeMidtoneHue
    self.colorGradeMidtoneSaturation = colorGradeMidtoneSaturation
    self.colorGradeMidtoneLuminance = colorGradeMidtoneLuminance
    self.colorGradeHighlightLuminance = colorGradeHighlightLuminance
    self.colorGradeGlobalHue = colorGradeGlobalHue
    self.colorGradeGlobalSaturation = colorGradeGlobalSaturation
    self.colorGradeGlobalLuminance = colorGradeGlobalLuminance
    self.hueAdjustmentRed = hueAdjustmentRed
    self.hueAdjustmentOrange = hueAdjustmentOrange
    self.hueAdjustmentYellow = hueAdjustmentYellow
    self.hueAdjustmentGreen = hueAdjustmentGreen
    self.hueAdjustmentAqua = hueAdjustmentAqua
    self.hueAdjustmentBlue = hueAdjustmentBlue
    self.hueAdjustmentPurple = hueAdjustmentPurple
    self.hueAdjustmentMagenta = hueAdjustmentMagenta
    self.saturationAdjustmentRed = saturationAdjustmentRed
    self.saturationAdjustmentOrange = saturationAdjustmentOrange
    self.saturationAdjustmentYellow = saturationAdjustmentYellow
    self.saturationAdjustmentGreen = saturationAdjustmentGreen
    self.saturationAdjustmentAqua = saturationAdjustmentAqua
    self.saturationAdjustmentBlue = saturationAdjustmentBlue
    self.saturationAdjustmentPurple = saturationAdjustmentPurple
    self.saturationAdjustmentMagenta = saturationAdjustmentMagenta
    self.luminanceAdjustmentRed = luminanceAdjustmentRed
    self.luminanceAdjustmentOrange = luminanceAdjustmentOrange
    self.luminanceAdjustmentYellow = luminanceAdjustmentYellow
    self.luminanceAdjustmentGreen = luminanceAdjustmentGreen
    self.luminanceAdjustmentAqua = luminanceAdjustmentAqua
    self.luminanceAdjustmentBlue = luminanceAdjustmentBlue
    self.luminanceAdjustmentPurple = luminanceAdjustmentPurple
    self.luminanceAdjustmentMagenta = luminanceAdjustmentMagenta
    self.blackWhite = blackWhite
    self.grayMixerRed = grayMixerRed
    self.grayMixerOrange = grayMixerOrange
    self.grayMixerYellow = grayMixerYellow
    self.grayMixerGreen = grayMixerGreen
    self.grayMixerAqua = grayMixerAqua
    self.grayMixerBlue = grayMixerBlue
    self.grayMixerPurple = grayMixerPurple
    self.grayMixerMagenta = grayMixerMagenta
    self.highlightRecovery = highlightRecovery
    self.autoExposure = autoExposure
    self.look = look
    self.profile = profile
    self.toneCurveMode = toneCurveMode
    self.toneCurveLuma = toneCurveLuma
    self.toneCurveRed = toneCurveRed
    self.toneCurveGreen = toneCurveGreen
    self.toneCurveBlue = toneCurveBlue
    self.displayToneCurveLuma = displayToneCurveLuma
    self.displayToneCurveRed = displayToneCurveRed
    self.displayToneCurveGreen = displayToneCurveGreen
    self.displayToneCurveBlue = displayToneCurveBlue
    self.chromaPrefilter = chromaPrefilter
    self.hotPixelSuppression = hotPixelSuppression
    self.deepDenoise = deepDenoise
    self.crop = crop
    self.localAdjustments = localAdjustments
    self.retouchSpots = retouchSpots
    self.lensProfileEnable = lensProfileEnable
    self.lensCorrectionDistortion = lensCorrectionDistortion
    self.lensCorrectionCa = lensCorrectionCa
    self.lensCorrectionVignetting = lensCorrectionVignetting
    self.perspective = perspective
    self.filmLook = filmLook
    self.filmStrength = filmStrength
    self.demosaic = demosaic
  }
}
