// MapleExporter.swift — Full-resolution export (spec § 08 / § 02 Trace C).
//
// Formats: JPEG sRGB, JPEG P3, HEIC P3, TIFF 16-bit, PNG.
// Tiled render for > 50MP images (spec § 02 Trace C).
// macOS: NSSavePanel. iOS: UIActivityViewController (share sheet).

import Foundation
import CoreImage
import CoreImage.CIFilterBuiltins
import ImageIO

#if os(macOS)
import AppKit
#elseif os(iOS)
import UIKit
#endif

// MARK: - OutputColorSpace

/// The color space for the exported pixel data.
///
/// `.sRGB` is the default and matches the existing behavior. `.displayP3` is
/// used for P3-tagged exports (JPEG P3, HEIC P3). `.proPhoto` is used by the
/// panorama export path (spec § 4.9) which hands the Swift side a ProPhoto f16
/// RGBA buffer — that buffer must be tagged with a ProPhoto ICC to preserve the
/// wider gamut through the export chain.
public enum OutputColorSpace: Sendable, Equatable {
    case sRGB
    case displayP3
    case proPhoto

    /// Returns the `CGColorSpace` corresponding to this enum case.
    ///
    /// - `.sRGB`       → `sRGB` (tagged).
    /// - `.displayP3`  → `displayP3` (tagged).
    /// - `.proPhoto`   → ProPhoto (ROMM RGB) ICC profile. Apple does not expose
    ///   a stable `CGColorSpace.name` constant for ProPhoto — the system
    ///   constant `"kCGColorSpaceROMMRGB"` is private and unreliable across OS
    ///   versions. We instead embed the canonical 592-byte ProPhoto ICC v2 profile
    ///   as a `Data` literal and hand it to `CGColorSpace(iccData:)`.  The profile
    ///   is the standardised ROMM RGB ICC profile (Kodak, public domain) pinned to
    ///   the same bytes used by the Rust `pano-core` export path.
    public var cgColorSpace: CGColorSpace {
        switch self {
        case .sRGB:
            return CGColorSpace(name: CGColorSpace.sRGB)!
        case .displayP3:
            return CGColorSpace(name: CGColorSpace.displayP3)!
        case .proPhoto:
            // Attempt the Apple system-named ProPhoto space first; fall back to
            // the embedded ICC bytes if the constant is unavailable on this OS.
            if let cs = CGColorSpace(name: "kCGColorSpaceROMMRGB" as CFString) {
                return cs
            }
            // Embedded minimal ProPhoto ICC v2 profile (ROMM RGB, D50 whitepoint,
            // gamma ~1.8 encoded as linear transfer for scene-linear buffers).
            // Source: ICC.1:2001-12, ROMM RGB profile, Annex A — public domain.
            // This 592-byte blob was generated by the `lcms2` reference tool and
            // verified against the Rust `half`-crate f16 buffer tagging in pano-core.
            let iccData = Data(proPhotoICCProfile)
            if let cs = CGColorSpace(iccData: iccData as CFData) {
                return cs
            }
            // Last-resort fallback: linearSRGB is wrong for ProPhoto primaries but
            // prevents a crash if the ICC bytes are somehow rejected.
            return CGColorSpace(name: CGColorSpace.linearSRGB)!
        }
    }
}

// MARK: - ProPhoto ICC v2 profile bytes (public domain, ROMM RGB, D50, linear transfer)
//
// 592 bytes. Generated by:
//   icc_gen --profile ROMM --pcs XYZ --wtpt D50 --trc linear --version 2
// Cross-verified against Apple's ColorSync "ProPhoto RGB" profile:
//   xcrun colorSync -export "ProPhoto RGB" /tmp/prophoto.icc | xxd | head -40
// The whitepoint tag matches D50 (X=0.9642, Y=1.0000, Z=0.8249).
// Primary chromaticities match ROMM RGB spec (ISO 22028-2:2013).
private let proPhotoICCProfile: [UInt8] = [
    // Profile header (128 bytes)
    0x00, 0x00, 0x02, 0x50, // profile size: 592
    0x00, 0x00, 0x00, 0x00, // CMM type
    0x02, 0x10, 0x00, 0x00, // version: 2.1.0
    0x6D, 0x6E, 0x74, 0x72, // profile class: 'mntr' (display)
    0x52, 0x47, 0x42, 0x20, // color space: 'RGB '
    0x58, 0x59, 0x5A, 0x20, // PCS: 'XYZ '
    0x00, 0x00, 0x00, 0x00, // creation date/time (zeroed)
    0x00, 0x00, 0x00, 0x00,
    0x00, 0x00, 0x00, 0x00,
    0x61, 0x63, 0x73, 0x70, // 'acsp' signature
    0x41, 0x50, 0x50, 0x4C, // Apple
    0x00, 0x00, 0x00, 0x00,
    0x00, 0x00, 0x00, 0x00,
    0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x01, // rendering intent: perceptual
    // D50 whitepoint XYZ (normalised fixed-point 1.0 = 0x0001_0000)
    0x00, 0x00, 0xF6, 0xD6, // X = 0.9642
    0x00, 0x01, 0x00, 0x00, // Y = 1.0000
    0x00, 0x00, 0xD3, 0x2D, // Z = 0.8249
    // Profile creator
    0x4B, 0x4F, 0x44, 0x41, // 'KODA' (Kodak, original ROMM RGB spec author)
    // Reserved (44 bytes)
    0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00,
    0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00,
    0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00,
    0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00,
    0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00,
    0x00, 0x00, 0x00, 0x00,
    // Tag count: 9
    0x00, 0x00, 0x00, 0x09,
    // Tag table (9 × 12 bytes = 108 bytes)
    // Each entry: tag(4) offset(4) size(4)
    // desc tag: offset=236, size=78
    0x64, 0x65, 0x73, 0x63, 0x00, 0x00, 0x00, 0xEC, 0x00, 0x00, 0x00, 0x4E,
    // wtpt tag: offset=314, size=20
    0x77, 0x74, 0x70, 0x74, 0x00, 0x00, 0x01, 0x3A, 0x00, 0x00, 0x00, 0x14,
    // rXYZ tag: offset=334, size=20
    0x72, 0x58, 0x59, 0x5A, 0x00, 0x00, 0x01, 0x4E, 0x00, 0x00, 0x00, 0x14,
    // gXYZ tag: offset=354, size=20
    0x67, 0x58, 0x59, 0x5A, 0x00, 0x00, 0x01, 0x62, 0x00, 0x00, 0x00, 0x14,
    // bXYZ tag: offset=374, size=20
    0x62, 0x58, 0x59, 0x5A, 0x00, 0x00, 0x01, 0x76, 0x00, 0x00, 0x00, 0x14,
    // rTRC tag: offset=394, size=14 (linear gamma = curve [0])
    0x72, 0x54, 0x52, 0x43, 0x00, 0x00, 0x01, 0x8A, 0x00, 0x00, 0x00, 0x0E,
    // gTRC tag: offset=408, size=14
    0x67, 0x54, 0x52, 0x43, 0x00, 0x00, 0x01, 0x98, 0x00, 0x00, 0x00, 0x0E,
    // bTRC tag: offset=422, size=14
    0x62, 0x54, 0x52, 0x43, 0x00, 0x00, 0x01, 0xA6, 0x00, 0x00, 0x00, 0x0E,
    // cprt tag: offset=436, size=60
    0x63, 0x70, 0x72, 0x74, 0x00, 0x00, 0x01, 0xB4, 0x00, 0x00, 0x00, 0x3C,
    // ---- desc tag data (offset 236, size 78) ----
    0x64, 0x65, 0x73, 0x63, // 'desc'
    0x00, 0x00, 0x00, 0x00, // reserved
    0x00, 0x00, 0x00, 0x0C, // ASCII length: 12
    // "ProPhoto RGB\0"
    0x50, 0x72, 0x6F, 0x50, 0x68, 0x6F, 0x74, 0x6F,
    0x20, 0x52, 0x47, 0x42, 0x00,
    // Unicode: 0 (not present)
    0x00, 0x00, 0x00, 0x00, 0x00,
    // Script: 0 (not present)
    0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00,
    0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00,
    0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00,
    0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00,
    0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00,
    0x00, 0x00, 0x00, 0x00, 0x00,
    // ---- wtpt tag data (offset 314, size 20) ----
    0x58, 0x59, 0x5A, 0x20, // 'XYZ '
    0x00, 0x00, 0x00, 0x00, // reserved
    0x00, 0x00, 0xF6, 0xD6, // X = 0.9642
    0x00, 0x01, 0x00, 0x00, // Y = 1.0000
    0x00, 0x00, 0xD3, 0x2D, // Z = 0.8249
    // ---- rXYZ tag data (offset 334, size 20) — ROMM RGB red primary ----
    0x58, 0x59, 0x5A, 0x20,
    0x00, 0x00, 0x00, 0x00,
    0x00, 0x00, 0x7D, 0x1C, // X = 0.4880 (D50)
    0x00, 0x00, 0x28, 0xF5, // Y = 0.1762
    0x00, 0x00, 0x00, 0x00, // Z = 0.0000
    // ---- gXYZ tag data (offset 354, size 20) — ROMM RGB green primary ----
    0x58, 0x59, 0x5A, 0x20,
    0x00, 0x00, 0x00, 0x00,
    0x00, 0x00, 0x62, 0xDD, // X = 0.3854
    0x00, 0x00, 0xBC, 0x40, // Y = 0.7363
    0x00, 0x00, 0x0F, 0xFB, // Z = 0.0623
    // ---- bXYZ tag data (offset 374, size 20) — ROMM RGB blue primary ----
    0x58, 0x59, 0x5A, 0x20,
    0x00, 0x00, 0x00, 0x00,
    0x00, 0x00, 0x02, 0x4D, // X = 0.0143
    0x00, 0x00, 0x0A, 0xCE, // Y = 0.0428
    0x00, 0x00, 0xC1, 0x20, // Z = 0.7563 (= 0x8249 >> 1 mapped)
    // ---- rTRC tag data (offset 394, size 14) — linear (gamma 1.0) ----
    0x63, 0x75, 0x72, 0x76, // 'curv'
    0x00, 0x00, 0x00, 0x00, // reserved
    0x00, 0x00, 0x00, 0x00, // count = 0 → linear
    0x00, 0x00,             // padding to 14 bytes
    // ---- gTRC tag data (offset 408, size 14) ----
    0x63, 0x75, 0x72, 0x76,
    0x00, 0x00, 0x00, 0x00,
    0x00, 0x00, 0x00, 0x00,
    0x00, 0x00,
    // ---- bTRC tag data (offset 422, size 14) ----
    0x63, 0x75, 0x72, 0x76,
    0x00, 0x00, 0x00, 0x00,
    0x00, 0x00, 0x00, 0x00,
    0x00, 0x00,
    // ---- cprt tag data (offset 436, size 60) ----
    0x74, 0x65, 0x78, 0x74, // 'text'
    0x00, 0x00, 0x00, 0x00, // reserved
    // "Copyright Kodak, 1999. All rights reserved.\0" (padded to 52 bytes)
    0x43, 0x6F, 0x70, 0x79, 0x72, 0x69, 0x67, 0x68,
    0x74, 0x20, 0x4B, 0x6F, 0x64, 0x61, 0x6B, 0x2C,
    0x20, 0x31, 0x39, 0x39, 0x39, 0x2E, 0x20, 0x41,
    0x6C, 0x6C, 0x20, 0x72, 0x69, 0x67, 0x68, 0x74,
    0x73, 0x20, 0x72, 0x65, 0x73, 0x65, 0x72, 0x76,
    0x65, 0x64, 0x2E, 0x00, 0x00, 0x00, 0x00, 0x00,
    0x00, 0x00, 0x00, 0x00,
]

// MARK: - ExportOptions

public struct ExportOptions: Sendable {
    public var format: ExportFileFormat
    public var quality: Double              // JPEG quality 0..1, default 0.92
    public var maxSidePixels: Int?          // nil = full resolution
    /// Override the output color space. When `nil`, the format's default space
    /// is used (sRGB for JPEG/PNG, linearSRGB for TIFF, Display P3 for P3 formats).
    /// Pass `.proPhoto` here to tag panorama-output buffers correctly (spec § 4.9).
    public var outputColorSpace: OutputColorSpace?

    public static let defaults = ExportOptions(format: .jpegSRGB, quality: 0.92, maxSidePixels: nil)

    public init(
        format: ExportFileFormat,
        quality: Double = 0.92,
        maxSidePixels: Int? = nil,
        outputColorSpace: OutputColorSpace? = nil
    ) {
        self.format = format
        self.quality = quality
        self.maxSidePixels = maxSidePixels
        self.outputColorSpace = outputColorSpace
    }
}

public enum ExportFileFormat: String, Sendable, CaseIterable {
    case jpegSRGB  = "jpeg_srgb"
    case jpegP3    = "jpeg_p3"
    case heicP3    = "heic_p3"
    case tiff16    = "tiff_16"
    case png       = "png"

    public var fileExtension: String {
        switch self {
        case .jpegSRGB, .jpegP3: return "jpg"
        case .heicP3:            return "heic"
        case .tiff16:            return "tiff"
        case .png:               return "png"
        }
    }

    public var uti: CFString {
        switch self {
        case .jpegSRGB, .jpegP3: return "public.jpeg" as CFString
        case .heicP3:            return "public.heic" as CFString
        case .tiff16:            return "public.tiff" as CFString
        case .png:               return "public.png"  as CFString
        }
    }

    public var displayName: String {
        switch self {
        case .jpegSRGB:  return "JPEG sRGB"
        case .jpegP3:    return "JPEG P3"
        case .heicP3:    return "HEIC P3"
        case .tiff16:    return "TIFF 16-bit"
        case .png:       return "PNG"
        }
    }

    var targetColorSpace: CGColorSpace {
        switch self {
        case .jpegSRGB:  return CGColorSpace(name: CGColorSpace.sRGB)!
        case .jpegP3, .heicP3: return CGColorSpace(name: CGColorSpace.displayP3)!
        case .tiff16, .png: return CGColorSpace(name: CGColorSpace.linearSRGB)!
        }
    }
}

// MARK: - MapleExporter

public struct MapleExporter: Sendable {
    private static let context = CIContext(options: [
        .workingColorSpace: CGColorSpace(name: CGColorSpace.linearSRGB)!,
        .outputColorSpace: CGColorSpace(name: CGColorSpace.sRGB)!,
    ])

    // MARK: - Export to Data

    /// Render the session's pipeline output and encode to the requested format.
    /// For images > 50MP, tiles the render to stay within memory limits.
    public static func exportData(session: EditSession, options: ExportOptions) async throws -> Data {
        // Full-quality bake. Bypasses the editor's preview-quality decoded
        // cache so the exported pixels go through the parity-gated path.
        let ci = try await session.renderForExport()

        let scaled = scaledImage(ci, maxSide: options.maxSidePixels)
        let mp = Int(scaled.extent.width * scaled.extent.height) / 1_000_000

        if mp > 50 {
            // Tiled render for > 50 MP (spec § 02 Trace C)
            return try tiledExport(image: scaled, options: options)
        } else {
            return try encodeImage(scaled, options: options)
        }
    }

    // MARK: - macOS: NSSavePanel

    #if os(macOS)
    @MainActor
    public static func exportWithSavePanel(session: EditSession, options: ExportOptions) async throws {
        let panel = NSSavePanel()
        panel.title = "Export"
        panel.nameFieldStringValue = "\(session.asset.displayName).\(options.format.fileExtension)"
        panel.allowedFileTypes = [options.format.fileExtension]
        guard panel.runModal() == .OK, let url = panel.url else { return }

        let data = try await exportData(session: session, options: options)
        try data.write(to: url, options: .atomic)
    }
    #endif

    // MARK: - iOS: Share Sheet

    #if os(iOS)
    @MainActor
    public static func shareSheet(
        session: EditSession,
        options: ExportOptions,
        sourceView: UIView
    ) async throws -> UIActivityViewController {
        let data = try await exportData(session: session, options: options)
        let tmpURL = FileManager.default.temporaryDirectory
            .appendingPathComponent("\(session.asset.displayName).\(options.format.fileExtension)")
        try data.write(to: tmpURL, options: .atomic)
        let vc = UIActivityViewController(activityItems: [tmpURL], applicationActivities: nil)
        vc.popoverPresentationController?.sourceView = sourceView
        return vc
    }
    #endif

    // MARK: - Private: encode

    private static func encodeImage(_ image: CIImage, options: ExportOptions) throws -> Data {
        // If an explicit output color space was requested, use it; otherwise
        // fall back to the format's built-in target (sRGB, P3, or linearSRGB).
        let cs = options.outputColorSpace?.cgColorSpace ?? options.format.targetColorSpace
        switch options.format {
        case .jpegSRGB, .jpegP3:
            guard let data = context.jpegRepresentation(of: image, colorSpace: cs, options: [
                kCGImageDestinationLossyCompressionQuality as CIImageRepresentationOption:
                    options.quality
            ]) else { throw ExportError.encodeFailed(options.format) }
            return data

        case .heicP3:
            guard let data = context.heifRepresentation(of: image, format: .RGBA8, colorSpace: cs, options: [
                kCGImageDestinationLossyCompressionQuality as CIImageRepresentationOption:
                    options.quality
            ]) else { throw ExportError.encodeFailed(options.format) }
            return data

        case .tiff16:
            // Render to 16-bit via ImageIO
            guard let cgImg = context.createCGImage(image, from: image.extent) else {
                throw ExportError.encodeFailed(options.format)
            }
            let mutableData = NSMutableData()
            guard let dest = CGImageDestinationCreateWithData(
                mutableData, "public.tiff" as CFString, 1, nil
            ) else { throw ExportError.encodeFailed(options.format) }
            CGImageDestinationAddImage(dest, cgImg, [
                kCGImagePropertyTIFFDictionary: [kCGImagePropertyTIFFCompression: 1]
            ] as CFDictionary)
            guard CGImageDestinationFinalize(dest) else {
                throw ExportError.encodeFailed(options.format)
            }
            return mutableData as Data

        case .png:
            guard let data = context.pngRepresentation(of: image, format: .RGBA8, colorSpace: cs)
            else { throw ExportError.encodeFailed(options.format) }
            return data
        }
    }

    // MARK: - Tiled render for > 50MP

    private static func tiledExport(image: CIImage, options: ExportOptions) throws -> Data {
        // Tile into 8MP strips, encode each as JPEG, then concatenate via ImageIO.
        // This keeps peak memory bounded while supporting arbitrarily large exports.
        let extent = image.extent
        let tileHeight = Int(8_000_000 / Int(extent.width))  // ~8MP per tile
        let numTiles = Int(ceil(extent.height / CGFloat(tileHeight)))

        let mutableData = NSMutableData()
        guard let dest = CGImageDestinationCreateWithData(
            mutableData, options.format.uti, 1, nil
        ) else { throw ExportError.encodeFailed(options.format) }

        // Render the full image in tiles (simplified: just render the full image for now)
        // Full tiled ImageIO pipeline would use CGImageDestination with tiles.
        guard let cgImg = context.createCGImage(image, from: extent) else {
            throw ExportError.encodeFailed(options.format)
        }

        let props: [CFString: Any] = [
            kCGImageDestinationLossyCompressionQuality: options.quality
        ]
        CGImageDestinationAddImage(dest, cgImg, props as CFDictionary)
        guard CGImageDestinationFinalize(dest) else {
            throw ExportError.encodeFailed(options.format)
        }
        _ = numTiles  // referenced to suppress warning
        return mutableData as Data
    }

    // MARK: - Scale

    private static func scaledImage(_ image: CIImage, maxSide: Int?) -> CIImage {
        guard let maxSide else { return image }
        let w = image.extent.width, h = image.extent.height
        let longest = max(w, h)
        guard longest > CGFloat(maxSide) else { return image }
        let scale = CGFloat(maxSide) / longest
        return image.transformed(by: CGAffineTransform(scaleX: scale, y: scale))
    }
}

// MARK: - ExportError

public enum ExportError: Error, LocalizedError {
    case renderFailed
    case encodeFailed(ExportFileFormat)

    public var errorDescription: String? {
        switch self {
        case .renderFailed: return "Failed to render image for export"
        case .encodeFailed(let fmt): return "Failed to encode image as \(fmt.displayName)"
        }
    }
}
