// src/apple/Packages/MapleCore/Tests/MapleCoreTests/HashingTests.swift
//
// Unit tests for the BLAKE3 Swift wrapper in Hashing.swift.
//
// BLAKE3 test vectors sourced from the upstream reference implementation
// (https://github.com/BLAKE3-team/BLAKE3/blob/master/test_vectors/test_vectors.json).
// The "abc" vector hex was verified with `echo -n abc | b3sum`.

import XCTest
@testable import MapleCore

final class HashingTests: XCTestCase {

    func testBLAKE3HexOfKnownInput() {
        // BLAKE3 hex of the ASCII string "abc" — well-known test vector.
        let abc = Data("abc".utf8)
        let hex = BLAKE3.hex(abc)
        XCTAssertEqual(
            hex,
            "6437b3ac38465133ffb63b75273a8db548c558465d79db03fd359c6cd5bd9d85"
        )
    }

    func testBLAKE3HexOfEmptyDataReturnsNil() {
        XCTAssertNil(BLAKE3.hex(Data()))
    }

    func testBLAKE3HexLengthIs64() {
        let data = Data("hello world".utf8)
        let hex = BLAKE3.hex(data)
        XCTAssertEqual(hex?.count, 64)
    }

    func testBLAKE3HexIsLowercase() {
        let data = Data("hello".utf8)
        let hex = BLAKE3.hex(data)!
        XCTAssertEqual(hex, hex.lowercased())
    }

    func testBLAKE3HexDeterministic() {
        let data = Data("determinism check".utf8)
        let hex1 = BLAKE3.hex(data)
        let hex2 = BLAKE3.hex(data)
        XCTAssertEqual(hex1, hex2)
    }

    func testBLAKE3HexDifferentInputsDifferentHashes() {
        let h1 = BLAKE3.hex(Data("aaaa".utf8))
        let h2 = BLAKE3.hex(Data("aaab".utf8))
        XCTAssertNotEqual(h1, h2)
    }

    // MARK: - MapleId (spec-form, 32 chars)
    //
    // These mirror the server-side test cases at
    // `src/api/tests/indexer-id.test.ts` byte-for-byte. The expected hex
    // values were computed by the Rust raw-core reference (verified to
    // match the TS implementation by that test); the device must produce
    // the exact same bytes for backup dedup to fire on the server's
    // `findOne({ maple_id })` lookup.

    /// Primary-form id for 1024 ramp bytes + the canonical test inputs from
    /// `indexer-id.test.ts`. Locks the spec-form derivation to a single
    /// known hex so a future refactor in raw-ffi can't silently drift.
    /// Expected value generated by running `raw_core::MapleId::primary`
    /// directly on the same inputs — the indexer's TS implementation
    /// asserts the same vector at `src/api/tests/indexer-id.test.ts` (vector
    /// "1024 ramp, SN-1234, 4242").
    func testMapleIdPrimaryMatchesServerVector() {
        var bytes = [UInt8](repeating: 0, count: 1024)
        for i in 0..<bytes.count { bytes[i] = UInt8(i & 0xff) }
        let data = Data(bytes)
        let hex = MapleId.primary(
            headBytes: data,
            capturedAtISO8601: "2024:06:01 12:34:56",
            cameraSerial: "SN-1234",
            shutterCount: 4242
        )
        XCTAssertEqual(hex, "014866c913dfe35e7b9618b709827be9")
    }

    /// Cross-implementation parity vector: the same byte stream and
    /// timestamp computed with absent serial / zero shutter must produce
    /// the canonical hex `01378688bcd9f3c9a9e37159ada21f10`. This is the
    /// real-world path (the indexer currently passes `null` for serial and
    /// shutter), so any divergence on this case breaks server dedup.
    func testMapleIdPrimaryParityNoSerialNoShutter() {
        var bytes = [UInt8](repeating: 0, count: 1024)
        for i in 0..<bytes.count { bytes[i] = UInt8(i & 0xff) }
        let hex = MapleId.primary(
            headBytes: Data(bytes),
            capturedAtISO8601: "2024:06:01 12:34:56"
        )
        XCTAssertEqual(hex, "01378688bcd9f3c9a9e37159ada21f10")
    }

    /// Same as `testMapleIdPrimaryMatchesServerVector` but with absent
    /// serial + zero shutter — covers the FFI's null-pointer path for
    /// serial and the spec's `None ≡ Some(0)` shutter behaviour.
    func testMapleIdPrimaryAbsentSerialAndShutter() {
        let data = Data([1, 2, 3, 4, 5])
        let hex = MapleId.primary(
            headBytes: data,
            capturedAtISO8601: "2024:06:01 12:34:56"
        )
        // Sanity: 32 hex chars, primary tag.
        XCTAssertEqual(hex?.count, 32)
        XCTAssertEqual(hex?.prefix(2), "01")
        // Determinism — same inputs hash to the same output.
        let again = MapleId.primary(
            headBytes: data,
            capturedAtISO8601: "2024:06:01 12:34:56",
            cameraSerial: nil,
            shutterCount: 0
        )
        XCTAssertEqual(hex, again)
    }

    /// `None` serial and `Some(0)` shutter must hash identically to the
    /// "absent" forms — the FFI's `serial_ptr == null` path and
    /// `shutter_count == 0` value must reproduce raw-core's `None` branch.
    func testMapleIdPrimaryEmptyStringSerialEqualsNil() {
        let data = Data([9, 9, 9, 9, 9, 9, 9, 9])
        let a = MapleId.primary(headBytes: data, capturedAtISO8601: "2024:06:01 00:00:00")
        let b = MapleId.primary(
            headBytes: data,
            capturedAtISO8601: "2024:06:01 00:00:00",
            cameraSerial: "",
            shutterCount: 0
        )
        XCTAssertEqual(a, b)
    }

    /// Fallback-form id for a 512-byte ramp — pinned to the same vector as
    /// the server test, so the device's FFI output and the indexer's
    /// `deriveId` branch agree on a single canonical hex. Computed from
    /// `raw_core::MapleId::fallback` on the inputs in
    /// `src/api/tests/indexer-id.test.ts` ("512 step-7").
    func testMapleIdFallbackMatchesServerVector() {
        var bytes = [UInt8](repeating: 0, count: 512)
        for i in 0..<bytes.count { bytes[i] = UInt8((i * 7) & 0xff) }
        let hex = MapleId.fallback(bytes: Data(bytes))
        XCTAssertEqual(hex, "021ee2b82d3019e91bf272ccb95bb8bb")
    }

    func testMapleIdFallbackEmptyReturnsNil() {
        XCTAssertNil(MapleId.fallback(bytes: Data()))
    }

    func testMapleIdPrimaryEmptyHeadOrTsReturnsNil() {
        XCTAssertNil(MapleId.primary(headBytes: Data(), capturedAtISO8601: "x"))
        XCTAssertNil(MapleId.primary(headBytes: Data([0]), capturedAtISO8601: ""))
    }

    /// Primary and fallback ids over the same bytes must NEVER collide —
    /// the leading tag byte (0x01 vs 0x02) is the spec's collision guard
    /// between the two derivations.
    func testMapleIdPrimaryFallbackNeverCollide() {
        let data = Data(repeating: 0xab, count: 256)
        let p = MapleId.primary(headBytes: data, capturedAtISO8601: "2024:06:01 12:34:56")
        let f = MapleId.fallback(bytes: data)
        XCTAssertNotNil(p)
        XCTAssertNotNil(f)
        XCTAssertNotEqual(p, f)
        XCTAssertEqual(p?.prefix(2), "01")
        XCTAssertEqual(f?.prefix(2), "02")
    }
}
