// WebglParityFixtureGenerator.swift — Plan 3 M2.1 Task 9.
//
// Renders the WebGL parity reference PNG (16x16) by feeding the
// synthesized fp16 RGBA input from the Web side through Apple's
// `processSceneLinear` Metal pipeline. The PNG is committed at
// `src/web/projects/maple-common/src/lib/webgl/dev/fixtures/reference.png`
// so the standalone WebGL test page (and the vitest snapshot spec)
// can diff their candidate against an Apple-rendered ground truth.
//
// Inputs:
//   - synthetic-input.bin (2048 bytes, 16x16 fp16 RGBA, src/web/.../webgl/dev/fixtures/)
//   - The same AdjustmentModel the WebGL test page uses (see
//     `Self.fixtureModel` below — exposure 1.0 / contrast 25 / etc.).
//
// Output:
//   - reference.png (16x16 sRGB-encoded RGBA8) under the same fixtures dir.
//
// Re-run when:
//   - Any Apple Metal kernel constant changes.
//   - AdjustmentModel slider semantics change in raw-core / Apple.
//   - The synthesized input is regenerated by
//     src/web/projects/maple-common/src/lib/webgl/dev/fixtures/scripts/generate-synthetic-input.ts.
//
// This test is meant to be run manually (or in nightly CI on a macOS
// runner) — it always fails on the first run with a "baseline written"
// XCTFail (per `GoldenStore.compareOrRecord`'s convention) and
// produces the PNG. Subsequent runs assert ΔE budgets.

import XCTest
import CoreImage
import CoreGraphics
import AppKit
@testable import MapleCore

final class WebglParityFixtureGenerator: XCTestCase {

    // MARK: - Repo / fixture resolution

    /// Walk from `#filePath` to the repo root.
    /// `.../src/apple/Packages/MapleCore/Tests/MapleCoreTests/Self.swift`
    /// → 7 levels up.
    private static func repoRoot() -> URL {
        return URL(fileURLWithPath: #filePath)
            .deletingLastPathComponent()  // MapleCoreTests/
            .deletingLastPathComponent()  // Tests/
            .deletingLastPathComponent()  // MapleCore/
            .deletingLastPathComponent()  // Packages/
            .deletingLastPathComponent()  // apple/
            .deletingLastPathComponent()  // src/
            .deletingLastPathComponent()  // repo root
    }

    private static func webFixtureDir() -> URL {
        return repoRoot().appendingPathComponent(
            "src/web/projects/maple-common/src/lib/webgl/dev/fixtures"
        )
    }

    /// AdjustmentModel — must mirror the Web side's `FIXTURE_MODEL` in
    /// `webgl-test-page.component.ts` and `pipeline.spec.ts` exactly.
    /// Re-record `reference.png` when this changes.
    private static var fixtureModel: AdjustmentModel {
        var m = AdjustmentModel.default
        m.exposure = 1.0
        m.contrast = 25
        m.highlights = -30
        m.shadows = 40
        m.whites = 0
        m.blacks = 0
        m.temperature = 5500
        m.tint = -10
        m.vibrance = 50
        m.saturation = -20
        return m
    }

    // MARK: - PNG encoding helper (sRGB output)

    private static func pngData(from cgImage: CGImage) -> Data? {
        let rep = NSBitmapImageRep(cgImage: cgImage)
        return rep.representation(using: .png, properties: [:])
    }

    // MARK: - Test

    /// Renders the WebGL parity reference PNG. First run writes the
    /// baseline + XCTFails ("baseline written"); subsequent runs diff
    /// against the committed PNG with the same ΔE budgets the Apple
    /// SceneLinearVisualRegressionTests use (mean ≤ 5, p95 ≤ 10,
    /// max ≤ 30, bias ≤ 0.05).
    func testGenerateWebglParityReference() async throws {
        let inputURL = Self.webFixtureDir()
            .appendingPathComponent("synthetic-input.bin")
        guard FileManager.default.fileExists(atPath: inputURL.path) else {
            XCTFail("Missing fp16 input fixture at \(inputURL.path) — " +
                    "run `bun run src/web/projects/maple-common/src/lib/webgl/dev/fixtures/scripts/generate-synthetic-input.ts` first.")
            return
        }
        let inputBytes = try Data(contentsOf: inputURL)
        guard inputBytes.count == 16 * 16 * 4 * 2 else {
            XCTFail("synthetic-input.bin: expected 2048 bytes (16x16 fp16 RGBA), got \(inputBytes.count)")
            return
        }

        // Wrap fp16 RGBA as a CIImage tagged extendedLinearITUR_2020 — the
        // same path ImageEditPipeline.decodeSceneLinear uses to hand the
        // Rust-decoded buffer to Core Image.
        let space = CGColorSpace(name: CGColorSpace.extendedLinearITUR_2020)!
        let bytesPerRow = 16 * 4 * 2 // 4 channels × 2 bytes per fp16 lane
        let decoded: CIImage = inputBytes.withUnsafeBytes { rawBuf -> CIImage in
            let pixels = Data(rawBuf)
            return CIImage(
                bitmapData: pixels,
                bytesPerRow: bytesPerRow,
                size: CGSize(width: 16, height: 16),
                format: .RGBAh,
                colorSpace: space
            )
        }

        let pipeline = ImageEditPipeline()
        let processed = pipeline.processSceneLinear(
            decoded: decoded,
            model: Self.fixtureModel,
            targetSize: nil,
            asShot: nil
        )

        let workingSpace = CGColorSpace(name: CGColorSpace.extendedLinearSRGB)!
        let outputSpace = CGColorSpace(name: CGColorSpace.sRGB)!
        let ciContext: CIContext
        if let device = MTLCreateSystemDefaultDevice() {
            ciContext = CIContext(mtlDevice: device, options: [
                .workingColorSpace: workingSpace,
                .workingFormat: CIFormat.RGBAh,
                .cacheIntermediates: false,
            ])
        } else {
            ciContext = CIContext(options: [
                .workingColorSpace: workingSpace,
                .workingFormat: CIFormat.RGBAh,
                .cacheIntermediates: false,
            ])
        }

        guard let cg = ciContext.createCGImage(
            processed,
            from: CGRect(x: 0, y: 0, width: 16, height: 16),
            format: .RGBA8,
            colorSpace: outputSpace
        ) else {
            XCTFail("createCGImage returned nil for processed CIImage")
            return
        }
        guard let png = Self.pngData(from: cg) else {
            XCTFail("Failed to encode rendered CGImage to PNG")
            return
        }

        // Write the PNG into the Web fixtures dir AND record-or-compare via
        // GoldenStore (so first-run + diff semantics are consistent with
        // the rest of the Apple visual harness).
        let referenceURL = Self.webFixtureDir().appendingPathComponent("reference.png")
        try FileManager.default.createDirectory(
            at: referenceURL.deletingLastPathComponent(),
            withIntermediateDirectories: true
        )

        let isFirstRun = !FileManager.default.fileExists(atPath: referenceURL.path)
        try png.write(to: referenceURL)
        if isFirstRun {
            XCTFail("baseline written at \(referenceURL.path) — " +
                    "open it, verify it looks correct, then commit + re-run.")
        }

        // Also feed the committed Apple-UITests goldens directory so the
        // file is reachable from the same tooling the rest of the visual
        // harness uses.
        try GoldenStore.compareOrRecord(
            name: "webgl-parity-reference",
            candidate: png,
            budget: GoldenBudget(mean: 5, p95: 10, max: 30, bias: 0.05)
        )
    }
}
