// WebglParityFixtureGenerator.swift — Plan 3 M2.1 Task 9.
//
// Renders the WebGL parity reference PNG (16x16) by feeding the
// synthesized fp16 RGBA input from the Web side through Apple's
// Metal kernels — restricted to the **same five stages** the WebGL2
// dev-chain implements (Plan 3 M2.1 cut, see
// `src/web/projects/maple-common/src/lib/webgl/pipeline.ts`):
//
//   1. WhiteBalance
//   2. SceneToneControls
//   3. SceneVibrance
//   4. SceneSaturation
//   5. AgXViewTransform
//
// Apple's production `processSceneLinear` chain runs **eleven** stages
// — the five above plus SceneClarity, SceneTexture, SceneDehaze,
// SceneSharpen, SceneNRLuminance, SceneNRColor. Routing the fixture
// through `processSceneLinear` therefore inflates the parity gap
// because:
//   • `AdjustmentModel.default.nrColor == 25` runs the NR-color stage by
//     default (see noise_reduction.rs:61-96 / the kernel comment in
//     ImageEditPipeline.swift:415-423), shifting Oklab a/b chroma.
//   • The other four absent-from-WebGL stages are zero in the fixture
//     model, but their kernels still cost a ping-pong texture round-
//     trip — fp16 quantisation drifts each pass.
//
// The pre-Plan-3 generator routed the fixture through `processSceneLinear`
// and produced a reference PNG that contained those extra-stage
// contributions, raising apparent ΔE to 5.87 / max 57 against the
// WebGL2 candidate. The fix lives in this generator (the WebGL chain
// is correct as-is): call only the five Metal kernels the Web side
// implements, in the same order, with the same uniforms.
//
// Cross-references:
//   - Plan: docs/superpowers/plans/2026-04-25-plan-3-m2-webgl-shaders.md
//   - WebGL chain: src/web/projects/maple-common/src/lib/webgl/pipeline.ts
//   - Inline AgX poly (ticket #08, Apple commit 8ff4142): the WebGL
//     shader uses the closed-form 6-piece polynomial; the Apple kernel
//     in this branch still samples a 512-entry LUT baked from the
//     same polynomial (`src/scripts/derive_agx_lut.py:72-104` /
//     `src/raw-pipeline/raw-core/src/view/agx_coeffs.rs`). The two
//     paths agree to << 1 ΔE on the fixture's tonal range — confirmed
//     by the post-fix measurement; see commit message.
//
// Inputs:
//   - synthetic-input.bin (2048 bytes, 16x16 fp16 RGBA, src/web/.../webgl/dev/fixtures/)
//   - The same AdjustmentModel the WebGL test page uses (see
//     `Self.fixtureModel` below — exposure 1.0 / contrast 25 / etc.).
//
// Output:
//   - reference.png (16x16 sRGB-encoded RGBA8) under the same fixtures dir.
//
// Re-run when:
//   - Any Apple Metal kernel constant changes (specifically the five
//     stages this generator invokes).
//   - AdjustmentModel slider semantics change in raw-core / Apple.
//   - The WebGL chain gains a stage Apple already has — extend this
//     generator to mirror the new chain, NOT to call the production
//     `processSceneLinear`.
//   - The synthesized input is regenerated by
//     src/web/projects/maple-common/src/lib/webgl/dev/fixtures/scripts/generate-synthetic-input.ts.
//
// This test is meant to be run manually (or in nightly CI on a macOS
// runner) — it always fails on the first run with a "baseline written"
// XCTFail (per `GoldenStore.compareOrRecord`'s convention) and
// produces the PNG. Subsequent runs assert ΔE budgets.

import XCTest
import CoreImage
import CoreGraphics
import AppKit
@testable import MapleCore

final class WebglParityFixtureGenerator: XCTestCase {

    // MARK: - Repo / fixture resolution

    /// Walk from `#filePath` to the repo root.
    /// `.../src/apple/Packages/MapleCore/Tests/MapleCoreTests/Self.swift`
    /// → 7 levels up.
    private static func repoRoot() -> URL {
        return URL(fileURLWithPath: #filePath)
            .deletingLastPathComponent()  // MapleCoreTests/
            .deletingLastPathComponent()  // Tests/
            .deletingLastPathComponent()  // MapleCore/
            .deletingLastPathComponent()  // Packages/
            .deletingLastPathComponent()  // apple/
            .deletingLastPathComponent()  // src/
            .deletingLastPathComponent()  // repo root
    }

    private static func webFixtureDir() -> URL {
        return repoRoot().appendingPathComponent(
            "src/web/projects/maple-common/src/lib/webgl/dev/fixtures"
        )
    }

    /// AdjustmentModel — must mirror the Web side's `FIXTURE_MODEL` in
    /// `webgl-test-page.component.ts` and `pipeline.spec.ts` exactly.
    /// Re-record `reference.png` when this changes.
    private static var fixtureModel: AdjustmentModel {
        var m = AdjustmentModel.default
        m.exposure = 1.0
        m.contrast = 25
        m.highlights = -30
        m.shadows = 40
        m.whites = 0
        m.blacks = 0
        m.temperature = 5500
        m.tint = -10
        m.vibrance = 50
        m.saturation = -20
        return m
    }

    // MARK: - PNG encoding helper (sRGB output)

    private static func pngData(from cgImage: CGImage) -> Data? {
        let rep = NSBitmapImageRep(cgImage: cgImage)
        return rep.representation(using: .png, properties: [:])
    }

    // MARK: - Test

    /// Renders the WebGL parity reference PNG. First run writes the
    /// baseline + XCTFails ("baseline written"); subsequent runs diff
    /// against the committed PNG with the same ΔE budgets the Apple
    /// SceneLinearVisualRegressionTests use (mean ≤ 5, p95 ≤ 10,
    /// max ≤ 30, bias ≤ 0.05).
    func testGenerateWebglParityReference() async throws {
        let inputURL = Self.webFixtureDir()
            .appendingPathComponent("synthetic-input.bin")
        guard FileManager.default.fileExists(atPath: inputURL.path) else {
            XCTFail("Missing fp16 input fixture at \(inputURL.path) — " +
                    "run `bun run src/web/projects/maple-common/src/lib/webgl/dev/fixtures/scripts/generate-synthetic-input.ts` first.")
            return
        }
        let inputBytes = try Data(contentsOf: inputURL)
        guard inputBytes.count == 16 * 16 * 4 * 2 else {
            XCTFail("synthetic-input.bin: expected 2048 bytes (16x16 fp16 RGBA), got \(inputBytes.count)")
            return
        }

        // Wrap fp16 RGBA as a CIImage tagged extendedLinearITUR_2020 — the
        // same path ImageEditPipeline.decodeSceneLinear uses to hand the
        // Rust-decoded buffer to Core Image.
        let space = CGColorSpace(name: CGColorSpace.extendedLinearITUR_2020)!
        let bytesPerRow = 16 * 4 * 2 // 4 channels × 2 bytes per fp16 lane
        let decoded: CIImage = inputBytes.withUnsafeBytes { rawBuf -> CIImage in
            let pixels = Data(rawBuf)
            return CIImage(
                bitmapData: pixels,
                bytesPerRow: bytesPerRow,
                size: CGSize(width: 16, height: 16),
                format: .RGBAh,
                colorSpace: space
            )
        }

        // Five-stage WebGL-parity chain — mirrors pipeline.ts exactly.
        // We deliberately bypass `ImageEditPipeline.processSceneLinear`
        // because the production chain runs six additional stages the
        // WebGL2 M2.1 dev-chain does not (Clarity / Texture / Dehaze /
        // Sharpen / NRLuminance / NRColor — the latter is non-zero by
        // default at `AdjustmentModel.default.nrColor == 25`). See the
        // file header for the full rationale.
        let model = Self.fixtureModel
        // WhiteBalance: identity short-circuit when live == decoded
        // (matches WebGL test page wiring at webgl-test-page.component.ts:91-98,
        //  which feeds `asShotTemperature: 6500, asShotTint: 0` and the
        //  Apple kernel's fallback at ImageEditPipeline.swift:304-305).
        var img = MetalKernels.applyWhiteBalance(
            to: decoded,
            liveTemperature: Float(model.temperature),
            liveTint: Float(model.tint),
            decodedTemperature: 6500,
            decodedTint: 0
        )
        img = MetalKernels.applySceneToneControls(
            to: img,
            exposure: Float(model.exposure),
            highlights: Float(model.highlights),
            shadows: Float(model.shadows),
            whites: Float(model.whites),
            blacks: Float(model.blacks)
        )
        img = MetalKernels.applySceneVibrance(
            to: img, vibrance: Float(model.vibrance)
        )
        img = MetalKernels.applySceneSaturation(
            to: img, saturation: Float(model.saturation)
        )
        let processed = MetalKernels.applyAgXViewTransform(
            to: img, contrast: Float(model.contrast)
        )

        let workingSpace = CGColorSpace(name: CGColorSpace.extendedLinearSRGB)!
        let outputSpace = CGColorSpace(name: CGColorSpace.sRGB)!
        let ciContext: CIContext
        if let device = MTLCreateSystemDefaultDevice() {
            ciContext = CIContext(mtlDevice: device, options: [
                .workingColorSpace: workingSpace,
                .workingFormat: CIFormat.RGBAh,
                .cacheIntermediates: false,
            ])
        } else {
            ciContext = CIContext(options: [
                .workingColorSpace: workingSpace,
                .workingFormat: CIFormat.RGBAh,
                .cacheIntermediates: false,
            ])
        }

        guard let cg = ciContext.createCGImage(
            processed,
            from: CGRect(x: 0, y: 0, width: 16, height: 16),
            format: .RGBA8,
            colorSpace: outputSpace
        ) else {
            XCTFail("createCGImage returned nil for processed CIImage")
            return
        }
        guard let png = Self.pngData(from: cg) else {
            XCTFail("Failed to encode rendered CGImage to PNG")
            return
        }

        // Write the PNG into the Web fixtures dir AND record-or-compare via
        // GoldenStore (so first-run + diff semantics are consistent with
        // the rest of the Apple visual harness).
        let referenceURL = Self.webFixtureDir().appendingPathComponent("reference.png")
        try FileManager.default.createDirectory(
            at: referenceURL.deletingLastPathComponent(),
            withIntermediateDirectories: true
        )

        let isFirstRun = !FileManager.default.fileExists(atPath: referenceURL.path)
        try png.write(to: referenceURL)
        if isFirstRun {
            XCTFail("baseline written at \(referenceURL.path) — " +
                    "open it, verify it looks correct, then commit + re-run.")
        }

        // Also feed the committed Apple-UITests goldens directory so the
        // file is reachable from the same tooling the rest of the visual
        // harness uses.
        try GoldenStore.compareOrRecord(
            name: "webgl-parity-reference",
            candidate: png,
            budget: GoldenBudget(mean: 5, p95: 10, max: 30, bias: 0.05)
        )
    }
}
