//! Native-target tests for the wasm-bindgen entries — split from `lib.rs`
//! to keep it under the file-size budget. `use super::*` = the crate root,
//! exactly as the previously-inline `mod tests` saw it.

use super::*;

/// Byte-identity (#817): the WASM `compute_profile_lut` MUST return the
/// exact bytes `raw_core::view::auto_profile::bake_profile_lut` produces —
/// the same core fn the Apple `maple_compute_profile_lut` FFI calls. So
/// WASM == core and (asserted in raw-ffi) FFI == core, giving web + Apple
/// byte-identical LUTs by construction. Runs as a plain native test
/// (the binding is ordinary Rust off wasm32).
#[test]
fn compute_profile_lut_matches_raw_core_bake() {
    use raw_core::view::auto_profile::{
        bake_profile_lut, ChannelCurve, ProfileCurve, DEFAULT_LUT_SIZE,
    };
    // Distinct per-channel curve (mirrors the raw-core golden test) so the
    // identity check exercises a non-trivial LUT.
    let mut curve = ProfileCurve::identity();
    let shape = |i: usize, exp: f32, lift: f32| {
        let x = i as f32 / 31.0;
        let y = lift + (1.0 - lift) * x.powf(exp);
        (x, y.clamp(0.0, 1.0))
    };
    let (mut r, mut g, mut b) = (
        ChannelCurve::identity(),
        ChannelCurve::identity(),
        ChannelCurve::identity(),
    );
    for i in 0..32 {
        r.anchors[i] = shape(i, 0.7, 0.05);
        g.anchors[i] = shape(i, 1.0, 0.0);
        b.anchors[i] = shape(i, 1.4, 0.0);
    }
    curve.r = r;
    curve.g = g;
    curve.b = b;

    let flat = curve.to_flat();
    let n = DEFAULT_LUT_SIZE;
    let via_wasm = compute_profile_lut(&flat, n as u32).expect("bake ok");
    let via_core = bake_profile_lut(&curve, n);
    assert_eq!(via_wasm, via_core, "WASM LUT must equal raw-core bake");
}

// The error paths construct a `JsError`, which is a wasm-bindgen import
// that traps on non-wasm targets — so the `Err(..)` arms can't be
// exercised by native `cargo test` (calling `compute_profile_lut` with a
// rejected `n` would trap, not return). The reject logic (`n < 2`,
// `n > MAX_LUT_SIZE`, wrong curve_len) is identical to the raw-ffi
// error-path tests (`profile_lut_degenerate_n_returns_error`,
// `profile_lut_oversized_n_returns_error`, `profile_lut_wrong_curve_len_*`),
// which DO run natively and share the same `MAX_LUT_SIZE` constant.
// Natively we CAN assert the accepted boundary `n = MAX_LUT_SIZE` returns
// Ok with the full grid (the success arm builds no `JsError`).
#[test]
fn compute_profile_lut_accepts_n_bounds() {
    use raw_core::view::auto_profile::{ProfileCurve, MAX_LUT_SIZE};
    let flat = ProfileCurve::identity().to_flat();
    // Floor: n = 2 succeeds.
    let lo = compute_profile_lut(&flat, 2).expect("n=2 bakes");
    assert_eq!(lo.len(), 2 * 2 * 2 * 3);
    // Ceiling: n = MAX_LUT_SIZE succeeds (boundary is inclusive).
    let hi = compute_profile_lut(&flat, MAX_LUT_SIZE as u32).expect("n=MAX bakes");
    assert_eq!(hi.len(), MAX_LUT_SIZE * MAX_LUT_SIZE * MAX_LUT_SIZE * 3);
}

/// Synthesized 8x8 mosaic round-trip — proves the new entry returns
/// fp16 RGBA with alpha lane = 0x3c00 (fp16 1.0) and a buffer length
/// of 8*w*h bytes (i.e. 4 channels * 2 bytes/lane * w * h).
///
/// We don't have a fixture DNG checked in (raws are gitignored), but
/// the function is layered on `raw_core::pipeline::render_scene_linear_*`
/// which has its own fixture-gated tests upstream. This test instead
/// uses the smallest valid synthetic input we can: a tiny embedded DNG
/// generated by `cargo test -p raw-core` fixtures. Skip when the
/// fixture isn't available.
#[test]
#[ignore = "requires test-fixtures/raws/* (gitignored); run with --ignored"]
fn render_bytes_scene_linear_returns_fp16_rgba_with_alpha_one() {
    // Path mirror of the helper test in raw-core; this test only runs
    // when the engineer has the fixtures locally.
    let path = std::path::PathBuf::from(std::env::var("CARGO_MANIFEST_DIR").unwrap())
        .join("../test-fixtures/raws/dji-mavic3pro-100mp.dng");
    if !path.exists() {
        eprintln!("fixture missing at {:?} — skipping", path);
        return;
    }
    let bytes = std::fs::read(&path).expect("read fixture");
    let result =
        render_bytes_scene_linear(&bytes, "dng", None, true).expect("render_bytes_scene_linear ok");
    let w = result.width();
    let h = result.height();
    assert!(w > 0 && h > 0, "non-zero dimensions");
    let lanes: Vec<u16> = result.fp16_rgba();
    assert_eq!(
        lanes.len(),
        (w as usize) * (h as usize) * 4,
        "expected 4 fp16 lanes per pixel (RGBA)"
    );
    // Alpha lane (every 4th u16) must be fp16 1.0 = 0x3c00.
    // Sample the first 16 pixels — covers the top-left tile and is
    // cheap.
    for i in 0..16.min(w as usize * h as usize) {
        let alpha = lanes[i * 4 + 3];
        assert_eq!(
            alpha, 0x3c00,
            "pixel {} alpha was 0x{:04x}, expected fp16 1.0 (0x3c00)",
            i, alpha
        );
    }
    // Sanity: at least one of the first 256 R/G/B lanes is non-zero
    // (the synthetic input has signal).
    let any_nonzero_rgb = (0..256.min(w as usize * h as usize))
        .any(|i| lanes[i * 4] != 0 || lanes[i * 4 + 1] != 0 || lanes[i * 4 + 2] != 0);
    assert!(
        any_nonzero_rgb,
        "all R/G/B lanes were zero — pipeline failure"
    );
}

/// Repo-root fixture path (raw-wasm sits two levels below src/). Skip-pass
/// when the gitignored RAW is absent, mirroring the raw-core pattern.
fn fixture_path() -> Option<std::path::PathBuf> {
    let path = std::path::PathBuf::from(env!("CARGO_MANIFEST_DIR"))
        .join("../../../test-fixtures/raws/test_0002.dng");
    if path.exists() {
        Some(path)
    } else {
        eprintln!("fixture missing at {:?} — skipping", path);
        None
    }
}

/// #1101: the sized scene-linear entry respects the long-edge cap, keeps
/// the fp16 RGBA contract (alpha = 0x3c00), and reports native dims that
/// match raw-core's `native_render_dims`.
#[test]
fn render_bytes_scene_linear_sized_caps_long_edge_and_reports_native_dims() {
    let Some(path) = fixture_path() else { return };
    let bytes = std::fs::read(&path).expect("read fixture");
    let cap = 768u32;
    let result = render_bytes_scene_linear_sized(&bytes, "dng", None, true, cap)
        .expect("sized scene-linear render ok");
    let (w, h) = (result.width(), result.height());
    assert!(
        w.max(h) <= cap,
        "long edge {} exceeds cap {}",
        w.max(h),
        cap
    );
    let lanes: Vec<u16> = result.fp16_rgba();
    assert_eq!(
        lanes.len(),
        (w as usize) * (h as usize) * 4,
        "4 fp16 lanes per pixel"
    );
    assert_eq!(lanes[3], 0x3c00, "alpha lane must be fp16 1.0");

    let raw_img = raw_core::decode::decode_bytes(&bytes, "dng").expect("decode");
    let (nw, nh) = raw_core::pipeline::native_render_dims(&raw_img);
    assert_eq!(
        (result.full_width(), result.full_height()),
        (nw, nh),
        "full_* getters must carry the native oriented dims"
    );
    assert!(
        result.full_width().max(result.full_height()) > cap,
        "fixture should be larger than the cap for this test to be meaningful"
    );
}

/// #1101: the sized display entry respects the cap, reports native dims,
/// and keeps the `render_bytes` contract (RGB bytes + As-Shot WB seed).
#[test]
fn render_bytes_sized_caps_long_edge_and_matches_as_shot_seed() {
    let Some(path) = fixture_path() else { return };
    let bytes = std::fs::read(&path).expect("read fixture");
    let cap = 768u32;
    let sized =
        render_bytes_sized(&bytes, "dng", None, false, cap).expect("sized display render ok");
    let (w, h) = (sized.width(), sized.height());
    assert!(
        w.max(h) <= cap,
        "long edge {} exceeds cap {}",
        w.max(h),
        cap
    );
    assert_eq!(
        sized.rgb().len(),
        (w as usize) * (h as usize) * 3,
        "packed RGB bytes"
    );

    let raw_img = raw_core::decode::decode_bytes(&bytes, "dng").expect("decode");
    let (nw, nh) = raw_core::pipeline::native_render_dims(&raw_img);
    assert_eq!((sized.full_width(), sized.full_height()), (nw, nh));

    // As-Shot derivation must match the full-size entry bit-for-bit (the
    // sized cold open seeds the same WB sliders) — the slider-frame
    // estimate, not the retired log2(B/R) heuristic (#1892).
    let (expected_cct, expected_tint) = as_shot_wb(&raw_img);
    assert_eq!(sized.as_shot_temperature(), expected_cct);
    assert_eq!(sized.as_shot_tint(), expected_tint);
    // test_0002 (H2D-39) sits far off the Planckian locus — the estimate
    // must carry a real tint, where the old heuristic hard-coded 0.
    assert!(
        expected_tint.abs() > 1.0,
        "frame-consistent as-shot tint should be non-zero for this fixture, got {expected_tint}"
    );
}

/// #1892: a fresh open (no XMP) must develop IDENTICALLY to an explicit
/// `crs:WhiteBalance="As Shot"` sidecar — both resolve to the As-Shot
/// sentinel; neither pushes the display estimate into the model. Pre-#1892
/// the fresh open substituted a heuristic CCT as an explicit target and the
/// two differed.
///
/// Compared on the SCENE-LINEAR entry (where white balance lives), not the
/// display entry: the display tail's Auto Profile fit shares a bytes-keyed
/// cache across render qualities, so concurrent tests rendering this same
/// fixture at a different quality can swap the cached fit between the two
/// renders and flake a display-byte compare (#924's sharing tradeoff).
#[test]
fn render_bytes_scene_linear_fresh_open_matches_as_shot_xmp() {
    let Some(path) = fixture_path() else { return };
    let bytes = std::fs::read(&path).expect("read fixture");
    let cap = 512u32;
    let fresh = render_bytes_scene_linear_sized(&bytes, "dng", None, true, cap)
        .expect("fresh-open develop");
    let as_shot_xmp = r#"<?xpacket begin="" id="W5M0MpCehiHzreSzNTczkc9d"?>
<x:xmpmeta xmlns:x="adobe:ns:meta/"><rdf:RDF xmlns:rdf="http://www.w3.org/1999/02/22-rdf-syntax-ns#">
<rdf:Description rdf:about="" xmlns:crs="http://ns.adobe.com/camera-raw-settings/1.0/" crs:WhiteBalance="As Shot"/>
</rdf:RDF></x:xmpmeta>
<?xpacket end="w"?>"#;
    let explicit =
        render_bytes_scene_linear_sized(&bytes, "dng", Some(as_shot_xmp.to_string()), true, cap)
            .expect("as-shot XMP develop");
    assert_eq!(
        fresh.fp16_rgba(),
        explicit.fp16_rgba(),
        "fresh open and explicit As-Shot XMP must develop byte-identically"
    );
}
