//! Native-target tests for the wasm-bindgen entries — split from `lib.rs`
//! to keep it under the file-size budget. `use super::*` = the crate root,
//! exactly as the previously-inline `mod tests` saw it.

use super::*;

/// Byte-identity (#817): the WASM `compute_profile_lut` MUST return the
/// exact bytes `raw_core::view::auto_profile::bake_profile_lut` produces —
/// the same core fn the Apple `maple_compute_profile_lut` FFI calls. So
/// WASM == core and (asserted in raw-ffi) FFI == core, giving web + Apple
/// byte-identical LUTs by construction. Runs as a plain native test
/// (the binding is ordinary Rust off wasm32).
#[test]
fn compute_profile_lut_matches_raw_core_bake() {
    use raw_core::view::auto_profile::{
        bake_profile_lut, ChannelCurve, ProfileCurve, DEFAULT_LUT_SIZE,
    };
    // Distinct per-channel curve (mirrors the raw-core golden test) so the
    // identity check exercises a non-trivial LUT.
    let mut curve = ProfileCurve::identity();
    let shape = |i: usize, exp: f32, lift: f32| {
        let x = i as f32 / 31.0;
        let y = lift + (1.0 - lift) * x.powf(exp);
        (x, y.clamp(0.0, 1.0))
    };
    let (mut r, mut g, mut b) = (
        ChannelCurve::identity(),
        ChannelCurve::identity(),
        ChannelCurve::identity(),
    );
    for i in 0..32 {
        r.anchors[i] = shape(i, 0.7, 0.05);
        g.anchors[i] = shape(i, 1.0, 0.0);
        b.anchors[i] = shape(i, 1.4, 0.0);
    }
    curve.r = r;
    curve.g = g;
    curve.b = b;

    let flat = curve.to_flat();
    let n = DEFAULT_LUT_SIZE;
    let via_wasm = compute_profile_lut(&flat, n as u32).expect("bake ok");
    let via_core = bake_profile_lut(&curve, n);
    assert_eq!(via_wasm, via_core, "WASM LUT must equal raw-core bake");
}

// The error paths construct a `JsError`, which is a wasm-bindgen import
// that traps on non-wasm targets — so the `Err(..)` arms can't be
// exercised by native `cargo test` (calling `compute_profile_lut` with a
// rejected `n` would trap, not return). The reject logic (`n < 2`,
// `n > MAX_LUT_SIZE`, wrong curve_len) is identical to the raw-ffi
// error-path tests (`profile_lut_degenerate_n_returns_error`,
// `profile_lut_oversized_n_returns_error`, `profile_lut_wrong_curve_len_*`),
// which DO run natively and share the same `MAX_LUT_SIZE` constant.
// Natively we CAN assert the accepted boundary `n = MAX_LUT_SIZE` returns
// Ok with the full grid (the success arm builds no `JsError`).
#[test]
fn compute_profile_lut_accepts_n_bounds() {
    use raw_core::view::auto_profile::{ProfileCurve, MAX_LUT_SIZE};
    let flat = ProfileCurve::identity().to_flat();
    // Floor: n = 2 succeeds.
    let lo = compute_profile_lut(&flat, 2).expect("n=2 bakes");
    assert_eq!(lo.len(), 2 * 2 * 2 * 3);
    // Ceiling: n = MAX_LUT_SIZE succeeds (boundary is inclusive).
    let hi = compute_profile_lut(&flat, MAX_LUT_SIZE as u32).expect("n=MAX bakes");
    assert_eq!(hi.len(), MAX_LUT_SIZE * MAX_LUT_SIZE * MAX_LUT_SIZE * 3);
}

/// Synthesized 8x8 mosaic round-trip — proves the new entry returns
/// fp16 RGBA with alpha lane = 0x3c00 (fp16 1.0) and a buffer length
/// of 8*w*h bytes (i.e. 4 channels * 2 bytes/lane * w * h).
///
/// We don't have a fixture DNG checked in (raws are gitignored), but
/// the function is layered on `raw_core::pipeline::render_scene_linear_*`
/// which has its own fixture-gated tests upstream. This test instead
/// uses the smallest valid synthetic input we can: a tiny embedded DNG
/// generated by `cargo test -p raw-core` fixtures. Skip when the
/// fixture isn't available.
#[test]
#[ignore = "requires test-fixtures/raws/* (gitignored); run with --ignored"]
fn render_bytes_scene_linear_returns_fp16_rgba_with_alpha_one() {
    // Repo-root fixture path (raw-wasm sits two levels below src/); this
    // test only runs when the engineer has the fixtures locally. (The
    // original `../test-fixtures` spelling resolved inside `src/raw-pipeline`
    // where no fixtures live, so the test always skipped — fixed with #2661.)
    let path = std::path::PathBuf::from(std::env::var("CARGO_MANIFEST_DIR").unwrap())
        .join("../../../test-fixtures/raws/dji-mavic3pro-100mp.dng");
    if !path.exists() {
        eprintln!("fixture missing at {:?} — skipping", path);
        return;
    }
    let bytes = std::fs::read(&path).expect("read fixture");
    let result =
        render_bytes_scene_linear(&bytes, "dng", None, true).expect("render_bytes_scene_linear ok");
    let w = result.width();
    let h = result.height();
    assert!(w > 0 && h > 0, "non-zero dimensions");
    let lanes: Vec<u16> = result.fp16_rgba();
    assert_eq!(
        lanes.len(),
        (w as usize) * (h as usize) * 4,
        "expected 4 fp16 lanes per pixel (RGBA)"
    );
    // Alpha lane (every 4th u16) must be fp16 1.0 = 0x3c00.
    // Sample the first 16 pixels — covers the top-left tile and is
    // cheap.
    for i in 0..16.min(w as usize * h as usize) {
        let alpha = lanes[i * 4 + 3];
        assert_eq!(
            alpha, 0x3c00,
            "pixel {} alpha was 0x{:04x}, expected fp16 1.0 (0x3c00)",
            i, alpha
        );
    }
    // Sanity: at least one of the first 256 R/G/B lanes is non-zero
    // (the synthetic input has signal).
    let any_nonzero_rgb = (0..256.min(w as usize * h as usize))
        .any(|i| lanes[i * 4] != 0 || lanes[i * 4 + 1] != 0 || lanes[i * 4 + 2] != 0);
    assert!(
        any_nonzero_rgb,
        "all R/G/B lanes were zero — pipeline failure"
    );
}

/// #2661: a sensor whose full-native-res CPU develop cannot fit the 4 GiB
/// wasm32 heap (the 100 MP reference measured 9.2 GB) must memory-clamp:
/// `render_bytes` develops through the sized chain at
/// `min(sensor_long_edge / 2, SIZED_DEVELOP_MAX_LONG_EDGE)` and reports the
/// native dims on `full_width`/`full_height` so caller zoom math is
/// unaffected. Before the clamp this exact call aborted the WASM instance
/// (`handle_alloc_error` → `unreachable`) from the no-WebGPU fallback.
#[test]
#[ignore = "requires test-fixtures/raws/* (gitignored, ~100 MP develop); run with --ignored"]
fn render_bytes_memory_clamps_sensors_too_large_for_the_wasm_heap() {
    let path = std::path::PathBuf::from(std::env::var("CARGO_MANIFEST_DIR").unwrap())
        .join("../../../test-fixtures/raws/dji-mavic3pro-100mp.dng");
    if !path.exists() {
        eprintln!("fixture missing at {:?} — skipping", path);
        return;
    }
    let bytes = std::fs::read(&path).expect("read fixture");
    let result = crate::render::render_bytes(&bytes, "dng", None).expect("render_bytes ok");

    let raw_img = raw_core::decode::decode_bytes(&bytes, "dng").expect("decode");
    let clamp = crate::cpu_budget::clamp_develop_long_edge(raw_img.width, raw_img.height, None)
        .expect("the 100 MP reference must be over the full-develop budget");
    assert_eq!(
        result.width().max(result.height()),
        clamp,
        "render_bytes must develop at the memory clamp for oversized sensors"
    );
    let (nw, nh) = raw_core::pipeline::native_render_dims(&raw_img);
    assert_eq!(
        (result.full_width(), result.full_height()),
        (nw, nh),
        "full_* getters must carry the native oriented dims"
    );
    assert_eq!(
        result.rgb().len(),
        (result.width() as usize) * (result.height() as usize) * 3,
        "packed RGB bytes at the clamped size"
    );
}

/// Repo-root fixture path (raw-wasm sits two levels below src/). Skip-pass
/// when the gitignored RAW is absent, mirroring the raw-core pattern.
fn fixture_path() -> Option<std::path::PathBuf> {
    let path = std::path::PathBuf::from(env!("CARGO_MANIFEST_DIR"))
        .join("../../../test-fixtures/raws/test_0002.dng");
    if path.exists() {
        Some(path)
    } else {
        eprintln!("fixture missing at {:?} — skipping", path);
        None
    }
}

/// #1101: the sized scene-linear entry respects the long-edge cap, keeps
/// the fp16 RGBA contract (alpha = 0x3c00), and reports native dims that
/// match raw-core's `native_render_dims`.
#[test]
fn render_bytes_scene_linear_sized_caps_long_edge_and_reports_native_dims() {
    let Some(path) = fixture_path() else { return };
    let bytes = std::fs::read(&path).expect("read fixture");
    let cap = 768u32;
    let result = render_bytes_scene_linear_sized(&bytes, "dng", None, true, cap)
        .expect("sized scene-linear render ok");
    let (w, h) = (result.width(), result.height());
    assert!(
        w.max(h) <= cap,
        "long edge {} exceeds cap {}",
        w.max(h),
        cap
    );
    let lanes: Vec<u16> = result.fp16_rgba();
    assert_eq!(
        lanes.len(),
        (w as usize) * (h as usize) * 4,
        "4 fp16 lanes per pixel"
    );
    assert_eq!(lanes[3], 0x3c00, "alpha lane must be fp16 1.0");

    let raw_img = raw_core::decode::decode_bytes(&bytes, "dng").expect("decode");
    let (nw, nh) = raw_core::pipeline::native_render_dims(&raw_img);
    assert_eq!(
        (result.full_width(), result.full_height()),
        (nw, nh),
        "full_* getters must carry the native oriented dims"
    );
    assert!(
        result.full_width().max(result.full_height()) > cap,
        "fixture should be larger than the cap for this test to be meaningful"
    );
}

/// #1101: the sized display entry respects the cap, reports native dims,
/// and keeps the `render_bytes` contract (RGB bytes + As-Shot WB seed).
#[test]
fn render_bytes_sized_caps_long_edge_and_matches_as_shot_seed() {
    let Some(path) = fixture_path() else { return };
    let bytes = std::fs::read(&path).expect("read fixture");
    let cap = 768u32;
    let sized =
        render_bytes_sized(&bytes, "dng", None, false, cap).expect("sized display render ok");
    let (w, h) = (sized.width(), sized.height());
    assert!(
        w.max(h) <= cap,
        "long edge {} exceeds cap {}",
        w.max(h),
        cap
    );
    assert_eq!(
        sized.rgb().len(),
        (w as usize) * (h as usize) * 3,
        "packed RGB bytes"
    );

    let raw_img = raw_core::decode::decode_bytes(&bytes, "dng").expect("decode");
    let (nw, nh) = raw_core::pipeline::native_render_dims(&raw_img);
    assert_eq!((sized.full_width(), sized.full_height()), (nw, nh));

    // As-Shot derivation must match the full-size entry bit-for-bit (the
    // sized cold open seeds the same WB sliders) — the slider-frame
    // estimate, not the retired log2(B/R) heuristic (#1892).
    let (expected_cct, expected_tint) = as_shot_wb(&raw_img);
    assert_eq!(sized.as_shot_temperature(), expected_cct);
    assert_eq!(sized.as_shot_tint(), expected_tint);
    // test_0002 (H2D-39) sits far off the Planckian locus — the estimate
    // must carry a real tint, where the old heuristic hard-coded 0.
    assert!(
        expected_tint.abs() > 1.0,
        "frame-consistent as-shot tint should be non-zero for this fixture, got {expected_tint}"
    );
}

/// A 2×2×2 `.mlut` grid mapping every input to pure red — mirrors
/// `gpu_render::tests_film::solid_red_lut` (a mirrored, not shared, private
/// copy — same convention `film_look_tests.rs`'s own `identity_lattice`
/// documents for this feature). Strong enough that a render with it loaded
/// must visibly differ from the no-look render, proving the look is
/// genuinely applied rather than silently ignored.
fn solid_red_mlut_bytes() -> Vec<u8> {
    let mut data = Vec::with_capacity(2 * 2 * 2 * 3);
    for _ in 0..(2 * 2 * 2) {
        data.extend_from_slice(&[1.0, 0.0, 0.0]);
    }
    raw_core::film::encode_mlut(2, &data)
}

/// #2719: sized + film-look union entry. Empty `film_lut_bytes` must render
/// byte-identically to the plain sized entry — the same empty-clears
/// contract `render_bytes_with_film` documents for the unsized path,
/// extended here to the sized one.
#[test]
fn render_bytes_sized_with_film_empty_lut_matches_render_bytes_sized() {
    let Some(path) = fixture_path() else { return };
    let bytes = std::fs::read(&path).expect("read fixture");
    let cap = 768u32;
    let no_lut =
        render_bytes_sized(&bytes, "dng", None, false, cap).expect("plain sized render ok");
    let empty_lut = render_film::render_bytes_sized_with_film(&bytes, "dng", None, false, cap, &[])
        .expect("sized+film render with empty lut ok");
    assert_eq!(no_lut.width(), empty_lut.width());
    assert_eq!(no_lut.height(), empty_lut.height());
    assert_eq!(
        no_lut.rgb(),
        empty_lut.rgb(),
        "an empty film_lut_bytes must render byte-identically to render_bytes_sized"
    );
    assert_eq!(
        no_lut.as_shot_temperature(),
        empty_lut.as_shot_temperature()
    );
    assert_eq!(no_lut.as_shot_tint(), empty_lut.as_shot_tint());
}

/// #2719: with a real (non-empty) film LUT loaded, `render_bytes_sized_with_film`
/// keeps every contract `render_bytes_sized` already has — long-edge cap,
/// native dims, As-Shot WB seed — AND visibly changes the pixels versus the
/// no-look render, proving the look actually reaches the sized develop path
/// rather than being accepted and dropped.
#[test]
fn render_bytes_sized_with_film_caps_long_edge_and_applies_the_look() {
    let Some(path) = fixture_path() else { return };
    let bytes = std::fs::read(&path).expect("read fixture");
    let cap = 768u32;
    let lut_bytes = solid_red_mlut_bytes();

    let with_film =
        render_film::render_bytes_sized_with_film(&bytes, "dng", None, false, cap, &lut_bytes)
            .expect("sized+film render ok");
    let (w, h) = (with_film.width(), with_film.height());
    assert!(
        w.max(h) <= cap,
        "long edge {} exceeds cap {}",
        w.max(h),
        cap
    );
    assert_eq!(
        with_film.rgb().len(),
        (w as usize) * (h as usize) * 3,
        "packed RGB bytes"
    );

    let raw_img = raw_core::decode::decode_bytes(&bytes, "dng").expect("decode");
    let (nw, nh) = raw_core::pipeline::native_render_dims(&raw_img);
    assert_eq!(
        (with_film.full_width(), with_film.full_height()),
        (nw, nh),
        "full_* getters must carry the native oriented dims, same contract as render_bytes_sized"
    );

    // As-Shot derivation is unaffected by the film look — identical to the
    // no-lut sized entry (matches render_bytes_with_film's own as-shot
    // contract for the unsized path).
    let (expected_cct, expected_tint) = as_shot_wb(&raw_img);
    assert_eq!(with_film.as_shot_temperature(), expected_cct);
    assert_eq!(with_film.as_shot_tint(), expected_tint);

    let no_lut =
        render_bytes_sized(&bytes, "dng", None, false, cap).expect("plain sized render ok");
    assert_ne!(
        no_lut.rgb(),
        with_film.rgb(),
        "a solid-red film LUT must visibly change the rendered pixels"
    );
}

/// #1892: a fresh open (no XMP) must develop IDENTICALLY to an explicit
/// `crs:WhiteBalance="As Shot"` sidecar — both resolve to the As-Shot
/// sentinel; neither pushes the display estimate into the model. Pre-#1892
/// the fresh open substituted a heuristic CCT as an explicit target and the
/// two differed.
///
/// Compared on the SCENE-LINEAR entry (where white balance lives), not the
/// display entry: the display tail's Auto Profile fit shares a bytes-keyed
/// cache across render qualities, so concurrent tests rendering this same
/// fixture at a different quality can swap the cached fit between the two
/// renders and flake a display-byte compare (#924's sharing tradeoff).
#[test]
fn render_bytes_scene_linear_fresh_open_matches_as_shot_xmp() {
    let Some(path) = fixture_path() else { return };
    let bytes = std::fs::read(&path).expect("read fixture");
    let cap = 512u32;
    let fresh = render_bytes_scene_linear_sized(&bytes, "dng", None, true, cap)
        .expect("fresh-open develop");
    let as_shot_xmp = r#"<?xpacket begin="" id="W5M0MpCehiHzreSzNTczkc9d"?>
<x:xmpmeta xmlns:x="adobe:ns:meta/"><rdf:RDF xmlns:rdf="http://www.w3.org/1999/02/22-rdf-syntax-ns#">
<rdf:Description rdf:about="" xmlns:crs="http://ns.adobe.com/camera-raw-settings/1.0/" crs:WhiteBalance="As Shot"/>
</rdf:RDF></x:xmpmeta>
<?xpacket end="w"?>"#;
    let explicit =
        render_bytes_scene_linear_sized(&bytes, "dng", Some(as_shot_xmp.to_string()), true, cap)
            .expect("as-shot XMP develop");
    assert_eq!(
        fresh.fp16_rgba(),
        explicit.fp16_rgba(),
        "fresh open and explicit As-Shot XMP must develop byte-identically"
    );
}

/// #3039: `develop_non_raw` is the WASM entry the Web single-file/non-RAW
/// editor session must call on every slider tick. Before it existed,
/// `RawPipelineService.decode()` special-cased non-RAW extensions to a
/// plain `createImageBitmap` + 2D-canvas readback with NO adjustment model
/// applied — so a +EV exposure slider (or any other edit) silently
/// produced byte-identical output regardless of the XMP passed in. That
/// gap never touched WASM at all, which is why the bug produced zero
/// worker/console activity to debug.
///
/// Synthetic mid-grey scene-linear input (this test supplies exactly the
/// buffer `decodeNonRawToSceneLinearF32` would hand the worker — NOT sRGB
/// bytes; `develop_non_raw` never decodes a file). An objective brightness
/// threshold, not a screenshot compare — matches this repo's "no
/// eyeballing" color-testing convention.
#[test]
fn develop_non_raw_applies_exposure_and_never_agx_tone_maps() {
    let width = 4u32;
    let height = 4u32;
    let pixel_count = (width * height) as usize;
    // Mid-grey sRGB (0.5) decoded to linear ((0.5+0.055)/1.055)^2.4 ≈ 0.214 —
    // the exact value doesn't matter for a monotonic exposure check, only
    // that every pixel is identical (so a neutral, flat card stays neutral
    // through the Rec.2020 gamut rotation and the Oklab gamut-compress).
    let grey_linear = 0.214_f32;
    let mut rgba = Vec::with_capacity(pixel_count * 4);
    for _ in 0..pixel_count {
        rgba.extend_from_slice(&[grey_linear, grey_linear, grey_linear, 1.0]);
    }

    let baseline = develop_non_raw(&rgba, width, height, None).expect("baseline develop ok");
    assert_eq!(
        baseline.source_orientation(),
        1,
        "browser-decoded pixels are already oriented"
    );
    let baseline_rgb = baseline.rgb();
    assert_eq!(baseline_rgb.len(), pixel_count * 3);

    let boosted_xmp = r#"<?xpacket begin="" id="W5M0MpCehiHzreSzNTczkc9d"?>
<x:xmpmeta xmlns:x="adobe:ns:meta/"><rdf:RDF xmlns:rdf="http://www.w3.org/1999/02/22-rdf-syntax-ns#">
<rdf:Description rdf:about="" xmlns:crs="http://ns.adobe.com/camera-raw-settings/1.0/" crs:Exposure2012="2.0"/>
</rdf:RDF></x:xmpmeta>
<?xpacket end="w"?>"#;
    let boosted = develop_non_raw(&rgba, width, height, Some(boosted_xmp.to_string()))
        .expect("boosted develop ok");
    let boosted_rgb = boosted.rgb();
    assert_eq!(boosted_rgb.len(), pixel_count * 3);

    // This is the exact symptom #3039 reported: identical bytes regardless
    // of the adjustment model. A +2 EV exposure boost must brighten every
    // channel of every pixel.
    for i in 0..baseline_rgb.len() {
        assert!(
            boosted_rgb[i] > baseline_rgb[i],
            "byte {} did not brighten under +2 EV: baseline={} boosted={}",
            i,
            baseline_rgb[i],
            boosted_rgb[i]
        );
    }

    // `skip_agx` contract: the default-model baseline must render close to
    // the input grey card, not scene-referred-tone-mapped by AgX (which
    // would visibly compress a mid-grey input toward a different value —
    // see `ChainOptions::skip_agx`'s doc and this fn's module doc).
    assert!(
        (100..=160).contains(&baseline_rgb[0]),
        "default-model baseline should render close to the input grey \
         without AgX view-transform tone-mapping, got {}",
        baseline_rgb[0]
    );
    // Neutral in -> neutral out (no per-channel bias from the gamut steps).
    assert_eq!(baseline_rgb[0], baseline_rgb[1]);
    assert_eq!(baseline_rgb[1], baseline_rgb[2]);
}

/// #3039 review: a dedicated, TIGHT-tolerance identity check, independent of
/// the exposure-boost test above. That test's `100..=160` window is correct
/// for "close to the input, not AgX-tone-mapped" but far too loose to catch a
/// genuine identity bug — a double sRGB decode (or a missing re-encode) would
/// land the baseline near byte 55 (`0.5.powf(2.2) * 255`), comfortably inside
/// `100..=160`'s SIBLING test without ever failing it. This test exists
/// because exactly that class of bug was suspected during review: an
/// independent verification reported a #808080 grey card rendering at
/// compositor mean ~39/255 with NO edits applied, which — if real — would be
/// a scene-linear round-trip failure, not an exposure-application failure.
///
/// Input is the EXACT linear value the real Web pipeline produces for a
/// `#808080` canvas readback: `srgb_decode(128/255)` via the same IEC
/// 61966-2-1 formula `decodeNonRawToSceneLinearF32`'s LUT implements
/// (`image-utils.ts`'s `srgbToLinear`) — not an approximated constant, so
/// this test would catch a mismatched transfer function on either side.
///
/// Result: this test PASSES (baseline round-trips to 127/255, i.e. within 1
/// of identity) — proving `develop_non_raw`'s own math is correct in
/// isolation. The reported ~39/255 in the field is NOT reproduced at this
/// layer; see `image-utils.spec.ts`'s equivalent TS-side check and this
/// commit's PR description for where the investigation looked next.
#[test]
fn develop_non_raw_default_model_round_trips_grey_within_tight_tolerance() {
    let width = 4u32;
    let height = 4u32;
    let pixel_count = (width * height) as usize;
    let byte: f32 = 128.0;
    let srgb = byte / 255.0;
    // IEC 61966-2-1 sRGB electro-optical transfer (display -> linear) — the
    // exact formula `image-utils.ts`'s `srgbToLinear` implements. `0.5`
    // sRGB is comfortably past the `<= 0.04045` linear-segment threshold, so
    // this always takes the power-law branch.
    let grey_linear = ((srgb + 0.055) / 1.055).powf(2.4);

    let mut rgba = Vec::with_capacity(pixel_count * 4);
    for _ in 0..pixel_count {
        rgba.extend_from_slice(&[grey_linear, grey_linear, grey_linear, 1.0]);
    }

    let baseline = develop_non_raw(&rgba, width, height, None).expect("baseline develop ok");
    assert_eq!(
        baseline.source_orientation(),
        1,
        "browser-decoded pixels are already oriented"
    );
    let rgb = baseline.rgb();
    assert_eq!(rgb.len(), pixel_count * 3);

    // Tolerance: +/-2/255 per channel — objective, no visual judgment. A
    // double-gamma bug (decode twice, or never re-encode) misses this by
    // 60-90/255, nowhere near this window.
    for (i, &channel) in rgb.iter().enumerate() {
        let diff = (i32::from(channel) - byte as i32).abs();
        assert!(
            diff <= 2,
            "byte {i} = {channel}, expected {byte} +/- 2 (default model must be a near-identity \
             round trip: srgb-decode -> chain (skip_agx, no edits) -> srgb-encode), got diff {diff}",
        );
    }
}
