"""Generate canonical exp(-i/64) f32 bits, independent of host expf/libm."""

import struct
from decimal import Decimal, localcontext
from pathlib import Path


def generate():
    with localcontext() as context:
        context.prec = 80
        bits = [
            struct.unpack("<I", struct.pack("<f", float((-Decimal(i) / 64).exp())))[0]
            for i in range(513)
        ]
    return (
        "// Generated by tools/generate_nlm_exp_table.py. Do not edit.\n"
        "// exp(-i/64), rounded to binary32 from 80-digit decimal precision.\n"
        "// Included by CPU and GPU hosts; no target-specific libm calls.\n"
        "pub(super) const VALUES: [f32; 513] = [\n"
        + "".join(f"    f32::from_bits(0x{value:08x}),\n" for value in bits)
        + "];\n"
    )


if __name__ == "__main__":
    destination = (
        Path(__file__).resolve().parents[1]
        / "src/raw-pipeline/raw-core/src/stages/nlm_exp_table.rs"
    )
    destination.write_text(generate(), encoding="utf-8", newline="\n")
