//! One-shot Hasselblad DCP extractor. Run when test_0000.DNG changes
//! (rare). Dumps ColorMatrix1, ColorMatrix2, AsShotNeutral, and the
//! calibration illuminant codes in source-pasteable form.
//!
//!   cargo run --release -p raw-core --features test-support \
//!       --example extract-dcp -- test-fixtures/raws/test_0000.DNG

use raw_core::decode::decode_bytes;
use std::env;

fn main() -> Result<(), Box<dyn std::error::Error>> {
    let path = env::args()
        .nth(1)
        .ok_or("usage: extract-dcp <path-to-dng>")?;
    let bytes = std::fs::read(&path)?;
    let raw = decode_bytes(&bytes, "dng")?;

    println!("// Auto-generated by examples/extract-dcp.rs from {}", path);
    println!("// camera: {} {}", raw.camera_make, raw.camera_model);
    println!();
    let mut entries: Vec<_> = raw.color_matrices.iter().collect();
    entries.sort_by_key(|(illum, _)| format!("{:?}", illum));
    for (illum, mat) in entries {
        println!("// ColorMatrix for {:?}:", illum);
        println!("pub const COLOR_MATRIX_{:?}: [[f32; 3]; 3] = [", illum);
        for row in 0..3 {
            print!("    [");
            for col in 0..3 {
                if col > 0 {
                    print!(", ");
                }
                print!("{:.6}", mat.0[row][col]);
            }
            println!("],");
        }
        println!("];");
        println!();
    }
    println!(
        "pub const AS_SHOT_NEUTRAL: [f32; 3] = [{:.6}, {:.6}, {:.6}];",
        raw.as_shot_neutral[0], raw.as_shot_neutral[1], raw.as_shot_neutral[2]
    );
    Ok(())
}
