//! Computes Rust AgX outputs for the Spike 1.2 fixed test grid.
//! Run from src/raw-pipeline/raw-core via:
//!   cp /tmp/spike_1_2_compute_refs.rs examples/spike_1_2_refs.rs
//!   cargo run --release -p raw-core --example spike_1_2_refs
//! Emits Swift-source-ready array literal to stdout.

use raw_core::image::{ColorSpace, Image};

fn agx(r: f32, g: f32, b: f32) -> [f32; 3] {
    let mut img = Image::new(1, 1, ColorSpace::SceneLinearRec2020);
    img.pixels[0] = [r, g, b];
    raw_core::view::agx::apply(&mut img, 0.0);
    img.pixels[0]
}

fn main() {
    // Spike 1.2 brief: fixed grid of scene-linear Rec.2020 pixels.
    // mid-gray, highlights, deep shadows, saturated reds/greens/blues,
    // near-zero values, near-AGX_MAX_EV.
    let mid_gray = 0.18_f32;
    let max_ev = 6.5_f32;
    let min_ev = -10.0_f32;
    let cases: &[(&str, [f32; 3])] = &[
        ("mid_gray",         [mid_gray, mid_gray, mid_gray]),
        ("highlight_neutral",[5.0,      5.0,      5.0]),
        ("deep_shadow",      [0.001,    0.001,    0.001]),
        ("near_zero",        [1e-6,     1e-6,     1e-6]),
        ("saturated_red",    [20.0 * mid_gray, mid_gray, mid_gray]),
        ("saturated_green",  [mid_gray, 20.0 * mid_gray, mid_gray]),
        ("saturated_blue",   [mid_gray, mid_gray, 20.0 * mid_gray]),
        ("near_max_ev",      [mid_gray * (max_ev - 0.1).exp2(); 3]),
        ("at_min_ev",        [mid_gray * min_ev.exp2(); 3]),
        ("ungamuty_red_only",[2.5,      0.0,      0.0]),
        ("hot_specular_R",   [50.0,     0.18,     0.18]),
        ("low_R_high_BG",    [0.01,     2.0,      2.0]),
        ("near_one_neutral", [1.0,      1.0,      1.0]),
        ("blackish",         [0.0,      0.0,      0.0]),
    ];
    println!("// Generated by examples/spike_1_2_refs.rs (AGX_VERSION 5).");
    println!("// Each row: scene_in [R G B], display_out [R G B] from view::agx::apply.");
    println!("static let rustReferenceOutputs: [(label: String, scene: SIMD3<Float>, display: SIMD3<Float>)] = [");
    for (label, scene) in cases {
        let out = agx(scene[0], scene[1], scene[2]);
        println!(
            "    (label: \"{}\", scene: SIMD3<Float>({}, {}, {}), display: SIMD3<Float>({}, {}, {})),",
            label,
            scene[0], scene[1], scene[2],
            out[0], out[1], out[2],
        );
    }
    println!("]");
}
