//! Computes Rust AgX outputs for the Spike 1.2 fixed test grid.
//! Run from src/raw-pipeline/raw-core via:
//!   cargo run --release -p raw-core --example spike_1_2_refs
//! Emits Swift-source-ready array literal to stdout.
//!
//! NOTE: this example deliberately exercises the **per-channel LUT path
//! only** (log-encode → normalize → contrast-modulate → sigmoid LUT),
//! NOT `view::agx::apply` — at AGX_VERSION 7 (#263) that wrapper became
//! a full Sobotka pipeline (luma-coupled toe → INSET matrix →
//! per-channel sigmoid LUT → OUTSET matrix → clamp). The Swift Spike 1.2
//! mirror (`agxPerChannelLUT` in `SceneLinearPipelineTests.swift`) only
//! models the per-channel sigmoid stage, so we generate Rust reference
//! outputs from the same per-channel kernel for apples-to-apples parity.
//! Coefficients come from `view::agx_coeffs`; LUT bytes from
//! `agx_lut.bin`.

use raw_core::view::agx::{AGX_LUT_SIZE, AGX_MAX_EV, AGX_MID_GRAY, AGX_MIN_EV};

/// Per-channel AgX kernel — byte-identical to the private `agx_per_channel`
/// fn in `view::agx`, mirrored here so the example can call it without
/// going through `apply` (which now wraps the per-channel kernel with
/// `preform_rolloff`). Keep in sync with `view/agx.rs:67-77`.
fn agx_per_channel(scene: f32, lut: &[f32], slope: f32) -> f32 {
    let mid_norm = -AGX_MIN_EV / (AGX_MAX_EV - AGX_MIN_EV);
    let floor = AGX_MID_GRAY * AGX_MIN_EV.exp2();
    let clamped = scene.max(floor);
    let logv = (clamped / AGX_MID_GRAY)
        .log2()
        .clamp(AGX_MIN_EV, AGX_MAX_EV);
    let norm = (logv - AGX_MIN_EV) / (AGX_MAX_EV - AGX_MIN_EV);
    let contrast_adjusted = (mid_norm + (norm - mid_norm) * slope).clamp(0.0, 1.0);
    sample_lut(contrast_adjusted, lut).clamp(0.0, 1.0)
}

/// Linear-interpolated LUT sample, mirror of `view::agx::sample_lut`.
fn sample_lut(x: f32, lut: &[f32]) -> f32 {
    let n = lut.len();
    let x = x.clamp(0.0, 1.0);
    let idx = x * ((n - 1) as f32);
    let i0 = idx.floor() as usize;
    let i1 = (i0 + 1).min(n - 1);
    let f = idx - (i0 as f32);
    lut[i0] * (1.0 - f) + lut[i1] * f
}

fn load_lut() -> Vec<f32> {
    // Resolved relative to CARGO_MANIFEST_DIR so the example runs from
    // either the workspace root or the raw-core crate.
    let path = std::path::Path::new(env!("CARGO_MANIFEST_DIR")).join("src/view/agx_lut.bin");
    let bytes =
        std::fs::read(&path).unwrap_or_else(|e| panic!("failed to read {}: {}", path.display(), e));
    assert_eq!(
        bytes.len(),
        AGX_LUT_SIZE * 4,
        "agx_lut.bin size mismatch: expected {} bytes, got {}",
        AGX_LUT_SIZE * 4,
        bytes.len()
    );
    bytes
        .chunks_exact(4)
        .map(|c| f32::from_le_bytes([c[0], c[1], c[2], c[3]]))
        .collect()
}

fn agx(r: f32, g: f32, b: f32, lut: &[f32]) -> [f32; 3] {
    [
        agx_per_channel(r, lut, 1.0),
        agx_per_channel(g, lut, 1.0),
        agx_per_channel(b, lut, 1.0),
    ]
}

fn main() {
    // Spike 1.2 brief: fixed grid of scene-linear Rec.2020 pixels.
    // mid-gray, highlights, deep shadows, saturated reds/greens/blues,
    // near-zero values, near-AGX_MAX_EV.
    let lut = load_lut();
    let mid_gray = 0.18_f32;
    let max_ev = 6.5_f32;
    let min_ev = -10.0_f32;
    let cases: &[(&str, [f32; 3])] = &[
        ("mid_gray", [mid_gray, mid_gray, mid_gray]),
        ("highlight_neutral", [5.0, 5.0, 5.0]),
        ("deep_shadow", [0.001, 0.001, 0.001]),
        ("near_zero", [1e-6, 1e-6, 1e-6]),
        ("saturated_red", [20.0 * mid_gray, mid_gray, mid_gray]),
        ("saturated_green", [mid_gray, 20.0 * mid_gray, mid_gray]),
        ("saturated_blue", [mid_gray, mid_gray, 20.0 * mid_gray]),
        ("near_max_ev", [mid_gray * (max_ev - 0.1).exp2(); 3]),
        ("at_min_ev", [mid_gray * min_ev.exp2(); 3]),
        ("ungamuty_red_only", [2.5, 0.0, 0.0]),
        ("hot_specular_R", [50.0, 0.18, 0.18]),
        ("low_R_high_BG", [0.01, 2.0, 2.0]),
        ("near_one_neutral", [1.0, 1.0, 1.0]),
        ("blackish", [0.0, 0.0, 0.0]),
    ];
    println!("// Generated by examples/spike_1_2_refs.rs (AGX_VERSION 6, per-channel LUT path).");
    println!("// Each row: scene_in [R G B], display_out [R G B] from the per-channel AgX");
    println!("// kernel (log-encode → normalize → contrast-modulate → sigmoid LUT).");
    println!("// This is NOT `view::agx::apply` output — that wraps the per-channel");
    println!("// kernel with `preform_rolloff`, which the Swift mirror does not implement.");
    println!("static let rustReferenceOutputs: [(label: String, scene: SIMD3<Float>, display: SIMD3<Float>)] = [");
    for (label, scene) in cases {
        let out = agx(scene[0], scene[1], scene[2], &lut);
        println!(
            "    (label: \"{}\", scene: SIMD3<Float>({}, {}, {}), display: SIMD3<Float>({}, {}, {})),",
            label,
            scene[0], scene[1], scene[2],
            out[0], out[1], out[2],
        );
    }
    println!("]");
}
